### ISSUE TITLE
We should go back to using `importlib.import_module` for importing extensions

### ISSUE THREAD

**Issue by bswck** [Rapptz/discord.py#10017]
### Summary

`load_extension` currently incorrectly implements parts of the import system in a thread-unsafe way and without reusing modules from the `sys.modules` registry, which is potentially harmful in some circumstances.

The nature of Python's import system makes all module-level code thread-safe; `load_extension` breaks that.

### Reproduction Steps

In your current working directory, paste appropriate contents to properly named files:

```py
# repro.py
import os

from discord import Intents
from discord.ext.commands import Bot

from ext import ExtCog  # early import the extension


class MyBot(Bot):
    async def setup_hook(self) -> None:
        await self.load_extension("ext")  # use load_extension to auto-exec the `setup()` callback

        cog_from_ext = self.get_cog("ExtCog")
        assert (
            repr(type(cog_from_ext)) == repr(ExtCog) == "<class 'ext.ExtCog'>"
        )  # passes
        assert type(cog_from_ext) is ExtCog  # fails!


if __name__ == "__main__":
    MyBot((), intents=Intents()).run(os.environ["TOKEN"])
```

```py
# ext.py
from discord.ext.commands import Bot, Cog


class ExtCog(Cog):
    pass


async def setup(bot: Bot) -> None:
    await bot.add_cog(ExtCog())
```

Now run `TOKEN=<paste your token here> python -m repro` from there.

There may be a lot of reasons to prefetch the extension modules before running the bot.

As you can see, we got two modules `ext` that now conflict (dpy unnecessarily reimported `ext` using low-level thread-unsafe utilities from `importlib.util`, instead of reusing what's in the `sys.modules` cache—which is a default if we used `importlib.import_module`—which at the end resulted in the eagerly-imported `ext` hanging with technically obsolete information).

My reason for eager importing of the extension modules was that I wanted to validate all extension names supplied via config are correct and I wanted to avoid the side effect of blocking the async event loop with disk I/O of imports (if I were to import things in the loop, I'd most likely use `asyncio.to_thread` to not make the loop freeze for even tiny fractions of seconds, but that is out of scope of the issue).

I strongly recommend going back to using `importlib.import_module` that reuses `sys.modules` and guarantees thread safety (contrary to what the current `load_extension` implementation does). [`importlib.util`](https://docs.python.org/3/library/importlib.html#module-importlib.util) was not meant to be used as a toolbox for performing manual imports; it was a toolbox for use in constructing importers that already tie in to the import machinery system, carried out by the `importlib.import_module`/`__import__` facade that does a lot of work to ensure thread safety and no lock ordering deadlocks (with the help of [`importlib._bootstrap._ModuleLockManager`](https://github.com/python/cpython/blob/d6b3e78504b3168c432b20002dbcf8ec9a435e61/Lib/importlib/_bootstrap.py#L1356-L1359) and [some related code](https://github.com/python/cpython/blob/4cd10762b06ec57252e3c7373e74240b4d0c5ed8/Lib/importlib/_bootstrap.py#L138-L477)).

### Expected Results

- `load_extension` reusing `sys.modules` cache and not breaking the import system thread safety

### Actual Results

- `load_extension` incorrectly implementing some parts of the import system in a thread-unsafe way (potentially harmful in some circumstances, as in the repro)

### Intents

default

### System Information

```
- Python v3.12.7-final
- discord.py v2.4.0-final
- aiohttp v3.11.2
- system info: Linux 5.15.167.4-microsoft-standard-WSL2 #1 SMP Tue Nov 5 00:21:55 UTC 2024
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by bswck** [comment]
Please LMK if you welcome a PR on that!

**Comment by Rapptz** [comment]
This is intended. In fact this issue of stale references can show up regardless of whether I use `importlib.import_module` or not, it's just a consequence of types being different which happens a lot when reloading code, which is the entire point of these modules.

Please note that the original reason *why* import_module is no longer used is because it makes it hard to differentiate between an import error in the actual module code execution vs the module not being found. See [here](https://github.com/Rapptz/discord.py/commit/0a21591d0c778f3f3596362fb1ae92ffc137e576) for the original commit reasoning.

**Comment by bswck** [comment]
> this issue of stale references can show up regardless of whether I use importlib.import_module or not

Sorry, but I don't see how. The only case I can imagine is if we reload a module which we early `from`-imported from, which is out of scope of this issue.

> it's just a consequence of types being different which happens a lot when reloading code, which is the entire point of these modules.

Types? Every module-level expression would get re-evaluated, not just types.

> Please note that the original reason why import_module is no longer used is because it makes it hard to differentiate between an import error in the actual module code execution vs the module not being found

Why is it necessary to differentiate between those? Is there a use case of programmatically catching only `ExtensionNotFound` and not `ExtensionFailed`, or is it just the custom semantics that dpy aims to have in its tracebacks?

**Comment by bswck** [comment]
In short: I'd expect `load_extension` to load an extension (and not reimport the extension module if it's already imported).
I'd never expect a function other than `reload_extension` to reload the extension module for me.

**Comment by Rapptz** [comment]
> Sorry, but I don't see how. Refs don't get stale if we reuse what's already in sys.modules. The only case of regardless stale references I can imagine is if we reload a module which we early from-imported from, which is out of the scope of this issue.

This is the exact scenario I describe, while it's not the issue you describe in your body it's a common issue nonetheless so the motivation to fix it is just not there for the same reasons.

> Types? Every module-level expression and stmt would get re-evaluated,

I'm talking about the import and usage of types and then checking their references. I'm aware that module code gets re-executed.

> Why is it necessary to differentiate between those?

Because people run into this issue and that's why it got fixed. A lot of code expects to properly report the error for developer ergonomics, so when they see a generic "ExtensionNotFound" but it *is* there they think it's a bug in the library and report it when it's just a bug in user code, therefore it makes sense to fix it for the user to point them in the right direction that no, the reason the import failed is because your code imported a non-existent module. Which leads to them fixing the improper code and then reloading the module with the fixes.

**Comment by bswck** [comment]
> This is the exact scenario I describe, while it's not the issue you describe in your body it's a common issue nonetheless so the motivation to fix it is just not there for the same reasons.

I'd opt for disrecommending eagerly `from`-importing modules that would later be intended to be reloaded.
[`importlib.reload` docs](https://docs.python.org/3/library/importlib.html#importlib.reload) outline the caveats of reloading modules and include that case. `from` imports is not a generally solvable problem (but yet `importlib.reload` found its use cases in REPL and wasn't a reason to drop the effort)—maybe that issue shouldn't be a blocker for improving the extension loading mechanism.

I'm mentioning `importlib.reload` here for an example; I am aware that it's not used in extension loading routines and [maybe generally shouldn't](https://github.com/python/cpython/issues/126548#issuecomment-2463367960).

> Because people run into this issue and that's why it got fixed. A lot of code expects to properly report the error for developer ergonomics, so when they see a generic "ExtensionNotFound" but it is there they think it's a bug in the library and report it when it's just a bug in user code

I agree that `ExtensionNotFound` is not a proper class name for an exception caused by an import error from an extension module that _has_ been found—but let's switch our assumptions.

If the exception class name is `ExtensionFailed` and we let the developer inspect the failure being either `ImportError` from not being able to find the module or an `ImportError` from inside the found extension module code (dpy doesn't have to know which one it really is), I don't see why it wouldn't be a better and easier approach in the long run (from the practical POV: less code to maintain, less edge cases and uncertainty coming from reimplementing parts of the import system with zero thread safety guarantees). An additional hint may be added in both cases (because dpy wouldn't know the root reason), "can the module be found"? Or, a post-check can be added to check if the spec can be found _after_ an import error occured (but that can have some edge cases) to really differentiate. That way we don't lose the robustness of the public API actually intended for programmatic imports. WDYT?

**Comment by Rapptz** [comment]
> I'd opt for disrecommending eagerly from-importing modules that would later be intended to be reloaded.

This is already not recommended to do. It doesn't stop people from doing it. I don't know how large your bots are in terms of code complexity but this issue pops up naturally for a lot of people and they eventually try it expecting it to work.

> WDYT?

If a better API comes around that allows for the code to work as intended here with the differentiation that is currently desirable then I'll switch to it. Otherwise I'm sticking with the code that works and has worked for the past 5 years.

**Comment by bswck** [comment]
Well, you could technically match on `ModuleNotFoundError: No module named '(?P<module_name>\w[\d\.\w]+)'` (or whatever the pattern should be)... and confirm with [audit hooks](https://docs.python.org/3/library/sys.html#sys.addaudithook) (if it's really necessary; would someone want to fake a `ModuleNotFoundError`? Python is all about consenting adults anyway...), which is what audits are documented to be intended to (_Note that audit hooks are primarily for collecting information about internal or otherwise unobservable actions, whether by Python or **libraries written in Python**._)... an audit hooks shouldn't be overly slow, and it could be disabled depending on `__debug__`...

**Comment by Rapptz** [comment]
This is going to be my last response here, sorry.

I don't know what the added benefit is here to go for something as brittle as regex matching on an exception compared to just leaving the code work as-is like it has years. Not to mention the audit hook. You're already eagerly importing code that shouldn't be eagerly imported per library recommendations. The thread safety argument doesn't work very well since asyncio is single threaded and there are other issues in asyncio, aiohttp, and this library with the free standing GIL-free build before this becomes a concern, and if necessary could just be solved by a lock instead of switching to a different API.

About the only change I'm willing to accept here is probably stronger documentation warning that extensions shouldn't be eagerly imported somewhere, but as far as code changes go this is entirely within how it's been explicitly designed.

**Comment by bswck** [comment]
I see.

"Worked as-is like it for years" is not an argument, but it's OK to simply disagree. "Other issues in asyncio, aiohttp" is not an argument either.

> You're already eagerly importing code that shouldn't be eagerly imported per library recommendations.

Sorry, I must have overlooked it.

The regex/audit propositions were obviously not ideal, but I also suggested post-check of finding the spec after an error, and it was ignored.

I as well don't see why you would need to tell a difference and use a custom class. But I get it that it can be hard from backward compatibility perspective now.

I'm not going to contribute to this either, because I don't feel like an attempt was ever made to understand the motivation behind this issue, and that's extremely demotivating. Thanks.
