### ISSUE TITLE
Setting a role on member join

### ISSUE THREAD

**Issue by iDragoon** [Rapptz/discord.py#1017]
I'm totally new to phyton programming and I was trying to create a bot for discord, I know the basics and I was trying to add a role as soon as a new member joined the server, how can I do that?
I made a test code but it is not working
![screenshot_1](https://user-images.githubusercontent.com/35436890/34922447-0a819872-f977-11e7-9514-b3b112a67609.png)

**Comment by LewdNeko** [comment]
You should be able to get better help by joining the d.py support server. Use this invite to join :) https://discord.gg/r3sSKJJ

**Comment by Vexs** [comment]
You're making a lot of basic mistakes. 

get_user_info takes in an ID, and gets basic user info from the api- it also has a rather strict ratelimit, and is a coro, needing to be awaited- and since you already have the user information in the form of a member object, pointless here.

Furthermore, you then check if a string is none...?

Anyway, add_roles takes in a member object and a role object. You're providing it with a list of roles the member has, and a string. Take a look at this [this in the FAQ,]
(http://discordpy.readthedocs.io/en/latest/faq.html#how-do-i-get-a-specific-user-role-channel-server) as well as the documentation on [add_roles](http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.add_roles)

**Comment by JulianPEllis** [comment]
@iDragoon By the way. your line `role='id'` would not work. You must use `discord.Object(id='ID HERE')`

**Comment by Harmon758** [comment]
Please don't necrobump issues.
@Vexs already addressed this.
