### ISSUE TITLE
create_invite doesn't accept Server as destination

### ISSUE THREAD

**Issue by ulgens** [Rapptz/discord.py#1019]
[The document](http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.create_invite) says 

```
create_invite(destination, **options)
Creates an invite for the destination which could be either a Server or Channel.
```

but when i try to create an invite with Server as destination, i'm getting `NOT FOUND (status code: 404): Unknown Channel` error.

`Client.create_invite` calls `self.http.create_invite` with this line:

```r = Route('POST', '/channels/{channel_id}/invites', channel_id=channel_id)```

It's obvious that, the call is not for using with Server. Also, in [HTTP API's  doc](https://discordapp.com/developers/docs/resources/channel#create-channel-invite), there isn't any mention to server for that method and there is no other method to create an invitation for a server.

There are to possible solutions:
* Fixing the misleading documentation
* If the parameter is server, creating an invitation for it's main channel.

I'd prefer second one.

**Comment by Vexs** [comment]
This is due to the removal of the default channel from discord, the default channel had the same id as the server- there isn't a failsafe way to select a "general" channel either. This issue is present in send_message, etc. 

This issue is no longer present on the rewrite branch, and the async branch is on non-breaking bugfixes.
