### ISSUE TITLE
cache_auth file is world readable (security concern)

### ISSUE THREAD

**Issue by NelsonMinar** [Rapptz/discord.py#104]
discord.py caches a token for server logins. On my Linux system the cache file is in `/tmp/discord_py` and both the directory and the file are world readable. That means anyone with access to my Linux system could use my Discord login's credentials.

I think the solution is to change [the code that creates the cache file](https://github.com/Rapptz/discord.py/blob/async/discord/client.py#L200-L203) to make the file only readable by the owner. It'd be nice to use the `tempfile` module in Python to create the file, but I'm not sure it's quite suitable. Using `os.chmod()` to make the file mode 0600 should work but then that needs a bit of testing on non-Unix platforms.

I'm filing this issue now to document it. I should be able to contribute a pull request to close it, but it may take a few days.

**Comment by Hornwitser** [comment]
This is only really a problem on multi-user systems *nix systems.  If an unauthorized third party is able to read files on your system, your discord tokens being stolen will be the least of your problems.  But if desired, you can easily change this behavior without having to modify the library by doing the command `umask 077` before running your python discord bot.

**Comment by Ghent** [comment]
*"This is only really a problem on multi-user systems *nix systems. If an
unauthorized third party is able to read files on your system, your discord
tokens being stolen will be the least of your problems."*

What a particularly odd thing to say.  Leaving authentication information
in a file in /tmp that is potentially world readable because the software
creating it does nothing to secure it is just pure laziness.  Rationalizing
that behavior by saying that it's the least of someone's problems is just
plain ignorant.  Would the glib response be the same if someone were
talking about your computer account, email account, Facebook or other
social media account?  Multiple users having access to the same files is
the hallmark of a multiuser system, whether it's *unix or Windows or any
other OS.

Having the software itself open and write the file securely in Python is
extremely easy and any piece of software should take steps to be as secure
as possible, especially with user's authentication information.  Yes, the
user can change their umask.  But any good programmer knows you don't rely
on the user to properly execute and protect the environment, especially
where security is concerned.  If we did, we wouldn't need to encrypt
passwords.

I highly appreciate all the work that the folks working on Python's discord
API library do, but I couldn't in good conscience read that response and
not respond with dismayed surprise.

**Comment by NelsonMinar** [comment]
I've submitted a pull request and hopefully that will end the question.

**Comment by Ghent** [comment]
Nelson,

Allow me to be the first user to thank you for watching out for me and my
authentication information.  I appreciate it very, very much! I hope the PR
gets processed soon!
