### ISSUE TITLE
wait_for is not calling a check function in this case

### ISSUE THREAD

**Issue by bmintz** [Rapptz/discord.py#1047]
bot.py and emoji.py are here:
https://gist.github.com/bmintz/f523946aec2895d897b99624968400bf

## Problem steps

1. Run `@Bot react <message id>` (message ID is in the same channel as the one where you invoke the command)
2. Click the new reaction on that message.

## Expected behavior

1. A reaction is added to that message.
2. The reaction added by the bot is immediately removed, and 'got reaction', followed by `True` three times is printed.

## Actual behavior

1. A reaction is added to that message.
2. The reaction added by the bot is only removed after 30s. Nothing is printed.

**Comment by Rapptz** [comment]
This is a problem with the code rather than the library.

You are basically saying:

1. Add a reaction.
2. Wait for a reaction to happen.
3. Remove that reaction

What you are expecting is something else:

1. Wait for a reaction to happen.
2. Add a reaction.
3. Remove that reaction.

As you can see, the sequence of events in your expectations vs the code is off. 

To fix this just place the `wait_for` before the `add_reaction` call.

**Comment by bmintz** [comment]
Sorry, I should clarify my expectations:
1. Bot adds a reaction to the message.
2. User clicks on the button to add the same emote as a reaction to the same message.
3. Bot notices (2) and removes its own reaction from the same message.

**Comment by bmintz** [comment]
Turns out the answer was `raw_reaction_add`, not `reaction_add`. When in doubt, use raw.
