### ISSUE TITLE
Updating "Playing"

### ISSUE THREAD

**Issue by Yalnix** [Rapptz/discord.py#1053]
My current playing code looks something like this:
`await client.change_presence(game=discord.Game(name="GRLC: "+(price_info[0])["price_usd"]), status=discord.Status("online"))`

but for whatever reason when this gets processed then it never actually changes on discord.

**Comment by Nekorooni** [comment]
Does it happen to be a selfbot?

**Comment by khazhyk** [comment]
what version are you using?

**Comment by Gorialis** [comment]
**If you're using a standard (OAuth) bot:**
In August, Discord made a change to presence that required sent presences to include `type`, even if it was 0.
Before [v0.16.9](https://github.com/Rapptz/discord.py/commit/7f18efdafe769573f9d4ccc6459dbb7b7c329a31) (async) and [1318@b8c1995](https://github.com/Rapptz/discord.py/commit/b8c19954e444f88a6667761cc27bcf16693f5544) (rewrite), no `type` was sent by default, so when this change happened, presences wouldn't display unless you set a `type` explicitly. Solution for this would be to update your library.

**If you're using a selfbot/userbot:**
The way presence works for user accounts has changed slightly since it was last directly supported by this library.
User accounts never receive their own `PRESENCE_UPDATE` events, even from other clients, so a presence emitted from one client (such as your desktop Discord client) would not be seen by another (such as your phone). This applies for your bot too, if your selfbot emits a presence, your desktop Discord client won't see it.

However, now, if you play a game on your computer, you can sometimes see the presence from your phone. Why?

Turns out, at some point, Discord made the official client POST to API endpoints when you start playing a game. This only applies to user accounts, and it seems (from testing) that it only relays when the game you're playing is verified.

You could use the Networking tab from within devtools to work out how exactly this flow works, if you're very determined to have your presence relay to other clients. I wouldn't particularly recommend it though, and with the harsher sanctions Discord has been issuing for userbots, I doubt it would be added to this library.

To spare yourself the effort, I'd use an alt account, a bot, or asking another user to determine if your presence has been set correctly, as they will all receive your presence as normal from just the gateway event.

**Comment by pedroricardo** [comment]
with me add, listening and watching instead of playing?

**Comment by Gorialis** [comment]
@pedroricardo Abstracted (user-friendly) extra presence modes aren't in this lib yet (but are [planned](https://github.com/Rapptz/discord.py/pull/908#issuecomment-345438446) for rewrite), but as they are just extra `Game` modes as of current, you can still set them by just using the `type` kwarg for `Game` with the respective values:
- `0` - 'Playing', default
- `1` - 'Streaming', requires valid twitch URL
- `2` - 'Listening to'
- `3` - 'Watching'
In future you should probably open a [new issue](https://github.com/Rapptz/discord.py/issues/new) to ask questions like this.

**Comment by pedroricardo** [comment]
That's what I was looking for. Thank you.

**Comment by Yalnix** [comment]
Thanks guys. Issue was that I hadn't explicitly set the type and didn't know it was on the game and not change_presence.
