### ISSUE TITLE
Message.Author showing empty result

### ISSUE THREAD

**Issue by ZeroX25** [Rapptz/discord.py#1054]
```
import discord
from discord.ext import commands

class challenge:
    """Challenges another player by using !challenge @playername"""

    def __init__(self, bot):
        self.bot = bot

    @commands.command(pass_context=True)
    
    async def challenge(self,ctx,user: discord.Member,member: discord.Member = None, ):
        """This will send a challenge out to a player."""
        if member is None: member = ctx.message.author		
        await self.bot.say(user.mention + " has been challenged by @".format(member) + "!")

def setup(bot):
    bot.add_cog(challenge(bot))
```

I'm having an issue with seeing the author of the previous message. I want ctx.message.author to be the user that inputs` !challenge <@user.id>` into discord, but what I get out of the prompt is this:
<@user.id> has been challenged by **@!**
Is the author returning a blank string? Or do I need to set up a log that finds the last !challenge message and pulls the author from there?

**Comment by datmellow** [comment]
It's best to not mix up string concatenation with .format and stick with a single way (preferably .format)

Your error comes because you have no placeholders in your string.

You can learn more about formatting here:
https://pyformat.info/

But otherwise you want `"has been challenged by {}".format(member)`

**Comment by ZeroX25** [comment]
Wow...I stared at the guide for a good 2 hours too..thanks!!
