### ISSUE TITLE
Can't install it

### ISSUE THREAD

**Issue by Aina261** [Rapptz/discord.py#1075]
Hi, I try to install it but I have ... some error ... 

https://pastebin.com/yih7jDR0

How fix it ?

**Comment by jwshields** [comment]
**Read the error that was given.**
It explicitly tells you what the problem is. It can't decode a certain Unicode character.
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xef in position 25: invalid continuation byte`

Which character is it talking about?
What does the regular representation of that character look like?

https://www.compart.com/en/unicode/U+00EF

**Comment by Aina261** [comment]
Oh, it's juste because my user name have an " ï " ... Thanks, I go to change it and try again.
This character means that it must be pronounced alone in my name.
