### ISSUE TITLE
How can I easily disconnect from a voice channel?

### ISSUE THREAD

**Issue by nickleijenhorst** [Rapptz/discord.py#1084]
I currently have a bot command that joins a voice channel, but I would like the bot to also be able to leave the channel. I spent about 1.5 hours trying to get this to work, by trying to save the VoiceClient object that I get after calling client.join_voice_channel()

I have limited experience in Python, and my idea was to save this to a global variable. However, even after I assign the global variable as voice_state = client.join_voice_channel(), the object stays of type None.

How can I easily keep track of the VoiceClient object after I receive it from client.join_voice_channel()?

**Comment by Rapptz** [comment]
To write to a global variable you need a `global` statement at the top of the function, e.g.

```py
foo = None

def bar():
    global foo
    foo = 10
```

However, it's typically recommended that you don't use global variables and instead use something like class instance variables instead. Since you're having a somewhat difficult time with the concept of globals, I recommend reading up more on Python.

As a reminder, this issue tracker is not meant for basic python questions.
