### ISSUE TITLE
[Suggestion] Add matching audit log in eventsc as an optional parameter

### ISSUE THREAD

**Issue by giorgiocav1** [Rapptz/discord.py#1086]
How about adding the matching audit log action as an optional argument?
say, for example, the[ `on_member_update()`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.on_member_update) event listener.
Currently it takes two arguments, `before` and `after`. But how about adding an optional argument called, say, `audit_log_entry` where the matching audit log entry would be passed?
so we could define `on_member update()` in two ways:
```
@client.event
async def on_member_update(before, after):
    # code...
```
or
```
@client.event
async def on_member_update(before, after, audit_log_entry):
    # code...
```
This would be useful because we could easily spot who actually updated the member's nickname without having to add 3 lines of code to get the last audit log entry.

**Comment by Vexs** [comment]
Discord doesn't supply an audit log for... anything. You have to do an api call to fetch the most recent logs (which, consdering how often member updates happen means that alone will prevent this from being a thing), and even then there might be a lag in updating, or it might have been done by a bot, or done by the user itself and have no audit log- even with all that, there isn't a reliable way to connect an update to an entry in the log.

**Comment by giorgiocav1** [comment]
Member updates are only an example, this could also be handy to know who kicked or banned someone, or if the user left himself (it's pretty much aplicable to any eent which can in some circumstances produce an audit log entry). And yes, there might not be an audit log entry for things like when the user deletes his own entry, but then the argument can just be `None` to show that there is no entry. About reliability, when the user adds the `audit_log_entry` argument they have to expect there to be a little lag while waiting for the entry to show up. This aims to just help a minimum with the speed of development of something such as a moderation bot.

**Comment by Rapptz** [comment]
This isn't gonna happen.

For starters, Discord does not provide audit log data. Which means that in order to do this there'll have to be a sleep portion and then an HTTP request. This is an incredibly expensive operation that flat out doesn't scale for people who have more than one guild in their bot.

Second, having to perform an HTTP request while dispatching is currently impossible given the current architecture of how dispatching works. So this request wouldn't even be possible.

Your best bet is to wait for audit log gateway events to happen. I've queried the developers about this over the span of a year and a half or so and recently they told me it's not going to happen in v7 of the gateway. So this probably isn't going to happen any time soon.
