### ISSUE TITLE
Getting a voice_state_update only when an user joins a voice channel

### ISSUE THREAD

**Issue by DanielVip3** [Rapptz/discord.py#1089]
I tried to make a simple bot that prints in chat when an user joins a voice channel(and only joins a channel, not when an user leaves or is muted etc. etc.), but it seems too difficult for me.  I always read the documentation, but it doesn't seem to say anything about the combination of voice_channel and before.
```
#All this script is in a while True, so that's the reason because the script is indented.
#ID means the ID of my main channel, to test the bot.
    id = discord.Object('412590211625779201')

    @client.event
    async def on_voice_state_update(before, after):
        await client.send_message(id, after.voice)
        if voice_channel.before == None:
            await client.send_message(id, 'I did it : the user joined the channel.')
        else:
            await client.send_message(id, 'I failed : the user didn\'t join the channel')

```

**Comment by Rapptz** [comment]
In v0.16.x, `on_voice_state_update` passes two `Member` objects, one for `before` and one for `after` the event happened, see the [documentation](http://discordpy.readthedocs.io/en/latest/api.html#discord.on_voice_state_update).

As per the documentation (again), you'll notice that there are a bunch of properties such as `voice_channel` on a `Member` object ([see here](http://discordpy.readthedocs.io/en/latest/api.html#discord.Member.voice) and [here](http://discordpy.readthedocs.io/en/latest/api.html#discord.VoiceState.voice_channel)).

The rest seems to be a logic error on your part (and invalid Python due to `NameError`).

To fix your issue you have to check if the member's voice channel before was `None` and if afterwards it isn't. So something like this: 

```py
async def on_voice_update(before, after):
    if before.voice_channel is None and after.voice_channel is not None:
        await client.send_message(..., "hello you joined voice")
```
