### ISSUE TITLE
How do i purge messages?

### ISSUE THREAD

**Issue by Hype153** [Rapptz/discord.py#1112]
I want to know how to purge some messages.
Maybe u could comment the code?

**Comment by mrc0mmand** [comment]
[Async branch](https://github.com/Rapptz/discord.py/blob/async/discord/client.py#L1304)
[Rewrite branch](https://github.com/Rapptz/discord.py/blob/rewrite/discord/channel.py#L218)

I'd say it's pretty well documented.

**Comment by ButterCheezii** [comment]
[Async branch](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.purge_from)
[Rewrite branch](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.TextChannel.purge)

Here are the respective pages of documentation, if that's your thing. It has a handy sidebar you can use instead of looking through the code.
