### ISSUE TITLE
No channel detection

### ISSUE THREAD

**Issue by Sakiut** [Rapptz/discord.py#1133]
I have a very weird problem with one of my bots : it does not detect the channels of my server, even the bot is in the server. I'm using the rewrite version.

[Bot's source code](https://gist.github.com/Sakiut/dd4ff52757ac35bb0651fe6bcfd931fb)

![Bug screen](https://cdn.discordapp.com/attachments/422459253119254528/422460161089732615/unknown.png)

**Comment by davfsa** [comment]
The ids have to be between "" (that should fix it)

**Comment by Vexs** [comment]
@davfsa, ids are integers on the rewrite branch, so no, that will not fix it. 

Is the rest of your bot operating as expected? If not, verify you have actually installed the rewrite branch with `pip show discord.py` using the same python executable that you use to run your bot.

Also, as a note, you can do bot.load_extension("folder.cog1") which will handle the imports and setup for you instead of having to import each one "by hand"

**Comment by Sakiut** [comment]
My bot is functioning at 100% except this problem @Vexs

**Comment by davfsa** [comment]
sorry @Vexs I didnt know it was in rewrite...
