### ISSUE TITLE
Help Command DMs

### ISSUE THREAD

**Issue by ArlixHomework** [Rapptz/discord.py#1140]
So, I don't know how this client.send_message works. Can someone help me? I want this to work because I want the help command go to the Direct Messages.

**Comment by LockdownDoom** [comment]
To send a message to a user through a DM, just say:

user = await client.get_user_info(message.author.id)

await client.send_message(user, ‘message’)

The only thing you have to do,really, is change the destination of the message to a user object instead of a channel. Also, all of this information can be found here, at the documentation: http://discordpy.readthedocs.io/en/latest/api.html

**Comment by Vexs** [comment]
This is not-good advice. `Get_user_info` is a very heavily regulated endpoint with a harsh ratelimit. Furthermore, you *already have* a member object in `message.author`, and discord.Member, as a subclass of discord.User, can be used as a valid destination.

**Comment by LockdownDoom** [comment]
Thank you. I didn’t know that you could use a member object as a destination.
