### ISSUE TITLE
@client.command async def <command name>(message) never works

### ISSUE THREAD

**Issue by TheEBBGaming** [Rapptz/discord.py#1147]
It never responds. No errors. No message. Nothing. I tried every way possible, from resorting my whole code to creating a new bot. 
![screenshot_14](https://user-images.githubusercontent.com/26286929/37541462-154d0e28-2931-11e8-97d6-069fb0dab421.png)
The event version of this code works.

**Comment by TheEBBGaming** [comment]
I tried using `await client.process_commands(message)` but it didn't work, either.

**Comment by Gorialis** [comment]
1. You've opened two issues (#1146)
2. Your code is improperly formatted in this issue (I assume this is a copying error, if it isn't, it is likely the root cause of your main problem)
3. You haven't given us any actual info other than 'doesn't work'. We cannot help you like this.

**Comment by TheEBBGaming** [comment]
Sorry, sir, I edited it.

**Comment by Gorialis** [comment]
Running from the top:
- You're using `client` for the command decorator. While this doesn't necessarily mean you've done something wrong, it implies you are using a `discord.Client` directly, rather than a `commands.Bot`.
  - `discord.Client` on its own does not have the commands extension. Command functionality only exists natively in `commands.Bot` (which is itself a subclass of `discord.Client`).
  - In the event you are using `commands.Bot` somewhere, you may accidentally be using both `Client` and `Bot` when you really only want `Bot` (since it is a subclass of `Client`). If you define an instance for both, remove the `Client` and replace your decorators, etc to use `bot` instead.
- You accept a `message` object, but your decorator says you want a `Context` instead (and in absence of the decorator kwarg, you would not receive an argument at all). You should change this argument and use `ctx.message` to access message attributes.
- You shouldn't be using `process_commands` in a command itself. If your command was actually working, this would cause recursive behavior, sticking your bot into an infinite loop of executing this command.
- You set `message.author` as a field value, but it wants a string. You should do `str(message.author)` or `message.author.mention`, etc to get the desired string for this value.
- You never actually send your embed in this command. You create it, but then nothing else is done. Provided it's supposed to go into the source channel, you can send it by using `await bot.say(embed=em6)`.

**Comment by TheEBBGaming** [comment]
I did everything you said, but nothing still happens.

**Comment by Gorialis** [comment]
Can you post your updated code? (and preferably, as much of it as possible, to make it easier to see if any problems linger outside of your command)

**Comment by TheEBBGaming** [comment]
`
@client.command()
async def useri(message):
    usr_roles = ""
    for role in message.author.roles:
        usr_roles = usr_roles + role.name + ", "
    em6=discord.Embed(title="Info for {}".format(message.author.name), color=0xFF369B)
    em6.add_field(name="Name:", value=message.author)
    em6.set_thumbnail(url = message.author.avatar_url)
    em6.add_field(name="ID:", value=message.author.id, inline=True)
    em6.add_field(name="Nickname:", value=message.author.nick, inline=True)
    em6.add_field(name="Roles:", value=usr_roles, inline=True)
    await bot.send_message(message.channel, embed=em6)
    print ("LAST ONE")
`

**Comment by TheEBBGaming** [comment]
Also, message.author is a string, right? I use message.author all the time and it prints TheEBBGaming#4633 (me)

**Comment by TheEBBGaming** [comment]
![screenshot_15](https://user-images.githubusercontent.com/26286929/37542500-c66998c2-2934-11e8-9766-1567bdf96a37.png)

**Comment by Gorialis** [comment]
`message.author` is not a string. It is a `discord.Member` object. It gets printed as your tag because `print` automatically wraps the statement in `str(..)`.

Reiterating these as these are still present in your code:
- You're using `client` for the command decorator, but you're also using `bot` in your code.
  - You are probably accidentally be using both `Client` and `Bot` when you really only want `Bot` (since it is a subclass of `Client`). If you define an instance for both, remove the `Client` and replace your decorators, etc to use `bot` instead.
- You accept a `message` object, but your decorator says you do not want anything passed. You should reinstate the decorator kwarg and use `ctx.message` to access message attributes.
- You should do `str(message.author)`, `message.author.name` or `message.author.mention` etc to get the string for your `Name:` embed value.

Additionally, judging by the whitespace around your code, I have a suspicion that this may be the only code present in your bot. Your bot cannot function with command code alone; you must instantiate a `Bot` instance and pass it a token to log into Discord with. I would recommend reading the [examples](https://github.com/Rapptz/discord.py/tree/async/examples).

**Comment by TheEBBGaming** [comment]
No, I have everything. All the imports, everything. **All my events work, just not my commands.** Also, I did change everything that said "client" to bot, right?
I changed everything that said message.author to str(message.author)
Now, gonna try it.

**Comment by TheEBBGaming** [comment]
Still does not work. :/

**Comment by TheEBBGaming** [comment]
![screenshot_16](https://user-images.githubusercontent.com/26286929/37542955-5a8e1dd8-2936-11e8-9063-0e7d74cbaf5c.png)

**Comment by Gorialis** [comment]
Second (and hopefully final) reiteration:
- You're using `client` for the command decorator, but you're also using `bot` in your code.
- You accept a `message` object, but your decorator says you do not want anything passed. You should reinstate the decorator kwarg and use `ctx.message` to access message attributes.

I would recommend checking out the [basic_bot example, particularly the command that deals with context](https://github.com/Rapptz/discord.py/blob/async/examples/basic_bot.py#L52).

If you can't get this command to work with the amended decorator and function signature, **I will need your code in its entirety to get any further with this.**

**Comment by TheEBBGaming** [comment]
I'm not using ctx though

**Comment by TheEBBGaming** [comment]
Right?

**Comment by Gorialis** [comment]
You are using `message` in your command. In order to get `message` for use in a command, [you have to pass context, as otherwise you have no other reference point to access it(http://discordpy.readthedocs.io/en/latest/faq.html#how-do-i-get-the-original-message).

Your decorator is also still wrong (`@client.event`, `bot.send_message`), and the fact the decorator is working at all suggests that you still have both a Bot and Client instance, when you [only need a Bot instance](https://github.com/Rapptz/discord.py/blob/async/examples/basic_bot.py#L9).

**Comment by TheEBBGaming** [comment]
@bot.command() returns a traceback
"Name 'bot' is not defined"

**Comment by TheEBBGaming** [comment]
I have `client = commands.Bot(command_prefix = "P")` at the top, btw

**Comment by GiovanniMCMXCIX** [comment]
you are defining `client` not `bot`

**Comment by TheEBBGaming** [comment]
When I do @Bot.command it also returns a traceback:
`command() missing 1 required positional argument: 'self'`

**Comment by Gorialis** [comment]
You're assigning your `Bot` to a variable called `client`, implying that it's a `Client` and not a `Bot`. You should change this definition to point to `bot` instead (`bot = ...`) and keep this consistent within your script.

Don't use `Bot.command`. This attempts to use this function direct from the class, you don't want this.

**Comment by TheEBBGaming** [comment]
I have "client" everywhere else, and yet everything works.
My final question, can I use ctx in events?

**Comment by Gorialis** [comment]
The reason `client` works everywhere else is because you named your `Bot` instance `client`.

`Context` objects are not usable in events, they're specific to commands only.

**Comment by TheEBBGaming** [comment]
So I should define commands.Bot as bot and not client is what you are saying?

**Comment by TheEBBGaming** [comment]
...and change everywhere that says "client" in to "bot"?

**Comment by Gorialis** [comment]
You're not required to, you could change everything back to `client`, but by doing so, you confuse the people reading your code into thinking you have a standard `discord.Client` instead of a `commands.Bot`, and you will receive advice of this type time and time again until you change it. Personally, I would go with changing it.

**Comment by TheEBBGaming** [comment]
Hmm. Okay. I'll try it out. Thanks a lot!
