### ISSUE TITLE
How to make something like this?

### ISSUE THREAD

**Issue by LAMGE2** [Rapptz/discord.py#1184]
I wanna make something like this:

In #announcements channel, once a staff sent a message, bot will delete it and will write the message itself:

Staff: Please dont swear.

Bot: *Deletes staff message* Please dont swear.

**Comment by scragly** [comment]
Typically the issue tickets on Github would be used for issues the library has, such as bugs, possible enhancements or missing feature coverage. 

For things like this, you'd be better of visiting the [documentation](http://discordpy.rtfd.org/en/latest) to better understand how the lib works and how you can utilise it, and to visit the [support server on discord.](https://discord.gg/r3sSKJJ)

If you're having trouble understanding the docs, you might be new to the Python programming language. In that case, we recommend going through one of the following:

- [The Official Tutorial](https://docs.python.org/3.5/tutorial/)
- [Automate The Boring Stuff (for complete beginners)](https://automatetheboringstuff.com/)
- [Learn X in Y Minutes (if you know programming already)](https://learnxinyminutes.com/docs/python3/)

And maybe doing some exercises over at [CodeAbbey](http://www.codeabbey.com/) to ensure you're familiar with the concepts and syntax of python.

After getting familiar with this, you should be able to find understanding the docs a lot easier and the concepts more familiar.

As general pointers regarding the query:

If you're intending this to be a private bot for a single guild, you can check the channel ID matches your announcements channel's ID, and then check if the member has the Staff role or similar. 

If your bot has many other uses, or is in not intending to be a private one, it's recommended to make this a command, which uses a prefix and a command name to notify the bot you want a certain action done. If you intend to use commands, it's generally recommended to use the commands extension, which simplifies a lot of the command registration, argument processing and prefix management.

After making sure you're familiar with both python and the docs, and if you're still having trouble, pop into the support server where general help enquiries are welcome and encouraged, rather than here on Github.

**Comment by TheTrain2000** [comment]
Without giving you the exact answer, let me try and nudge you in the right direction:

You can use the [on_message](http://discordpy.readthedocs.io/en/latest/api.html#discord.on_message) event to detect (and run code) whenever a message is sent that the bot can see.
Like so:
```py
async def on_message(message):
    # `message` is the new discord.Message object that the bot can see.
```
[discord.Message](http://discordpy.readthedocs.io/en/latest/api.html#discord.Message)
(`message.content` and `message.channel` may be particularly useful to you.

Another thing you may need to look into is seeing if a word/list of words is inside of a string.
Here are some sufficient StackOverflow questions on the topic:
[Word in a string](https://stackoverflow.com/questions/5473014/test-a-string-for-a-substring)
[List of words in a string](https://stackoverflow.com/questions/4843158/check-if-a-python-list-item-contains-a-string-inside-another-string)

The final hint I will give you is using [send_message](http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.send_message) with the destination set to `message.channel`.

For further help, feel free to add another comment or even hop on over to the [official discord.py support server](https://discord.gg/r3sSKJJ).
