### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by Drakonix000** [Rapptz/discord.py#1187]
I'm making a bot using discord.py for kicking players.

    from discord.ext.commands import Bot
    from discord.ext import commands
    import discord

    bot_prefix = "`"
    token = "NDMxNDc1OTU1NjYwNDg4NzA0.DafS4A.fIXEkLtWfZkmLjtduBPhq51hN5E"

    client = Bot(command_prefix = bot_prefix)

    @client.command(name='kick',
                    brief="Kick a player",
                    description="Kick",
                    pass_context = True)
    async def kick(context):
        kick(context.message.mentions[0].id)

    client.run(token)

But when someone uses the kick command it doesn't work and gets this error.

    discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: 'Command' object is not callable

**Comment by Harmon758** [comment]
First off, you're going to want to regenerate your token now.

> ```py
> async def kick(context):
>     kick(context.message.mentions[0].id)
> ```
In this kick command, you're trying to recursively call the kick command.
That's why it's raising an error telling you that Command objects aren't callable.
What you're probably looking for is https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.kick.
However, note that Client.kick accepts a Member object as a parameter rather than an ID.

This isn't an issue with discord.py, and for future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.

**Comment by JennyDiscord** [comment]
Instead of token = "token"
do bot.run("NDMxNDc1OTU1NjYwNDg4NzA0.DafS4A.fIXEkLtWfZkmLjtduBPhq51hN5E")
