### ISSUE TITLE
discord.Server.member_count, .created_at etc don't work for me

### ISSUE THREAD

**Issue by tozzzer** [Rapptz/discord.py#1197]
`@bot.command()
    async def createdat():
          server = discord.Server
          time = server.created_at
          await bot.say(time)`

The above code returns no errors but only says in discord: '<property object at> ' followed by a string of numbers and letters.
Can someone explain why it isn't returning a date/time?
(i also put in member_count as that also does the exact same thing)

**Comment by Gorialis** [comment]
Don't try to access properties of the dataclasses themselves - this isn't how OOP works.
Consider checking out **[How do I get the original message?](http://discordpy.readthedocs.io/en/latest/faq.html#how-do-i-get-the-original-message)** and the [examples](https://github.com/Rapptz/discord.py/tree/async/examples) on how to do this correctly.

**Comment by tozzzer** [comment]
@Gorialis thanks for the response. But out of interest, how should I have written my code to do this?

**Comment by OneEyedKnight** [comment]
https://github.com/Rapptz/discord.py/blob/async/examples/basic_bot.py#L46

**Comment by tozzzer** [comment]
@OneEyedKnight the code you linked me doesn't work for me either. When I use it it just says: 'raise MissingRequiredArgument('{0.name} is a required argument that is missing.'.format(param))
discord.ext.commands.errors.MissingRequiredArgument: member is a required argument that is missing.'

**Comment by Tarek1337** [comment]
@tozzzer There shouldn't be a space between member and the colon. 

```py
@bot.command()
async def joined(member: discord.Member):
    """Says when a member joined."""
    await bot.say('{0.name} joined in {0.joined_at}'.format(member))```

Should be like that.

**Comment by tozzzer** [comment]
@Tarek1337 i tried that and it still came up with the same error: 'raise MissingRequiredArgument('{0.name} is a required argument that is missing.'.format(param))
discord.ext.commands.errors.MissingRequiredArgument: member is a required argument that is missing.'

**Comment by Gorialis** [comment]
Please don't copy and paste code around from the example sources. They serve as an example to make you understand how to structure your own code, not as a direct implementation resource.

The command linked does not serve the purpose you were originally trying to in your own code. Your original issue is that you assigning the `discord.Server` dataclass to your `server` variable when you actually want an instance.

Instances relating to the current context can be found from the `Context` instance that is optionally passed to commands. An example of a command passing context is shown in the example [here.](https://github.com/Rapptz/discord.py/blob/async/examples/basic_bot.py#L52)

From the **[How do I get the original message?](http://discordpy.readthedocs.io/en/latest/faq.html#how-do-i-get-the-original-message)** FAQ entry, we know that when we pass context, we can use `ctx.message` to get the original message.
Since this message is tied to the server, it has the [Message.server](https://discordpy.readthedocs.org/en/latest/api.html#discord.Message.server) attribute, so the Server in this context can be found through `ctx.message.server`.

Connecting these pieces together, the solution to your problem is to:
- Pass context using the keyword argument in the decorator (see the example)
- Use `ctx.message.server` to get the Server instance, rather than attempting to access the dataclass.
