### ISSUE TITLE
What is this python magic that I see?

### ISSUE THREAD

**Issue by kevinkjt2000** [Rapptz/discord.py#1198]
https://github.com/Rapptz/discord.py/blob/1863a1c6636f53592519320a173ec9573c090c0b/discord/ext/commands/core.py#L682-L693

Can the above be simplified by just relying on `**attrs`?  Anything `**attrs` should be passed to the `cls` constructor.  It would be nice to get rid of this magical code.  I stumbled across it today, because I was trying to wrap a decorator around the `command` decorator in order to support decorating `class` methods.  All I want to do is pass `self` :man_shrugging:, but then I found out that I cannot pass `checks` in `**attrs` because it would be specified twice.

`checks` could still be reversed by updating it in `**attrs`:
```python
checks = attrs.get('checks', [])
checks.reverse()
attrs['checks'] = checks
```

Or is this magic necessary because of global checks?

My workaround is to overwrite the magic variable, instead of passing it in `**attrs`:
```python
wrapped.__commands_checks__ = checks
```

**Comment by Rapptz** [comment]
You clearly don't understand the original code if you think a kwarg is going to fix this.

The `__commands_check__` is because the *decorator order* does not matter so I take advantage of that situation by storing it in a temporary variable.

**Comment by kevinkjt2000** [comment]
Thanks for the really quick reply!

> The concept of cogs already exists so I don't know what you're struggling with.

Which I did want to use at first, but cogs seems to be lacking some documentation (which the documentation points out).  Since you recommend it, I suppose that I will give cogs a try anyway.

> because the _decorator order_ does not matter

Oh, I had not realized decorator stacking was going on here.  The only other decorators I came across in the documentation seem to be for permissions which I thought would fit nicely into the checks parameter of the default `cls`, so I tried to give checks as a keyword argument.

However, any of the keyword parameters given on https://github.com/Rapptz/discord.py/blob/1863a1c6636f53592519320a173ec9573c090c0b/discord/ext/commands/core.py#L705, such as `checks`, would not be supported in `**attrs` for any `cls`.

**Comment by Rapptz** [comment]
Those explicit keyword argument names are not going to change since the way they are intended to be used and supported is through the interfaces provided such as [`commands.check`](https://discordpy.readthedocs.io/en/rewrite/ext/commands/api.html#discord.ext.commands.check) or [`commands.cooldown`](https://discordpy.readthedocs.io/en/rewrite/ext/commands/api.html#discord.ext.commands.cooldown) interfaces.

Providing a subclass should only be through [`commands.Command`](https://rapptz.github.io/discord.py/docs/ext/commands/api.html#discord.ext.commands.Command) while calling `super().__init__` like usual.

So the intended way to do some subclassing should just be something similar to this:

```py
class MyCommand(commands.Command):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.custom_thing = kwargs.pop('custom_thing', None)

@commands.command(cls=MyCommand)
@commands.check(lambda ctx: True)
async def foo(ctx, *, arg: str):
    pass
```

(this assumes v1.0 of the lib).

Cogs are relatively simple (they're just classes). I suggest joining the [official discord.py server](https://discord.gg/r3sSKJJ) for more help on the topic until more proper documentation is released.
