### ISSUE TITLE
Context not passed

### ISSUE THREAD

**Issue by N-kay** [Rapptz/discord.py#1205]
I'm running Red-DiscordBot and writing my own cog, but I figure this might be more appropriate here.

I'm nesting some command groups, and at the `settings` level, ctx is no longer the context object as assumed, but rather a string of the selected subcommand.

```
@commands.group(name="war", pass_context=True)
async def war(self, ctx):
    print(type(ctx))
...
@war.group(name="settings", pass_context=True)
async def settings(self, ctx):
    print(type(ctx))
...
@settings.group(name="channels", pass_context=True)
async def channels(self, ctx):
...
@channels.group(name="requests", pass_context=True)
async def requests(self, ctx):
...
```

```
!war
> <class 'discord.ext.commands.context.Context'> 
!war settings
> 
!war settings channels
> <class 'str'>
```

Context works correctly in other groups below war.

**Comment by Harmon758** [comment]
I can't reproduce this with your example.
`!war settings` and `!war settings channels` both print `<class 'discord.ext.commands.context.Context'>` twice as they should.

**Comment by Harmon758** [comment]
I'm not familiar with Red, but that seems unlikely.
Without the full code, it's difficult to diagnose this.

**Comment by jcinqueg** [comment]
Something similar happened in my code using discord.py (1.3.2). It wasn't in Red but in my own bot. The context argument was either interpreted as a string, or not passed at all. The issue was caused by multiple functions having the same name, and was remedied by changed the python function name, but renaming the command in the decorator.
