### ISSUE TITLE
bot.say() don't work in a command

### ISSUE THREAD

**Issue by LavaPower** [Rapptz/discord.py#1211]
Hey !

I use the extension for commands. I make few cogs and some works. But when i make a group of command, the last bot.say() of one command don't work.

Example, i make this code :
```@github.command()
    async def repo(self, user = "None", name = "None"):
        if name == "None" or user == "None":
            await self.bot.say("Usage : !github repo <user> <repo>")
        else:
            url = "https://api.github.com/repos/"+user+"/"+name
            r = requests.get(url)
            infos = r.json()
            try:
                if infos["message"] == "Not Found":
                    await self.bot.say("Utilisateur ou repo inconnu.")
                else:
                    0/0
            except:
                name, owner, created, updated, language, forks, subs, url = infos["name"], infos["owner"]["login"], infos["created_at"][:10], infos["updated_at"][:10], infos["language"], infos["forks_count"], infos["subscribers_count"], infos["html_url"]
                repo = discord.Embed(title=name+" - Github", description="Informations de "+name, colour = 0x2ecc71)
                repo.set_footer(text="Dislo - Github System",icon_url=infos["avatar_url"])
                repo.add_field(name = "Nom", value = name, inline = False)
                repo.add_field(name = "Créateur", value = owner, inline = False)
                repo.add_field(name = "Création", value = created, inline = False)
                repo.add_field(name = "Update", value = updated, inline = False)
                repo.add_field(name = "Langage", value = language, inline = False)
                repo.add_field(name = "Forks", value = forks, inline = False)
                repo.add_field(name = "Stars", value = subs, inline = False)
                repo.add_field(name = "Lien", value = url, inline = False)
                await self.bot.say(embed=repo)
```

With a group of command named "github".
But i have this : https://i.imgur.com/4YJRWwi.png
We see command "!github repo" works but if i give all of the parameters, anything happens. No error

**Comment by SourSpoon** [comment]
This is some code that is difficult to understand, and I fear you may not of given us all the information.

There are some things that should be done differently:

- Requests is a blocking http library, use an async one instead. D.py uses aiohttp, so you should have that installed already
- The bare except and else statements dont really make sense here, this is totally abusing basic python flow control, Exceptions are meant to handle when things go unexpectedly not when everything is working as intended.
- giving both user and name a default value and then giving them an error like message should be done with an error handler, arguments not provided without defaults will raise an error for you that you can catch in the `on_command_error` event.

Finally this help may be more suited for the d.py server:
https://discord.gg/r3sSKJJ

**Comment by Harmon758** [comment]
First of all, this isn't an issue with discord.py, and as @SourSpoon noted, for future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.

I suspect the primary issue causing what you're describing is that
`repo.set_footer(text="Dislo - Github System",icon_url=infos["avatar_url"])` raises `KeyError: 'avatar_url'` inside your `except`, as `avatar_url` is not a valid key for what https://api.github.com/repos/LavaPower/Zolo returns.

However, there are numerous other issues with your code, in addition to the ones @SourSpoon already pointed out:
- The fact that you didn't see this error in your console means that you're not handling it properly in `on_command_error`
- There is no reason to use "None" instead of None
- Consider using `.format` for strings instead of chaining +'s
- Assigning values to multiple variables on one line, like in the first line of your `except`, makes your code unnecessarily unclear and harder to debug
- Your kwarg spacing is inconsistent

**Comment by LavaPower** [comment]
Okay, thanks you !
