### ISSUE TITLE
adding roles

### ISSUE THREAD

**Issue by Articuno1234** [Rapptz/discord.py#1233]
im not too sure how to add roles to a user ive tried
```
    @commands.command(pass_context=True)
    async def customrole(self, ctx, user: discord.User, *, rolename: discord.Role):
        """"""
        author = ctx.message.author
        await self.bot.create_role(author.server, name=rolename)
        await self.bot.add_roles(user, rolename)
```
and other stuff but it comes up with errors :cry:

**Comment by Rapptz** [comment]
`rolename: discord.Role` converts (or well, tries to) the string passed into a `discord.Role` inside that server. That means a role has to exist with that name.

So trying to `self.bot.create_role` with that role that would be found would be an error because `name` expects a `str` and the role already exists so creating a new one seems silly.

You probably meant to make the user input a string, in which case no converter is necessary. So something like this:

```py
    @commands.command(pass_context=True)
    async def customrole(self, ctx, member: discord.Member, *, role_name):
        """"""
        author = ctx.message.author
        role = await self.bot.create_role(author.server, name=role_name)
        await self.bot.add_roles(member, role)
```

Next time ask your basic questions in the [official server](https://discord.gg/r3sSKJJ) please.
