### ISSUE TITLE
has_any_roles

### ISSUE THREAD

**Issue by Jaedeke** [Rapptz/discord.py#1238]
Hey
Is it possible to make a list/variable and use it in like this
`roles = "Member", "Friends", "Mod", "Admin", "Super_Admin"
@commands.has_any_role(roles)
`
instead off this
`@commands.has_any_role("Member", "Friends", "Mod", "Admin", "Super_Admin")
`

**Comment by mental32** [comment]
just use a [starred expression](https://stackoverflow.com/questions/12555627/python-3-starred-expression-to-unpack-a-list)

**Comment by Jaedeke** [comment]
maybe a noob question but how do i use it

**Comment by LyricLy** [comment]
Do your research.

**Comment by Frizbunny** [comment]
@Jaedeke 
```py
@commands.has_any_role(*roles)
```
 Rather than passing in a list, you're passing in all the items in the list. Think of it like the star is *expanding* the list and making each item its own argument.


Also, if you ever see `*args` in a function, it means it can accept any number of variables.
Have a look at this example :)
```py
names_list = []

def add_names_to_names_list(*args):
    global names_list
    # args is a list, each item is an argument that was passed in!
    for name in args:
        names_list.append(role)

# even though args is a list, we still pass in each item as its own argument. 
# try this with a starred variable!
add_names_to_names_list('Rob', 'Jack', 'Sam', 'Sophie', 'Jezzie', 'Emilina')
print(names_list)
```
Play around with this and it'll help you understand it better. 

(sorry if I messed up, it's like 2:30 am)
