### ISSUE TITLE
My Aiohttp and websockets packages can't be updated because of discord.py

### ISSUE THREAD

**Issue by justingolden21** [Rapptz/discord.py#1250]
There are many python packages that require aiohttp and websockets to be downloaded and up to date, none of which I can use because I can't update them. Trying to do so results in:

```
discord-py 0.16.12 has requirement aiohttp<1.1.0,>=1.0.0, but you'll have aiohttp 3.1.3 which is incompatible.
discord-py 0.16.12 has requirement websockets<4.0,>=3.1, but you'll have websockets 4.0.1 which is incompatible.
```

Eel is one example of something I can't use because of discord.py ([https://github.com/ChrisKnott/Eel](https://github.com/ChrisKnott/Eel))

**Comment by Vexs** [comment]
Websockets is pinned at 3.x because of an [outstanding bug in the websockets lib that causes random disconnects/crashes. ](https://github.com/aaugustin/websockets/issues/350) Beatbutton has a fork with this fixed that you could use.

**Comment by Rapptz** [comment]
1. `aiohttp` is pinned because at the time there were bugs with memory leaks in aiohttp that I didn't want to expose people to.
2. `websockets` is pinned due to a bug in the websockets library.
3. There is nothing inherently wrong with pinning versions of a library to fit one that actually works with the library source, especially with breaking changes e.g. 1.x -> 2.x or other major version changes.

That being said, `Eel` does not require *any* asyncio functionality from what I'm seeing and instead opts to use `gevent` based asynchronous processing so there shouldn't be any type of "mixup" with using discord.py and eel outside of the fact that they use fundamentally different asynchronous components which makes them pretty much impossible to mix anyway.
