### ISSUE TITLE
Getting NoneType on get_channel() call. Any help appreciated!

### ISSUE THREAD

**Issue by freemanmax01** [Rapptz/discord.py#1255]
Title explains it! I'm not sure why this is happening - I'm almost 100% sure I'm being really thick about this an have done something obvious but any ideas on how to fix this would be fantastic!

Code here: https://hastebin.com/ebupeditic.py

**Comment by Gorialis** [comment]
Can you quote the actual error, with a traceback, that you get?

**Comment by freemanmax01** [comment]
@Vexs Just checked - I'm on version 0.16.12. What should I do from there?

**Comment by Vexs** [comment]
Well, you should install rewrite- the only instructions for how to do so are on the [discord.py discord server](https://discord.gg/r3sSKJJ) because the branch is still in development, and it is the only place where breaking changes are announced. Or, if you don't want to use the development branch, [you can refer to the async (main) branch's docs here.](http://discordpy.readthedocs.io/en/latest/api.html)

**Comment by freemanmax01** [comment]
@Vexs So where are those instructions on the server?

**Comment by Vexs** [comment]
They're stored in a bot command- which anyone on the server will quite happily point to. It's deliberately obscured due to the fact that the branch is not for general public consumption, and only for people willing to report bugs, stay up to date, etc.

**Comment by fourjr** [comment]
as vex said in basically every comment, [please join the discord server to ask for help](https://discord.gg/r3sSKJJ)

Migrating docs: http://discordpy.readthedocs.io/en/rewrite/migrating.html
Downgrade: ```
pip uninstall discord.py
pip install discord.py
```

**Comment by freemanmax01** [comment]
@fourjr Thank you! Sorry for asking here. I'll close this issue now I know!
