### ISSUE TITLE
Multiprocessing not playing well with cogs [rewrite]

### ISSUE THREAD

**Issue by AndreyATGB** [Rapptz/discord.py#1294]
I have a more complex multiprocessing based function I want to use but issues with it led me to testing much simpler ones. For example the one from [https://docs.python.org/3/library/multiprocessing.html#the-process-class](url). There are basically two ways it's going to go by using cogs, the first is by defining f outside of the cog class. For example:
```python
import multiprocessing as mp
import discord, asyncio
from discord.ext import commands

def f(name):
    print('hello', name)

class ParallelTest:

    def __init__(self, bot):
        self.bot = bot
    
    @commands.command(name='cogtest', hidden=True)
    @commands.is_owner()
    async def cogtest(self, ctx):
        p = mp.Process(target=f, args=('bob',))
        p.start()
        p.join()

def setup(bot):
    bot.add_cog(ParallelTest(bot))
```
Results in console output:
```
hello bob
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002064B3DB5C0>
```
Another thing to do is place f inside the cog (and change target to self.f so it actually works). This results in:
```
Traceback (most recent call last):
  File "C:\Users\Andrei\Anaconda3\lib\site-packages\discord.py-1.0.0a0-py3.6.egg\discord\ext\commands\core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "D:\Dropbox\Scripts\Discord Bot\cogs\PerlinCog.py", line 19, in cogtest
    p.start()
  File "C:\Users\Andrei\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\Andrei\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Andrei\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Andrei\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Andrei\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function reload at 0x000001F1056BB0D0>: it's not the same object as __main__.reload
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Andrei\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Andrei\Anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000026A3DFFB588>
```
The way to actually get this to work is to paste it in the main bot file. Mine is not using any classes, pretty much copy paste the example from the python.org page except change main to a command. This will work as expected. 
This happens when using a manager or pool as well.
If you're going to try this, remember to place your bot.run in ```if __name__ == '__main__':``` or the process will start another bot (or a lot more if you're starting more than one process). 
Can anyone else replicate the issue?

**Comment by ItWasAllIntended** [comment]
Nice copy paste

**Comment by calebj** [comment]
When you pass an instance method to multiprocessing, it's going to try to pickle that instance and its members, namely `bot`, to send it to the child process. Since many components of a `Client` instance can't be pickled, this fails. Try separating the function and any connected objects into something that *can* be serialized, like in your first example. Defining `f(name)` as either a classmethod or staticmethod should also work, or you can use threading to avoid having to run everything through pickle.

Another thing, you might consider using the [`run_in_executor()`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.AbstractEventLoop.run_in_executor) coroutine with either a [`ThreadPoolExecutor`](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor) for IO-bound tasks or a [`ProcessPoolExecutor`](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ProcessPoolExecutor) for CPU-bound tasks instead. The multiprocessing `join()` function will block your event loop, which is probably not something you want.

P.S. I think the reason you get multiple bot instances when you do this is because `multiprocessing.Process` is a generalization of UNIX's `fork()`, which copies everything in the running interpreter, including the bot, even on Windows.
