### ISSUE TITLE
economy cog json file keeps emptying itself

### ISSUE THREAD

**Issue by RMXdotEXE** [Rapptz/discord.py#1302]
Basically what the title says.

The problem is that
1) I change the bank.json economy data file to reflect the data that is supposed to be present
2) i load the cog
3) loading the cog creates an empty json file
4) data loss

**Comment by Harmon758** [comment]
As the README states, discord.py is an API wrapper for Discord.
It in and of itself is not a bot that contains cogs, as this issue seems specific to.
Rather, it's the framework likely being used by the redistributable bot you're using.
As such, this isn't an issue with discord.py, and you should probably create a new issue in the repository of whichever bot you're using.
