### ISSUE TITLE
Fatal read error on socket transport on bot just running

### ISSUE THREAD

**Issue by Runisco** [Rapptz/discord.py#1317]
Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x74ec10b0>
transport: <_SelectorSocketTransport fd=6 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 723, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
-----------------------------------------
I use multiple ascynio.sleep() commands, but those are inside of uncalled functions, so why these errors are popping up, I have no idea. Is the problem with asyncio itself on a Rpi? or is it discord.py doing something to it after being imported in code

**Comment by Gorialis** [comment]
Reading the error:
- **Fatal read error** means something was being read and for some reason reached a state where it no longer could be.
- **SSLProtocol** means it was an SSL connection, i.e. an encrypted connection to the internet.
- **read=polling** means data was being polled, i.e. it was delivered in chunks that the client waited for. This *could* be a HTTP download of a multipart file, but it's more likely that this was the websocket.
- **TimeoutError** means a time limit was set and surpassed without successfully completing the operation.

From this, we can deduce:
- Your bot was connected to the websocket and serving normally.
- Something happened to interrupt the connection to Discord. (This could be anything from Discord having an outage, your router resetting, a faulty cable, or a changeover at your gateway.)
- This interruption lasted long enough that the connection could not be conventionally resumed after it had passed.
- Your bot, no longer having a valid session, closed out with the above error.

Errors of this nature are fairly common on connections without the stability practices you might find on a [VPS](https://en.wikipedia.org/wiki/Virtual_private_server). They are not handled automatically on the async branch (0.16.x), so many people use service handlers like [`systemd`](https://www.freedesktop.org/wiki/Software/systemd/) or [`supervisord`](http://supervisord.org/index.html) to automatically restart their bot in these cases.

There is an in-development [`rewrite`](https://github.com/Rapptz/discord.py/tree/rewrite) branch that handles situations like this automatically. If you wish, you can learn more about it on the [discord.py help server](https://discord.gg/r3sSKJJ). Note however that switching to this branch is a large commitment, and may not be suitable for bots that perform important tasks or are developed under commission, for example.

Otherwise, there are some [good](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/sect-managing_services_with_systemd-unit_files) [online](https://www.raspberrypi-spy.co.uk/2015/10/how-to-autorun-a-python-script-on-boot-using-systemd/) [tutorials](https://www.digitalocean.com/community/tutorials/how-to-configure-a-linux-service-to-start-automatically-after-a-crash-or-reboot-part-1-practical-examples) on how to use services to keep your bot online.

**Comment by Harmon758** [comment]
Additionally, this is irrelevant to your usage of `asynico.sleep`, although it could be caused by something [blocking](https://discordpy.readthedocs.io/en/latest/faq.html#what-does-blocking-mean).
As @Gorialis detailed, discord.py uses asyncio internally, and the error itself is just telling you that the connection timed out. This could very well be due to a poor connection or performance issues with your Raspberry Pi.

**Comment by Runisco** [comment]
Could it be the voice functionality of the rewrite branch? It's hosted at home, so the instability makes sense.
When i searched through the rewrite documentation, the rewrite branch is the one I'm using btw, a search for timeouterror went into the voice section.

Is there some way of disabling/preventing loading of the voice functions when importing discord to see if this is the error? or do I need to uninstall the rewrite, and reinstall without voice?

**Comment by Harmon758** [comment]
A `TimeoutError` isn't exclusive to voice functionality. Any websocket connection to Discord's API could conceivably timeout. However, if you just don't join any voice channels, then there's no voice connections for there to timeout.

**Comment by Runisco** [comment]
Damn, and yay. Means that the most likely culprit is an unstable wireless connection
