### ISSUE TITLE
Websockets code 1006

### ISSUE THREAD

**Issue by thatguywiththatname** [Rapptz/discord.py#1320]
So I am running a Discord bot on a Digital Ocean Droplet (VM), and am having some problems with the websocket connection.

The bot runs fine, and stays online fine, but every now and again it throws this error:

`
websockets.protocol.fail_connection: Failing the WebSocket connection: 1006
`

You can see a small section of the log [here](https://i.imgur.com/Zz7b1Uc.png) which shows this error is recurring.

It seems that this error should occur from a bad / dodgy internet connection, but I don't think this can be the issue, as Digital Ocean have always maintained that they have very good stability when it comes to things like this ("99.99% Uptime").

You can also see my Droplets network usage [here](https://i.imgur.com/WWBAgWt.png), there are no downspikes during the times in the logs

As far as I can tell this error has no actual effect on my bot, but it is concerning that this occurs this often and I cannot find a way to fix it.

Looking in the [Websockets RFC](https://tools.ietf.org/html/rfc6455#section-7.4.1), 1006 is reserved for abnormal behavior, so does this mean that it could be to do with the Discord API handling things incorrectly (either at their end or the client end)?

Any ideas as to why this is happening / how to stop this error from happening?

**Comment by Harmon758** [comment]
A WebSocket closure code of 1006 doesn't provide much information. As you noted, all it means is that there was an abnormal closure and often no reason is provided.
As you also noted, this can often occur due to Internet connection issues. Barring that, it could be something [blocking](https://discordpy.readthedocs.io/en/latest/faq.html#what-does-blocking-mean) interfering with the WebSocket connection. It could also rarely be an issue on Cloudflare or Discord's end.
Generally, the library handles these WebSocket closures and automatically attempts to reconnect. Also of note, the auto reconnection logic has been improved significantly on the rewrite branch.
