### ISSUE TITLE
Can't find voice client attribute

### ISSUE THREAD

**Issue by LeBogoo** [Rapptz/discord.py#1329]
Hi! I try that the bot join in a voice channel, but i always get this error message: 
> AttributeError: type object 'Client' has no attribute 'voice_clients'

This is the code i try: 
`@bot.event
async def on_ready():
    channel = client.get_channel(438353035442389003)
    discord.Client.voice_clients.join_voice_channel(channel)
`
I don't know how i can fix it.

**Comment by Harmon758** [comment]
You're using the `discord.Client` class instead of an instance of the class like in the previous line.

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.
