### ISSUE TITLE
Changing Avatar upon Command

### ISSUE THREAD

**Issue by paixlukee** [Rapptz/discord.py#1330]
**Hello!**

I have seen some `edit_profile` functions and how they work.

What I want to do is use the `asyncio.sleep` function so my bot can change the avatar every {} minutes. 

I wanted to know, if I could do that, and exactly how to. (possibly with an easier way).

**Thank you,**
Luke

**Comment by Harmon758** [comment]
This is ill-advised as there's a rate limit (I think it's twice every 10 min. now) for avatar changes, which was actually implemented due to automatic avatar change abuse.
But yes, `asyncio.sleep` in a background task is probably the best implementation.

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.
