### ISSUE TITLE
Welcome mensage

### ISSUE THREAD

**Issue by wi6n3l** [Rapptz/discord.py#1360]
I, i need to know how to make na welcome message, i know the on_join, but the channel id, how do i get the id of one of the channels of the server user joined, because my bot is in a lot of servers… so…
every toturials or issues here doesn't work… help me pls

**Comment by Harmon758** [comment]
This is inadvisable, since there are servers without default channels now.
It'd be recommendable to add a server-specific setting where the option for welcome messages is toggleable and where you're able to set the channel they go to.

If you really wanted to do so, you could pick a channel at random. However, this is not a good idea, as your welcome messages could go somewhere unintended, e.g. an announcements channel.
For a list of channels in the guild:
https://discordpy.readthedocs.io/en/latest/api.html#discord.Server.channels
Note, you'd have to filter for text channels.
On the rewrite branch:
https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Guild.text_channels

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.
