### ISSUE TITLE
AttributeError: 'Client' object has no attribute 'send_message'

### ISSUE THREAD

**Issue by Liteb0t** [Rapptz/discord.py#1361]
i pasted the 'reply' bot example into pycharm but this error came up

**Comment by mrc0mmand** [comment]
We need more information from you to find out the root cause:
 * which version of `discord.py` do you use?
 * possibly full traceback of mentioned error

Given the information you gave us the most probable cause is that you use a rewrite version of `discord.py`, where the class hierarchy is a little bit different, see https://github.com/Rapptz/discord.py/blob/rewrite/examples/reply.py

Also, for future questions from the *user* side it is advised to use the official `discord.py` Discord server.
