### ISSUE TITLE
[FR] Implement an easier reaction system

### ISSUE THREAD

**Issue by Diniboy1123** [Rapptz/discord.py#1378]
The rewrite logic is already awesome, and the most logical one that I've ever seen. There is only one thing that was a bit hard for me to understand and use it firstly, and that is the `wait_for`. I think [eris's way](https://github.com/abalabahaha/eris/blob/master/examples/reactionButtons.js#L18-L35) to build these would be much easier if you're building a paginator, or any other reaction based thing.

At that concept, the keys are the actual reactions, and you can attach a function to each reaction that will be called.

I'd definitely keep `wait_for` because of the complicated checks and so on, but it'll be a nice addition to the lib. 👍 

And here it is "looped", so it reacts for any reaction from the __invoker__ user in the given timeout.

Thanks a lot!

**Comment by scragly** [comment]
There's sort of three levels to the code involved when a bot is built with discord.py:
1. Low Level - Raw API requests
2. Mid Level - Mapping the API to appropriate objects, functions and methods via d.py
3. High Level - Your own code on top of the d.py interface

Most implementation details for the higher end stuff is left out of the lib due to a number of reasons, a major one being that the lib is not meant to limit how you implement your own bots higher-end features; how you would prefer to implement one feature for your own bots code could be different to someone else's due to style preference, experience, existing dependencies, performance requirements, rigidity/flexibility and overall user experience.

Asking for something like the above is far too high-level for the lib to care about or get involved in for the most part. It would require a bunch of objects for tracking interactive sessions, building embed paginators, input handling, available choices and their parsing, designed user limitations and other things that I'm sure other will want to control, and it would have to be designed in a way that ensured it won't impact negatively systems that don't have much wiggle room performance-wise, yet somehow be flexible and powerful enough to be modified in almost any way to fulfil the intentions of most users. 

Instead of bloating the lib with unnecessary high-level code that mostly comes down to personal choice of implementation details, you should implement your own preferred setup and work with it. The lib should be separate from that, as it's for all intents, as bare as it should be when it comes to excess features.

Consider even that the commands extension, something used by the majority of regulars in one way or another, is kept separate intentionally from the lib.

**Comment by Vexs** [comment]
Not to mention a basic implementation of this is trivial to implement. 

```py
func_dict={"emoji":some_func}
...
def check(r, u):
    return all(r.emoji in func_dict, user==someone, reaction.message.id=someid) 

reaction, user= await client.wait_for("reaction_add", check = check)

func_dict.get(str(reaction.emoji))()
```

**Comment by Diniboy1123** [comment]
What, no. It is just a dict of reactions and attached callbacks. There are no embeds, paginators etc. You'd need to code that for yourself.
