### ISSUE TITLE
Discord.py Hug Command

### ISSUE THREAD

**Issue by KyleBurnip** [Rapptz/discord.py#1385]
I Tried To Make A Hug Command It's Not Working I Need Help

`@client.command(pass_context=True)
async def hug(ctx, member: discord.Member):
    author = ctx.message.author
    embed = discord.Embed(
        description = "**{1}** was huggged by **{0}**".format(member.mention, author.mention),
        color = 0x57d2cc
    )

    embed.set_image(url = random.choice(["https://cdn61.picsart.com/197337928002202.gif?r1024x1024", "https://media.giphy.com/media/wbrgtEbP1GPNS/giphy.gif", "https://media1.tenor.com/images/506aa95bbb0a71351bcaa753eaa2a45c/tenor.gif?itemid=7552075%22"]))
    await client.say(embed=embed)`

**Comment by Harmon758** [comment]
You need to provide the full traceback when asking for help with a problem in your code.
"It's Not Working" isn't enough information for anyone to figure out what the issue is to help you.

Also, for questions regarding usage of the library, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends. GitHub issues are not the proper place to ask for help.

**Comment by KyleBurnip** [comment]
@Harmon758  indents

**Comment by Harmon758** [comment]
Again, if you want someone to help you, you're going to need to provide them the full traceback for them to understand what the problem is.
I'm assuming by "indents" you mean that it's an indentation issue, in which case the solution would be to fix your indentation.

For further help, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api).

**Comment by KyleBurnip** [comment]
@Harmon758 Shut Up Nigga Fix My Code Or Piss Off

**Comment by Cristy86** [comment]
@KyleBurnip please be nice.

**Comment by KyleBurnip** [comment]
@Cristy86 Okay @Harmon758 Sorry I Just Need It Fixing

**Comment by Cristy86** [comment]
You need to understand python and discord.py to fix it yourself..

**Comment by Cristy86** [comment]
If you have a bug in your code please provide the traceback

**Comment by bitichigo** [comment]
Shut fuck ni******* pls go awa

**Comment by Cristy86** [comment]
bitichigo, please be nice.

**Comment by bitichigo** [comment]
Did you just call me bitch????

**Comment by Cristy86** [comment]
I said please be nice.

**Comment by KyleBurnip** [comment]
Damn this is hott

**Comment by bitichigo** [comment]
Fuck of your cold

**Comment by bitichigo** [comment]
.,,,;…………

**Comment by bitichigo** [comment]
!?!!!!!1++1fuck of

**Comment by bitichigo** [comment]
.

**Comment by bitichigo** [comment]
.

**Comment by bitichigo** [comment]
.

**Comment by volcanicer** [comment]
Well this is funny.
As for KyleBurnip, if you could provide the full traceback it would be very helpful.

**Comment by Shana6** [comment]
ok this is hilarious people think it's a good idea to put in that little effort into their issue question and then throw slurs and swears around because they dont know how to properly respond to asking for stuff like just answer the request and dont swear lmao how hard is that they just wanted ur traceback
