### ISSUE TITLE
I have a TypeError: must be str, not Member error

### ISSUE THREAD

**Issue by louga31** [Rapptz/discord.py#1395]
When I try to execute this code: [Pastebin](https://pastebin.com/CJVhJJ6w)
I get this error: `TypeError: must be str, not Member`.
Can you help me please ?

**Comment by mrc0mmand** [comment]
This depends on the way how you execute the command from Discord.

e.g.:
```
<  ?stats mrc0mmand
```
In this case `type(username) == str`

But for
```
< ?stats @mrc0mmand#1234
```

the `type(username) == discord.Member`

In other words, when using a mention, the username will be an instance of the `Member` class, but the code expects a string.

As I said last time, for this type of questions is better to use the official discord.py server.

**Comment by Harmon758** [comment]
First of all, you've leaked your Wargaming.net application ID. You might want to remove that application and create a new one.

Since your command definition is in a class, it's missing a self argument.
Since you're using the rewrite branch, it's also missing a context argument.
You're also missing a requests import, but you shouldn't be using requests anyway since [it's blocking](https://discordpy.readthedocs.io/en/rewrite/faq.html#what-does-blocking-mean).

As for your error itself, it's unclear where it's coming from or whether it's even in the scope of this code.
You need to provide the full traceback when requesting help diagnosing your issue.

As @mrc0mmand had told you and as the README recommends, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help. GitHub issues are not the proper place to ask for help.

@mrc0mmand The library would convert the mention into a string, e.g. `<@115691005197549570>`, so that shouldn't be the issue.

**Comment by mrc0mmand** [comment]
@Harmon758 Thanks for the correction, that somehow slipped my mind.
