### ISSUE TITLE
Script hanging till console interaction, then raises asyncio timeout

### ISSUE THREAD

**Issue by MattIPv4** [Rapptz/discord.py#1400]
So my bot has recently been randomly dying.
Nothing is logged to console, it just dies.
https://media.discordapp.net/attachments/381965515721146390/465096691503071244/image.png

When it has died and is hanging, pressing enter in the console will then prompt it to raise the error, in this situation an asyncio timeout error, and then crash.

I don't understand why these timeout errors won't raise until I press enter in console, and why they aren't internally handled.

(Sorry for it being a screenshot, the issue occurred whilst I was on mobile)

**Comment by Gorialis** [comment]
My guess for this is you're putting Command Prompt into selection mode by accident. You can tell if you're in selection mode by looking at the title of the window.

Selection mode is a mode for Command Prompt triggered by either using its menu or by clicking in certain conditions. It allows text to be highlighted and copied to the clipboard, during which **all output to the console is frozen**.

This causes `print` (or even just `sys.stdout.write`) to become a blocking call, and in your case freezes the event loop once called, resulting in your bot freezing as well.

You can test this yourself with a short script:
```py
import time

while True:
    time.sleep(2)  # to allow us time to read the numbers
    a = time.perf_counter()
    print('test')  # will freeze in selection mode
    b = time.perf_counter()
    print(f'took {b - a} seconds to print test')
```
Start the script and observe the short print times. Enter selection mode by clicking (or right clicking on the window title and going to Edit -> Mark). Wait about 10 seconds and then exit the mode by pressing Enter as many times as needed. You'll notice the time is much higher, because the script was frozen on the print statement.

The solution to this problem is to try to avoid entering selection mode. It's marked in the window title for both Command Prompt and PowerShell, and can be exited by pressing Enter as mentioned.

On Linux, such behavior doesn't exist (to the best of my knowledge), so this is a Windows exclusive issue.

**Comment by MattIPv4** [comment]
Sometimes I really hate windows. That totally could be whats causing it. Hadn't even considered selection mode as an issue here. I will add some stuff at launch to display quickedit and see if that helps.

**Comment by MattIPv4** [comment]
Still getting the random timeouts with quickedit disabled. Any ideas?

**Comment by Harmon758** [comment]
Do you have anything in your code that blocks and waits for input from the console?
