### ISSUE TITLE
Voice state messed up when trying to join private channels

### ISSUE THREAD

**Issue by JellyWX** [Rapptz/discord.py#1411]
This could be an issue in my own code but I think it's to do with the cached voice state of the bot.

To reproduce:

- Make a private VC that the bot hasn't got permissions to join
- Attempt to connect the bot to the private VC
- Change to a public VC with full permissions
- Attempt to connect the bot to the public VC

Expected result:
- Bot connects to the VC with full permissions but raises an error connecting to the private VC

Actual result:
- Raises 'Already in a voice channel' and refuses to connect to the full permission VC. No error upon trying to join the private VC (but it doesn't connect to it)

Info:
- Using latest d.py rewrite branch
- Using Python 3.6.6
- Using FFMPEG on Linux

Follow Up Stuff:
- Can confirm there are no issues after placing a permission checker before the connector:
```
if not <voice channel>.permissions_for(guild.me).connect: return
```

My code is at https://github.com/jellywx/soundfx-bot if required. Issues arise in the `play` commands

**Comment by Harmon758** [comment]
I can reproduce this for the period of time when the bot is still waiting to connect from the first attempt.
However, after the specified `timeout` passes and `TimeoutError` is raised, the bot proceeds to connect with no issues on a second attempt.
Are you waiting long enough for the `TimeoutError` to occur? The [default is 60s](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.VoiceChannel.connect).
This doesn't seem like unexpected behavior, and shouldn't be an issue since you can lower the `timeout` as you see fit.

**Comment by JellyWX** [comment]
Okay, I didn't wait long enough or realize there was such a 'timeout'. My proposition, then, is that either a different error be raised (e.g Already connect*ing* to channel)or that permissions get checked prior to connection attempts and raises an appropriate error. Surely the connection shouldn't have to timeout to indicate the bot can't connect?
