### ISSUE TITLE
Sending a message when someone joins the server

### ISSUE THREAD

**Issue by kylemacdoodle** [Rapptz/discord.py#1440]
I'm having trouble making my bot send a message when somebody joins a server.
So far, I have:

@client.event
async def discord_on_member_join():
    await bot.send_message(server, "welcome to the bottom of the barrel.")

note that i'm not the best at coding.

**Comment by scragly** [comment]
You shouldn't set server as a destination, as there's not a specific channel for it to go to. Once upon a time, there were default channels, which is why you may have heard this type of thing being possible in the past, but they are no longer around. Old default channels can be deleted, and newer servers simply don't have one. 

Instead you should have the bot have some type of command that saves a chosen channel as their 'welcome' channel. You can store the channel ID then under their guild ID and retrieve their welcome channel ID based on the context for member join events.

**Comment by kylemacdoodle** [comment]
So the channel ID is the channel's name, right?
What's the guild ID?

**Comment by scragly** [comment]
No the channel ID is the channel ID. Every discord channel, server, user, message, custom emoji have ID's, also known as snowflakes. They are a 64 bit integer that is unique to every object. They are not their name, which is hardly unique at all.

You can find ID's through escaping mentions, or enabling dev mode in your discord client and right clicking the relevant item and copying it's ID via context menu.

**Comment by kylemacdoodle** [comment]
Alright, thank you!

**Comment by scragly** [comment]
No problem. In future though, rather than continue asking basic discord and bot questions here in Github issues which are meant for opening actual issues with the code of the lib, not your issues with using or understanding the lib, you should head over to [the discord.py support server](https://discord.gg/discord-api). More people are available to answer the questions, quicker, and without annoying everyone with emails who might be subbed to github lib issues.

Also, please close the issue.

**Comment by kylemacdoodle** [comment]
Okay, thanks!
