### ISSUE TITLE
Bot never change presence/status

### ISSUE THREAD

**Issue by Foxlider** [Rapptz/discord.py#1443]
While using the rewrite version, I am trying to put the song's name in the status of the bot. 
As shown in the documentation, I am using this : 

```
game=discord.Game(name=player.title)
await self.bot.change_presence(status=discord.Status.online, activity=game)
```
The bot still have his old status

**Comment by scragly** [comment]
Hey, did you happen to update your rewrite recently? If not, you should since rewrite has had multiple breaking changes over the past couple of months, which includes the change to activity for change_presence. The docs will reflect the current code, not any old code, which might be your current issue.

**Comment by Foxlider** [comment]
Yes I did a few days ago.

**Comment by Foxlider** [comment]
I found a way of doing it. It's a bit brutal but hey... 
```
game=discord.Game(name=player.title)
self.bot.activity = game
```
