### ISSUE TITLE
Issue with getting object with Id

### ISSUE THREAD

**Issue by turalnovruzov** [Rapptz/discord.py#1463]
Hi. I am trying to save channel and user Ids in a file and then when needed send a message to them all. When I am trying to send the messages I don't know if Id belongs to user or channel. How can I know if an id belongs to a user or a channel

**Comment by scragly** [comment]
The IDs of discord objects are all snowflakes with the same format, nothing distinguishable from just their IDs that determines their object type. The only info they have in it by themselves is some unique identifier stuff to ensure it's one-of-a-kind, and creation time info. 

In order for you to determine what your data is in reference to, you need to actually think for a couple of extra seconds about how you're structuring your data in order to easily determine the context of what those IDs are for. 

This is definitely not a discord.py issue related to this library, and isn't even something limited to the python language in general; this is something that is known through any cases of storing and retrieving any data. 

This type of question really doesn't belong as an Issue on this repository, so I'd recommend closing it and popping over to maybe a programmer/python support server on discord, or the [discord.py support server](https://discord.gg/r3sSKJJ) for any discord.py usage related questions.

**Comment by turalnovruzov** [comment]
Thank you very much for the answer. Just another question. Can a channel Id be the same as a user's Id?
In other words, do all the objects have unique Ids or users have their unique Ids and channels have their own unique Id.

More clarification, think about 2 SQL tables: Channels and User. a channel can have the same id as a user. I have an idea that if they **all** have unique Ids, I will first cycle through bot's channel. If the Id does not match any of the channels' then it is a user.

**Comment by scragly** [comment]
All snowflakes are unique, hence why they're called snowflakes and hence why the following was stated in my previous comment:
> some unique identifier stuff to ensure it's one-of-a-kind
All discord objects generate from the same snowflake system, there's not one special one for channels, another special one for users, etc. That would just be unnecessary complexity when the snowflakes by design are already ensured they're unique.

Your idea of doing a check for one object type followed by another, and just lazily adding all IDs in one table is a terrible data storage decision. All data should be kept distinct from each other in order to efficiently retrieve the information you require with the least amount of resources possible.

I won't be answering any followup questions on this Issue in regards to this, as you should have just followed the previous given advice which was to go to a relevant support server that's more suitable for basic general programming questions like this, and to stop annoying the people who subscribe to github updates via email for this repo with irrelevant banter.

**Comment by turalnovruzov** [comment]
Thank you very much.
