### ISSUE TITLE
Error with avatars

### ISSUE THREAD

**Issue by Inspectiver** [Rapptz/discord.py#1472]
So I'm trying to make a simple bit of code that will send a truth or dare question in the form of an embed when the command !tod is typed. I got the command to work however I want the avatar of the user to show up as the thumbnail, and for some reason it isn't working.

`@bot.command(pass_context=True)
async def tod(ctx, user: discord.Member):
    random_lines = random.choice(open("tod.txt").readlines())
    avatar = (user.avatar_url)    
    author = ctx.message.author
    embed.set_thumbnail(url=avatar)
    embed = discord.Embed(title="Truth or Dare", description=" ", color=0x309bf3)
    embed.add_field(name="Question", value=random_lines, inline=True)
    embed.set_author(name=author, url="https://skyderp.com", icon_url=avatar)
    await bot.say(embed=embed)
    await bot.say(avatar)`
Error:
`Ignoring exception in command tod
Traceback (most recent call last):
  File "C:\Users\Tims Laptop\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "C:\Users\Tims Laptop\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 367, in invoke
    yield from self.prepare(ctx)
  File "C:\Users\Tims Laptop\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 345, in prepare
    yield from self._parse_arguments(ctx)
  File "C:\Users\Tims Laptop\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 304, in _parse_arguments
    transformed = yield from self.transform(ctx, param)
  File "C:\Users\Tims Laptop\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 212, in transform
    raise MissingRequiredArgument('{0.name} is a required argument that is missing.'.format(param))
discord.ext.commands.errors.MissingRequiredArgument: user is a required argument that is missing.`

I did however get it to work fine with a user info command
`@bot.command(pass_context=True)
async def info(ctx, user: discord.Member):
    avatar = (user.avatar_url)
    embed = discord.Embed(title="Info", description=" ", color=0x309bf3)
    embed.set_thumbnail(url=avatar)
    embed.add_field(name="Name", value="The users name is: {}".format(user.name), inline=True)
    embed.add_field(name="ID", value="The users ID is: {}".format(user.id), inline=True)
    embed.add_field(name="Status", value="The users status is: {}".format(user.status), inline=False)
    embed.add_field(name="Highest Role", value="The users highest role is: {}".format(user.top_role), inline=True)
    embed.add_field(name="Joined", value="The user joined at: {}".format(user.joined_at), inline=True)
    await bot.say(embed=embed)`

**Comment by Harmon758** [comment]
`MissingRequiredArgument` is raised when a command is invoked without a required argument:
https://github.com/Rapptz/discord.py/blob/1863a1c6636f53592519320a173ec9573c090c0b/discord/ext/commands/errors.py#L68-L71  This means that the user of the bot triggers the command and doesn't give required input.
In this case, you're invoking the command with `!tod`, but not passing the required `user` argument, with something like `!tod Harmon758#0004`.
To handle this, you can either set a default value for the user kwarg or you can catch `MissingRequiredArgument` in `on_command_error`:
https://github.com/Rapptz/discord.py/blob/1863a1c6636f53592519320a173ec9573c090c0b/discord/ext/commands/bot.py#L286-L295  Or as that documentation states, in a specific error handler for that command:
https://github.com/Rapptz/discord.py/blob/1863a1c6636f53592519320a173ec9573c090c0b/discord/ext/commands/core.py#L376-L381
Since you seem to only want the user who triggered the command, then instead of requiring an input for the user, you should just use `ctx.message.author`:
https://github.com/Rapptz/discord.py/blob/1863a1c6636f53592519320a173ec9573c090c0b/discord/ext/commands/context.py#L37-L38 https://github.com/Rapptz/discord.py/blob/1863a1c6636f53592519320a173ec9573c090c0b/discord/message.py#L51-L53
For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.
Also, you should use [code blocks](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code) instead of inline code formatting when you have newlines in your code.
