### ISSUE TITLE
discord.ext.commands.Bot.add_cog failing to pass message as parameter

### ISSUE THREAD

**Issue by jeremytiki** [Rapptz/discord.py#1479]
Assuming you have a setup like so:
```

from discord.ext.commands import Bot


class PluginClass:
    async def on_message(self, message):
        await self.send_message("Hello")

class mBot(Bot):
     def __init__(self, *args, **kwargs):
        super().__init__(self, *args, **kwargs)
        self.add_cog(PluginClass)
```

After running the setup I get the following:
```
Ignoring exception in message
Traceback (most recent call last):
  File "/home/jeremytiki/.virtualenvs/boterle-FXkqn9oM/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 252, in _run_extra                   
    yield from coro(*args, **kwargs)
```
[Line 252](https://github.com/Rapptz/discord.py/blob/async/discord/ext/commands/bot.py#L252).

**Comment by Harmon758** [comment]
This isn't the full traceback, and very little can be gathered from this part of it.
That line is just calling your coroutine when it dispatches the event.

As far as I can tell from this incomplete snippet, you're trying to use [`Client.send_message`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.send_message), but instead of invoking it using an instance of `Bot`/`mBot`, you're invoking it using your `PluginClass` instance.
And I assume `PluginClass.send_message` doesn't exist.
I'm not even sure you're adding the cog properly, since you're passing the `PluginClass` class itself instead of an instance of it.

In the future, please provide the full traceback and a complete and correct self-contained example, so that it's clear what the issue is, and for further help, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by jeremytiki** [comment]
Actually that is the entire Traceback, though thank you for your help. Sorry for wasting your time, but this feature is not documented at all so I'm trying to blindly figure it out.

**Comment by Harmon758** [comment]
A full traceback would include the exact line where the exception occurred, not just an indirect call that caused it. Perhaps more importantly, it would also include the exception type and message itself.

There's [documentation for the commands extension on the rewrite branch](https://discordpy.readthedocs.io/en/rewrite/ext/commands/index.html).
For the async branch, you'll have to read the docstrings, but it *is* documented.

**Comment by jeremytiki** [comment]
![2018-08-03-220957_1735x323_scrot](https://user-images.githubusercontent.com/1173792/43671542-0b34a7aa-976a-11e8-877f-71f50cd6da8e.png)

Well I don't know what to tell you then, because that is all that is being printed out. The program is started, the command is called, and that's all she wrote. I do appreciate the link to the documentation though.

**Comment by Harmon758** [comment]
> `TypeError: on_message() missing 1 required positional argument: 'message'`

This is the pertinent line of the traceback with the exception type and message.
In this case, the line calling your coroutine actually is where the exception occurs.
As I suspected before and pointed out, this is because you're passing the `PluginClass` class itself, instead of an instance of it, to `add_cog`. This causes `on_message` to be called as a static method, meaning the actual `message` argument is passed in place of `self`. Hence the missing `message` positional argument error, since a second positional argument isn't passed.

**Comment by jeremytiki** [comment]
My bad, when I copied it out of the terminal I must have missed that last line without realizing it. Again, thank you for your help with this issue.
