### ISSUE TITLE
Offline member.status

### ISSUE THREAD

**Issue by helsyQ** [Rapptz/discord.py#1499]
```python
import discord
import asyncio

client = MyClient()

@client.event
async def on_ready():
    for member in client.get_all_members():
        print(member, member.status)

client.run('token', bot=False)

```
The account which I use, consists in a big server with many users. Output of this code shows me that almost all people on the server are offline, although this is not true.

**Comment by Harmon758** [comment]
This example isn't self-contained since you're using your own `MyClient` class.
However, I was unable to reproduce this with `discord.Client`.
Note, [self-bots](https://discordapp.com/developers/docs/topics/oauth2#bot-vs-user-accounts) [are not allowed](https://support.discordapp.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-), and it's possible that this is the cause of your issue.
Otherwise, are you certain you're seeing an offline status for people who are not offline?

**Comment by helsyQ** [comment]
Yeah, actually I used `discord.Client`, not `MyClient`, it's just a mistake in the example. So you want to say that I can't automatize normal user account in any way?

**Comment by Harmon758** [comment]
I'm saying automating normal user accounts is forbidden by Discord and doing so can result in your account being terminated, as stated in the developer documentation and support article that I linked.
Your issue also likely isn't actionable unless it's reproducible on a bot account.
