### ISSUE TITLE
play_audio only plays a short hissing sound

### ISSUE THREAD

**Issue by SilasBerger** [Rapptz/discord.py#1509]
## System information [edited]
- Windows 10
- Python 3.6.5rc1, 64-bit

## Problem description
I'm having troubles with the `play_audio` function in the `discord.py[voice]` library.

At the start of the script, I load my demo opus sound file as follows:
```
with open("assets/audio/testAudioFile.opus", "rb") as file:
    demo_audio_file = file.read()
```

When the bot is ready, I check for the opus library; the output is `True`:
```
@bot.event
async def on_ready():
    [...]
    print("opus library loaded:", discord.opus.is_loaded())
```

I then have a command that lets the bot user join the message author's voice channel, which invokes the following function:
```
active_voice_channel = await bot.join_voice_channel(voice_channel)
```
...where the `voice_channel` argument is the message author's `voice_channel` property.

The bot successfully joins the correct voice channel. Finally, I have a command that should play the demo audio file by calling the following method:
```
async def play_sound(channel, args):
    await bot.send_message(channel, "Playing sound with the following arguments: " + ", ".join(args))
    active_voice_channel.play_audio(demo_audio_file, encode=True)
```

This is where the problem occurs. The function gets called, the message gets sent and a sound gets played. However, instead of playing the audio file, you can only hear a very short hissing sound in the Discord voice channel. The script does not show any errors. Am I doing something wrong?

**Comment by Rapptz** [comment]
`play_audio` is a lower-level hook that accepts very specific things, mainly PCM. From your `.opus` extension I can only assume that it's not raw PCM. It's also meant to be called in a loop with specific timing (20ms per frame size).

Basically, I believe you're using the wrong tool for what you want to do. Generally people just spawn an ffmpeg process to handle this instead of using the admittedly hard to use lower-level `play_audio`.
