### ISSUE TITLE
How to add an control panel with tkinter?

### ISSUE THREAD

**Issue by KironDevCoder** [Rapptz/discord.py#1523]
I have an discord.py bot including an control panel (not really yet), I use commands.Bot() to define my bot and run it with bot.run(token) which halts the gui. The gui already uses threading.Thread so what's wrong? 
[Kiron's friendly bot.zip](https://github.com/Rapptz/discord.py/files/2299459/Kiron.s.friendly.bot.zip)

**Comment by Gorialis** [comment]
While you start and create another thread, it doesn't actually end up helping in this instance because your bot starts **using the other thread** (it's triggered by tk from you pressing the button). This means that your bot and tk event loop are still using the same thread, it's just no longer thread 0 (the default).

To fix this, rather than using a button to start your bot, merely start your bot normally at the bottom of the script after `tk.start()`. This starts tk on a different thread, and starts your bot on the main thread.

It's also worth noting that most asyncio objects are **not threadsafe**, so you will need to look into how to safely interact with asyncio from your tk thread.

**Comment by Hornwitser** [comment]
Firstly you're using `threading` wrong.  [Per the docs](https://docs.python.org/3/library/threading.html#thread-objects) (emphasis mine)
> ... There are two ways to specify the activity: by passing a callable object to the constructor, or by _overriding the `run()` method_ in a subclass. **No other methods (except for the constructor) should be overridden in a subclass.** In other words, only override the `__init__()` and `run()` methods of this class.

Secondly, you're not using threading in a way that would actually work.  Either the bot or tkinter needs to run in it's own thread.  Calling `bot.run()` from within a tkinter callback (as is done with your bot_start command) would block until the bot stops, rendering the interface unresponsive until that happens.

Thirdly this is not a help forum for asking about or getting help with issues you may have making your python program.  It is for _issues with the discord.py library_.

**Comment by BatteTarte** [comment]
Hello i have the solution:
This worked for me:
just run bot in another thread:
here is an example

```python
import threading
import discord
from tkinter import * 



client = discord.Client()

@client.event
async def on_ready():
    print(f'{client.user} has connected to Discord!')

def run():
  bot.run("bot token")

def an():
    t = threading.Thread(target=run)
    t.start()#run the "run" function on another thread
root = Tk()             
 
root.geometry('100x100')
 
# Create a Button
btn = Button(root, text = 'Run', bd = '5',
                          command = an) 
btn.pack(side = 'top')   
 
root.mainloop()
```
