### ISSUE TITLE
Updating the prefix of commands with a command...

### ISSUE THREAD

**Issue by Mrerl** [Rapptz/discord.py#1524]
Hello,
I've a problem, i want change the prefix of commands when the bot is already started and i've the code below (i've show you only the importants parts of the script)

when i run the bot and use the command, the bot say the new prefix value but in the console, there is 

> ERROR asyncio Unclosed client session

and the prefix doesn't change...

Do you have any solution to do that ?
```
import discord
from discord.ext import commands
import aiohttp
import re
from datetime import timedelta
import traceback
import os
import sys
from random import choice, randint



prefix='!'
token='[token]'
version = "v0 - 18/08/2018"

bot = commands.Bot(command_prefix=prefix)

@bot.command(pass_context=True, hidden=True)
async def setprefix(ctx, *, nprefix):
	nprefix = nprefix.strip()
	if nprefix != "":
		try:
			prefix = nprefix
			await commands.Bot(command_prefix=prefix)
		except:
			await bot.say("Impossible de changer le préfix ...")
		else:
			await bot.say("Le nouveau préfix est : **{}**".format(prefix))
```

**Comment by Hornwitser** [comment]
Rather than making a whole new Bot object, have you considered doing `bot.command_prefix = nprefix`?

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.

**Comment by Mrerl** [comment]
thanks
