### ISSUE TITLE
get_member function sometime returns None

### ISSUE THREAD

**Issue by FluffuKarma** [Rapptz/discord.py#1559]
My bot has many functions that require the get_member() function. These functions use stored user id's from a database as the argument. Sometimes the function returns None which is troublesome. Did anyone encounter this problem, is it because of the connection to the server? Any help will be appreciated.

**Comment by Vexs** [comment]
Get_member returns `None` when it can't find the member in cache. This is usually caused by using it when the bot is not logged in (in which case the cache is unfilled), or mixing strings and ints- IDs are strings on the async branch, and ints on the rewrite branch. 

However, if it's neither of these, this can't really be diagnosed without more information- and would be best done on the [discord.py discord server.](https://discord.gg/r3sSKJJ)

**Comment by bmintz** [comment]
If a User object is OK instead, and you *really need it*, you can use [Client.get_user_info](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Client.get_user_info), but this should be used sparingly, as it makes an API call which is heavily rate limited (even more so than banning members).
