### ISSUE TITLE
Change Status

### ISSUE THREAD

**Issue by Y4hL** [Rapptz/discord.py#1606]
I am using
`client.change_presence(game=Game(name="Watching Tv"))`
to change my status, but how to can i change the "Playing" part?
Since now its displaying "Playing Watching Tv"

**Comment by Harmon758** [comment]
On the rewrite branch, you can use [`discord.ActivityType`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.ActivityType) (with the `Activity` class).
Otherwise, you'll have to manually set [`discord.Game.type`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Game.type).
For those values, see:
https://github.com/Rapptz/discord.py/blob/8ef509883a2ea3d491bcce61750b4eae11770b3b/discord/enums.py#L221-L226

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.
