### ISSUE TITLE
Invite is returning None for uses, max_age, created_at, and max_uses

### ISSUE THREAD

**Issue by Mehvix** [Rapptz/discord.py#1625]
While I was trying to get who invited a user after they joined I ran into a bug with invite not returning data for `uses`, `max_age`, `created_at`, and `max_uses`. This is my code:

```
for guild in self.client.guilds:
            for invite in await guild.invites():
                invite = await self.client.get_invite(invite)
                x = [invite.url, invite.uses, invite.inviter.id, invite.max_age, invite.code, invite.created_at, invite.max_uses]
                before_invites.append(x)
            print(before_invites[0])
```
which then prints out `['http://discord.gg/22EEEeE', None, 01234567890123456789, None, '22EEEeE', None, None]`

So far I've double checked and the bot has all permissions in the server, [posted on stack overflow](https://stackoverflow.com/questions/52580564/invite-uses-returning-none) and made sure that there are invites for the server that have been used.

**Comment by Gorialis** [comment]
Invite instances from `get_invite` do not have this information. Having attributes missing is [documented in Invite](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Invite). However, using `get_invite` here is pointless, because **[`Guild.invites`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Guild.invites) returns a list of Invite instances already.**

**Comment by Mehvix** [comment]
Thank you!
