### ISSUE TITLE
Can't use permissions_for on bot

### ISSUE THREAD

**Issue by FunkyNeonChickN** [Rapptz/discord.py#1670]
I am writing a bot that commonly needs to use reactions and am attempting to add a line of code that makes the bot say it doesn't have but needs the add_reactions permission. After adding the following lines:
```
if not message.channel.permissions_for(bot.user).add_reactions:
	if not message.channel.permissions_for(bot.user).send_messages:
		return
	await message.channel.send('I can\'t add reactions to you\'re messages! Please allow me to add them so you can get Coins!')
	return
```
I got this error:
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\**********\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "Bot.py", line 93, in on_message
    if not message.channel.permissions_for(bot.user).add_reactions:
  File "C:\Users\*********\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\channel.py", line 114, in permissions_for
    base = super().permissions_for(member)
  File "C:\Users\**********\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\abc.py", line 418, in permissions_for
    roles = member.roles
AttributeError: 'ClientUser' object has no attribute 'roles'
```

It seems I cannot use the permissions_for function on the client user. Any fixes/workarounds?

Thanks in advance!

**Comment by Harmon758** [comment]
[`GuildChannel.permissions_for`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.abc.GuildChannel.permissions_for) requires a `Member` object.
You'll want to use [`Guild.me`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Guild.me) instead of `bot.user`.

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.

**Comment by FunkyNeonChickN** [comment]
Ok, thanks :)
