### ISSUE TITLE
Create issue template for GitHub

### ISSUE THREAD

**Issue by nariman** [Rapptz/discord.py#1685]
Hello!
I've subscribed to the repo recently for updates, and noticed that sometimes people ask questions using the issue tracker. It's ok, but, it would be nice, if issue template will be created with a friendly recommendation to join and ask help via Discord chat.
At least it should reduce the amount of non-library-development related questions (and notifications as well). At most, the issue history will not be cluttered with these questions and complicate issue/PR searching for potential contributors.
And, as a perk, issue structure may be created (checkbox steps and/or additional info requests, for example) to make resolving easier.

**Comment by c-x-berger** [comment]
See PR #990

**Comment by narimanized** [comment]
Yep, I saw it a long time ago. Unfortunately, there's no any activity about merging. If it supposed to be merged into rewrite, smth should be done as a temporary solution for a base branch (or merge it).
Just a reminder.

**Comment by c-x-berger** [comment]
This may be unsubstantiated nonsense, but to my knowledge Danny will go on merge/close sprees every once in a while. For most PRs you just have to patiently wait until something happens.

The `async` branch isn't getting updates anyway (the last commit was merged in January), so any issues with it are - as far as I know - usually invalid (fixed in `rewrite`, though there are [special cases.](https://github.com/Rapptz/discord.py/issues/1249))

**Comment by narimanized** [comment]
Okay. Got it.
I expected some sort of base branch support for "special cases" like this or bugs. B/c its a base branch. And b/c it's a branch, currently published on PyPI.

**Comment by laggycomputer** [comment]
See #1957.
