### ISSUE TITLE
[async] Help with times, need in commands

### ISSUE THREAD

**Issue by Matty2064** [Rapptz/discord.py#1688]
Im tryna make sum kindof timer without using asyncio.sleep()

I was trying to make a datetime.datetime.now() + timedelta(minutes=30) and put it in a json

and then every time an user checked the timer it would say how much till the timer ends, and when it ends it says **Ready!**

i tried, when i take the datetime out of the json its no longer an object but just a string so
plis help xd

**Comment by Matty2064** [comment]
Sorry also The reason why i used it in a json is so even if the bot is reset it would still be able to take the end point ``

**Comment by Harmon758** [comment]
The [JSON standard](https://www.json.org/) doesn't support datetime objects.
If you want to store it as JSON, you'd have to convert it back to a datetime object from the string or store seconds since the epoch instead.

This is not an issue with discord.py.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python or JSON.
For further help specific to using this library, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.
