### ISSUE TITLE
Allow editing on more guild options. (rewrite branch)

### ISSUE THREAD

**Issue by AL1L** [Rapptz/discord.py#1701]
I would like to edit and view the guild parameters `explicit_content_filter`, `default_message_notifications`, simple as that. I would add them myself, but I don't want to mess anything up haha. 

For now I've been manually doing things like
```pyhton
response = await client.http.request(Route('GET', '/guilds/{guild_id}', guild_id=guild.id))
default_message_notifications= response['default_message_notifications']
```
which is a bit hacky in my opinion.

Thanks 👍

**Comment by Modelmat** [comment]
See #450 .

**Comment by AL1L** [comment]
@Modelmat, if you looked I made a comment on #450, but it didn't have explicit_content_filter, so I just made a new issue 😋

**Comment by SpencerOs** [comment]
Been hunting (for a while) for a way to allow only certain roles to access emoji through something like the edit_custom_emoji() in https, and either I'm still too new to python (and this is easily possible) or I'm about to fall into the same hacky trap that AL1L fell into.

**Comment by Harmon758** [comment]
@SpencerOs This is possible on the rewrite branch, with [`Guild.create_custom_emoji`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Guild.create_custom_emoji) or [`Emoji.edit`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Emoji.edit).
Please don't hijack issues. For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.

**Comment by Harmon758** [comment]
[`Guild.default_notifications`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Guild.default_notifications) has now been added with https://github.com/Rapptz/discord.py/commit/1ac432d9f053812a1caab8330d14d4a9ba526289 (#1722) and https://github.com/Rapptz/discord.py/commit/8b18fa307b5e4a9acc6c057b7489c4d11de359b4.
[`Guild.explicit_content_filter`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Guild.explicit_content_filter) has existed since https://github.com/Rapptz/discord.py/commit/728fae928563057785be34324b13a5f3ffc9b83e and the ability to edit it has now been added with https://github.com/Rapptz/discord.py/commit/648e62031df69222b08c284d03b0491f55b8e24a.
