### ISSUE TITLE
Add option to pass image into Embed constructor

### ISSUE THREAD

**Issue by Technerder** [Rapptz/discord.py#1713]
Add the functionality to pass in an image url into a constructor of the Embed class.

**Comment by scragly** [comment]
There's more than one image location available for embeds, and they all are covered already in both the async branch and the rewrite branch as far as I'm aware.
I'm unsure as to what else you could be referencing, so most likely you're just not building your Embed correctly.
I'd recommend popping into the [discord.py support server](https://discord.gg/r3sSKJJ) to discuss further.

**Comment by scragly** [comment]
Seems mostly unnecessary.

The embed fields of `footer`, `image`, `thumbnail`, `video`, `provider`, `author` and `fields` are all considered relatively rich content in an embed data structure, not basic info.

We are unable to set `video` or `provider` fields, so they're outside of the scope of this library. But all of them have their own defined data structures that make them up, rather then simple single values.

Compare the basic attribute of `title` which is just a single string value, with `image`, which instead has the following fields in it's structure:  
`url`, `proxy_url`, `height` and `width`.

While we set only the `url` field when constructing our own embed object in preparation for sending, it's this difference between the basic attributes and the more rich ones that gives them their current treatment.

And as you have outlined, since `add_image` returns the instance, it can be still done in a single line.

I personally don't think it would be worth bothering to add it in the `__init__` arguments, but you're welcome to wait to see if anyone else might agree with you.
