### ISSUE TITLE
bot.unload_extension breaks when cog classes are imported from other directories and modules.

### ISSUE THREAD

**Issue by deepakraj-tc** [Rapptz/discord.py#1730]
I wanted to separate cogs into multiple .py modules and import them into `setup.py` file which contains
```
from . import Plugin
def setup(bot):
    bot.add_cog(Plugin(bot))
```
for better project structure but this breaks the working of `bot.unload_extension` method. 
https://github.com/Rapptz/discord.py/blob/860d6a9ace8248dfeec18b8b159e7b757d9f56bb/discord/ext/commands/bot.py#L733

**Comment by Rapptz** [comment]
As is, this issue is unactionable.

1. Your project structure (which seems to be a core part of the issue) is wholly missing.
2. You say it does not work (another core part of the issue) yet the details of it not working are also missing.
3. That line of code you link to is an *attempt* at making submodules work as is evident by the name.

Please take the time to improve your issue so it can be fixed.

**Comment by Hornwitser** [comment]
Is it correct that you want a cog from the `cosmos.core.plugins.presence.presence` module to be unloaded when you unload the `cosmos.core.plugins.presence.setup` module?  There does not appear to be way to reliably determine if a sibling module is part of an extension or not, so I don't think there's any nice way to fix that.

Though I don't see how this more organized, putting the setup function into `__init__.py` seems more elegant to me.

**Comment by deepakraj-tc** [comment]
OMG thanks a lot! 
Putting `setup` function into `__init__.py` worked perfectly fine preserving my original core project structure.
