### ISSUE TITLE
Change bot playing status.

### ISSUE THREAD

**Issue by x-PythonDev-x** [Rapptz/discord.py#1737]
As you guys may know in discord there are statuses, which are Playing, Watching, and Streaming

On my discord bot. I have the following code;

`await bot.change_presence(game=discord.Game(name='.help'))`

and It shows "Playing .help" which is fine. But I was wondering if there is any way to change the "Playing" to "Watching"?

Thank You!

**Comment by Harmon758** [comment]
On the rewrite branch, you can use [`discord.ActivityType`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.ActivityType) (with the [`Activity`](https://discordpy.readthedocs.io/en/rewrite/api.html#activity) class).
Otherwise, you'll have to manually set [`discord.Game.type`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Game.type).
For those values, see:
https://github.com/Rapptz/discord.py/blob/c30b016bb52b46bf34d53eef2a6710d46780dfff/discord/enums.py#L227-L232

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.
