### ISSUE TITLE
program crashes with event loop is closed 

### ISSUE THREAD

**Issue by boostgod1118** [Rapptz/discord.py#1794]
import discord
from discord.ext import commands
import requests
from random import randint
import random
import time

requests.packages.urllib3.disable_warnings()

TOKEN = ''

client = discord.Client()

@client.event
async def on_message(message):
   
    if message.content.startswith('!ebayviews'):
        old = message.content
        url = old.replace("!ebayviews", "").strip()
        print ("Viewer started")

        headers1 = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.91 Safari/537.36",
            "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
            }

        for i in range(50):
            try:
                r =  requests.get(url,headers=headers1,verify=False,timeout=5)
                if r.status_code == 200:
                    print ("Viewed successfully")
                
            except Exception as e:
                print(e)
        
        embed = discord.Embed(title="", color=0x00ff00)
        embed.add_field(name="Item finished being viewed 50 times", value="SneakerSpeak", inline=True)
        await client.send_message(message.channel, embed=embed)

    if message.content == ('!help'):
        embed = discord.Embed(title="", color=0x00ff00)
        embed.add_field(name="Give 50 views to an item", value="!ebayviews url", inline=True)

        await client.send_message(message.channel, embed=embed)
        
@client.event
async def on_ready():
    print('Logged in as')
    print(client.user.name)
    print(client.user.id)
    print('------')

while True:
    client.run(TOKEN)

error mesasage: RuntimeError: Event loop is closed 

someone please help

**Comment by Harmon758** [comment]
That error message isn't very informative. You need to include the full traceback and when the error occurs.
The direct cause of this error is because after your bot finishes running, you try to run it again with `client. run`. The event loop gets closed when `client.run` finishes executing, so you can't reuse the `Client` instance to `run` it again.
This would occur whether or not your bot terminated as expected or unexpectedly, since you have `client.run` in a while loop.

Note, requests is [blocking](https://discordpy.readthedocs.io/en/latest/faq.html#what-does-blocking-mean), which could explain any unexpected disconnects you're getting.

This doesn't seem to be an issue with the library itself. For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.
For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
