### ISSUE TITLE
No option to ignore Discord.py's handling of quotation marks in the commands extension

### ISSUE THREAD

**Issue by Yandawl** [Rapptz/discord.py#1796]
Hi there,

I have a command registered as follows

![sdoifjsdf](https://user-images.githubusercontent.com/8414953/50370143-612d3a80-0599-11e9-9dc9-e3ee8273e8f4.png)

Which will allow my bot to generate an image card for a person's FFXIV character.

![sdijfjdjf](https://user-images.githubusercontent.com/8414953/50370150-7f933600-0599-11e9-936a-5a4667e6a9e7.png)

The issue I have is that single quotes are valid in character names as you can see above, however on mobile (iOS) keyboards, the default single quote is the smart quote, which will cause Discord.py to throw an exception due to being caught out by the code on L180 in [this commit](https://github.com/Rapptz/discord.py/commit/ea061ef9b2ba64524b91af6036a615352ff9ce1a?diff=unified#diff-8748cbb8f0e94c2191006f0a036471baR180)

As far as I can tell the only means invoking users can get around this is by invoking the command with a parameter wrapped in double quotes as follows.

`?iam Brynhildr Nana "Mizuki’"`

Is there/ can an option be added to ignore Discord.py's handling of quotation characters in the commands extension please?

Thanks!

**Comment by Rapptz** [comment]
Sorry for the late response.

By using [keyword-only arguments](https://discordpy.readthedocs.io/en/rewrite/ext/commands/commands.html#keyword-only-arguments) you can disregard all quote handling since it's untouched. However, as a downside you can only have one of these but it gives you total control over how parsing is done for the most part.
