### ISSUE TITLE
Transferring server ownership to a bot does not error

### ISSUE THREAD

**Issue by StarrFox** [Rapptz/discord.py#1817]
When using guild.edit(owner=member) if the member is a bot it will act like it worked when it really did nothing.

This can be recreated by using client.create_guild (only bots with less than 10 guilds can use this) or by a selfbot with server owner

**Comment by Modelmat** [comment]
Discord doesn't allow boys to own servers generally. This doesn't error but it won't work anyway. Perhaps this could be added in the documentation?

**Comment by laggycomputer** [comment]
The title of this issue should be "Transferring server ownership to a bot does not error"

**Comment by StarrFox** [comment]
@Modelmat this can happen with self bots or if the bot is the one to create the guild (Bot/Client.create_guild)

**Comment by Modelmat** [comment]
I know, that's why I said generally (and you edited your first post a few minutes ago).
If it doesn't error I'm guessing this is on discord's end so there's not much that can be done about it, aside from documentation. 
Hard coding to make an error isn't good either as I'm pretty sure the discord docs don't really specify the actual specifics of when a bot can a guild, and hence can change at any time.

**Comment by DiamondDemon669** [comment]
bots can own servers but can a bot transfer ownership to a member?

**Comment by AbstractUmbra** [comment]
Please don't necro old issues.

This is a question for the [official help server](https://discord.gg/dpy) since it is not an issue with the library, but for usage of the library.

To answer though, [the docs](https://discordpy.readthedocs.io/en/latest/api.html?highlight=guild%20edit#discord.Guild.edit) have what you want. Look at the `owner` kwarg.
