### ISSUE TITLE
Python 3.6 on pip

### ISSUE THREAD

**Issue by skairunner** [Rapptz/discord.py#1820]
Hi,

Is there a reason discord.py only displays as for Python 3.4 and 3.5 on pypa? Skimming through issues it seems that discord.py does work on 3.6.

Because I use Pipenv which checks Python versions rather strictly, I cannot install discord.py on 3.6 version at all.

Edit: Apparently I was mistaken about the version-checking, but the question itself stands.

**Comment by Harmon758** [comment]
Because https://github.com/Rapptz/discord.py/blob/async/setup.py does not include the Python 3.6 classifier.
The async branch/version on PyPI does support Python 3.6, and you should be able to install it with Pipenv.
The error you're encountering is likely just an issue with locking, fixed with https://github.com/pypa/pipenv/pull/3338, which hasn't been released yet. See https://github.com/pypa/pipenv/issues/3324.

**Comment by BurnySc2** [comment]
I'm also running python 3.6 and discord.py is working well for me.

I guess I should probably open a new issue for this question, but since a python 3.6 issue is already opened and is quite recent:
Is there a reason that the requirements.txt lists `aiohttp>=1.0.0,<1.1.0` ?
I just completely reinstalled aiohttp (version 3.5.1 was installed for me) and discord.py still works fine for me.
I did a reinstall of aiohttp because I need a more up to date version to run some other package.

**Comment by Harmon758** [comment]
The async branch is no longer in development, so its requirements are no longer updated.
The rewrite branch has the aiohttp requirement as >=3.3.0,<3.5.0.
For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.
