### ISSUE TITLE
max_members attribute for guilds

### ISSUE THREAD

**Issue by TheRockettek** [Rapptz/discord.py#1822]
It seems the /guilds endpoint provides max_members but it seems rewrite does not allow you to see this in a guild object, would be nice to add this into the object.

**Comment by devakira** [comment]
It doesn't look like it's been documented, however it is present when you GET `/servers/(id)`.

![advancedrestclient_2019-01-06_08-43-49](https://user-images.githubusercontent.com/19719195/50736754-36dd9e80-118f-11e9-9d42-b429f707407b.png)

**Comment by TheRockettek** [comment]
> I'm not sure which attribute you're referring to.
> The [/guilds endpoint ](https://discordapp.com/developers/docs/resources/guild#create-guild)is used to create a guild, but I don't see `max_members` or any similar attribute that that could be referring to on https://discordapp.com/developers/docs/resources/guild.
> Where is this attribute documented and what does it signify?

the GET /guilds/(id) one not POST

**Comment by Rapptz** [comment]
This is retrievable only on the `GET /guilds/id` endpoint, and is not retrievable from the regular gateway flow (which the library mainly uses). Since there is no support for `GET /guilds/id` (at the moment, and probably for the foreseeable future) this suggestion doesn't apply to the library in its current state.

I'll keep it open as a suggestion though.
