### ISSUE TITLE
Can't Install Discord.py

### ISSUE THREAD

**Issue by H-Kearney** [Rapptz/discord.py#1826]
I am on macOS Mojave 10.14 and running Python 3.7 and when I try to run "pip install discord.py" it returns with the error: 

> Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/w8/8c53ljpd76q1tw7g7j5vlbdh0000gn/T/pip-install-p3E6eD/aiohttp/

What is the problem and how would I go about to fix it?

**Comment by Harmon758** [comment]
In the future, please just edit your existing issue instead of closing and remaking it.
A simple search for `Command "python setup.py egg_info" failed with error code 1` will return results with potential solutions to this problem.
This is not an issue with discord.py.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python.
For further help specific to using this library, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by H-Kearney** [comment]
kk thx for the help
