### ISSUE TITLE
can't add 0️⃣ reaction

### ISSUE THREAD

**Issue by FelisPhasma** [Rapptz/discord.py#1831]
When I try to add the 0️⃣ emoji as a reaction I get an Unknown Emoji error.
`
await client.add_reaction(message, "0️⃣")
`
This doesn't work with the other keycaps either. I have been unable to find a workaround.

**Comment by laggycomputer** [comment]
Have you tried using a Unicode string like one starting in `\u`? 
Please ask in the Discord API or discord.py servers for other questions like this.

**Comment by FelisPhasma** [comment]
@laggycomputer The keycap emojis are a combination of three codes, and I should be able to get it with: `\u0030\uFE0F\u20E3`, however, this doesn't work either. I have also tried `\N{keycap: 0}`. 
I'll ask in the discord api server.

**Comment by CapnS** [comment]
The Unicode string for 0️⃣ would be "0\u20e3".

**Comment by bmintz** [comment]
Or `"0\N{combining enclosing keycap}"`

**Comment by FelisPhasma** [comment]
@CapnS @bmintz ah ok that worked. Thanks!

**Comment by Harmon758** [comment]
Discord doesn't use Variation Selector-16 (U+FE0F) to display/combine emoji.
For example, if you directly copy and paste the three Unicode characters you're using in your code (`0️⃣`) into Discord, it will not render the emoji properly.
Simply removing the Variation Selector-16 and using `0` with a Combining Enclosing Keycap (U+20E3),  i.e. `0⃣`, will work. `'\u20e3'` and `'\N{combining enclosing keycap}'` are just different ways of representing the same Combining Enclosing Keycap character.
`keycap: 0` is not a valid Unicode character name, so `\N{keycap: 0}` will raise a syntax error telling you this.

Since your issue seems to have been resolved, feel free to close it now, and as previously indicated and as the README recommends, for future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help.
