### ISSUE TITLE
How to make the bot respond to a DM?

### ISSUE THREAD

**Issue by Nate94022** [Rapptz/discord.py#1833]
Hello, how would I make my bot respond to a dm? I have a command that DM's the user who sent the message but I would like to also make it so then the user can respond to the bot and the bot will respond back

**Comment by lganWebb** [comment]
Please could you state whether you are async or rewrite. Or for the best chance of help, please go to the [official discord.py server](https://discord.gg/r3sSKJJ)

**Comment by Flxtcha** [comment]
[official discord.py server](https://discord.gg/r3sSKJJ)

**Comment by Nate94022** [comment]
Alright thanks I joined the server

**Comment by Harmon758** [comment]
For the async branch, see:
https://discordpy.readthedocs.io/en/latest/api.html#discord.Message.channel
https://discordpy.readthedocs.io/en/latest/api.html#privatechannel
https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.send_message

For the rewrite branch, see:
https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Message.channel
https://discordpy.readthedocs.io/en/rewrite/api.html#discord.DMChannel.send

Since your issue seems to have been resolved, feel free to close it now, and as indicated and as the README recommends, for future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help.

**Comment by itssigron** [comment]
await ctx.author.send("message here")
