### ISSUE TITLE
Rewrite: on_member_update either not being called on name/discriminator change or before is acting as if it's after

### ISSUE THREAD

**Issue by CodingKanin** [Rapptz/discord.py#1835]
So I used to be able to call on member name change with this really old code:
```py
                if not before.name == after.name:
                    em = discord.Embed(color=0xFFFF00)
                    em.add_field(name='Member:', value='{}#{} | <@{}>'.format(before.name, before.discriminator, before.id))
                    em.add_field(name='Before:', value='{}'.format(before.name), inline=False)
                    em.add_field(name='After:', value='{}'.format(after.name), inline=False)
                    em.set_author(name='Name changed!')
                    em.set_thumbnail(url=before.avatar_url)
                    em.set_footer(text=time.strftime(fmt))
                    await ch.send(embed=em)
```
Here is proof that this worked:
http://kanin-is-not-a-bunny.club/51ENx4t.png

However now when I try to rewrite this function, my check does not work. When I print before it shows what I recently have changed it to, however someone has stated that this print may be from something else calling the event and that it may be completely ignoring the name/discriminator change.

**Comment by Harmon758** [comment]
I'm unable to reproduce this.
[`on_member_update`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.on_member_update) properly picks up username and discriminator changes with the `before` parameter having the proper attributes for the `Member` prior to the change.
I'm also unable to ascertain if this exact code will work, as it's not self-contained, e.g. you don't show what `fmt` and `ch` are defined as.
However, the check, `not before.name == after.name` should properly pick up username changes in `on_member_update` (although it should be `before.name != after.name`). It will not pick up discriminator changes, as that's not part of [`Member.name`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Member.name).
What version of the rewrite branch are you using?

**Comment by laggycomputer** [comment]
This should have the no repro tag by now.

**Comment by Hornwitser** [comment]
User objects are cached, and as far as I can tell, if a user shares multiple guilds with the bot only one guild will have the correct before user data.

**Comment by CodingKanin** [comment]
Apparently this is a known bug, according to Danny
http://kanin-is-not-a-bunny.club/bDZ5mHl.png

I'm not sure how you were not able to reproduce it, as it's known to exist 🤔 



> 
> 
> I'm unable to reproduce this.
> [`on_member_update`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.on_member_update) properly picks up username and discriminator changes with the `before` parameter having the proper attributes for the `Member` prior to the change.
> I'm also unable to ascertain if this exact code will work, as it's not self-contained, e.g. you don't show what `fmt` and `ch` are defined as.
> However, the check, `not before.name == after.name` should properly pick up username changes in `on_member_update` (although it should be `before.name != after.name`). It will not pick up discriminator changes, as that's not part of [`Member.name`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Member.name).
> What version of the rewrite branch are you using?

Also, that code is uber old, my new code isn't really the same. However fmt and ch had nothing to do with it, it's simply a strftime and a channel object. I've tried everything you're suggesting and sadly nothing has worked, I am aware that checking for the name wouldn't trigger if the discriminator has changed. I simply put that old code as an example as to what USED to work, and what doesn't now (for most everyone I suppose)

**Comment by CodingKanin** [comment]
My current code is this:
```py
    async def on_member_update(self, before, after):
        guild = before.guild
        channels = await self.get_channels(guild=guild, type="member")
        if not channels:
            return
        em = discord.Embed(color=self.bot.error_color)
        db = await r.table("ModLogs").get(str(guild.id)).run(self.bot.conn)
        embed = db["embed"]
        if before != after:
            if embed:
                em.set_author(name="User name/discriminator update:")
                em.add_field(name="Before:", value=before)
                em.add_field(name="After:", value=after)
                for channel in channels:
                    await channel.send(embed=em)
            else:
                for channel in channels:
                    await channel.send(f"User name/discriminator update: Before: {before} After: {after}")
```
However I have tried adding .discriminator after before and after in the check, as well as having name and discriminator. Nothing has worked, The channels are correct and function.

**Comment by Harmon758** [comment]
> Apparently this is a known bug, according to Danny

As @Hornwitser said, and as Danny said after that screenshot, the known bug is that if you share multiple guilds with the bot, you'll only receive one valid event where `before` has the right attributes. The events afterwards for the other mutual guilds will have a `before` that is not correct. I'm not sure if the guild the valid event is for is guaranteed to be a certain one in a specific order or not, but the username and discriminator for `before` for that event will be correct.

> I'm not sure how you were not able to reproduce it

> Also, that code is uber old, my new code isn't really the same.

> I simply put that old code as an example as to what USED to work, and what doesn't now

My reproduction attempts were based on the only code that you had provided, which isn't self-contained and doesn't show the whole `on_member_update` event. But based on the `not before.name == after.name` check, that "old code" should still work. It should pick up the single valid event and ignore the ones afterwards, which does not fit your description of the issue, namely that the check does not work and that `before` is always incorrect or that it completely ignores the name/discriminator change.

> My current code is this

Again, I'm unable to determine if this will work, because you don't show what `get_channels` does.
If `await self.get_channels(guild=guild, type="member")` does not return a truthy value (i.e. a list of channels) for every guild you share with the bot in question, it's possible that the first and only valid event is for one of those guilds and you're simply returning at the beginning before any checks are reached, thus ignoring the valid event. The check would ignore all the events afterwards.
If you added a print statement before your check, but after that return, it would only print the events for guilds where `get_channels` returns a truthy value. If this isn't every guild you share with the bot, it could miss the valid event, and subsequently print the invalid `before`s for the following events.

**Comment by CodingKanin** [comment]
I told you what get_channels does and returns, and it works for my other functions. I will be closing this because it's a known bug though. No point in all this.
