### ISSUE TITLE
README says 3.4.2+ but 3.7 (and 3.6?) not supported

### ISSUE THREAD

**Issue by ancestral** [Rapptz/discord.py#1842]
Can you update the README.md to say that Python 3.7 isn’t supported (and maybe mention using the rewrite branch is an option)? The README currently says the requirements include Python 3.4.2+.

Thanks

**Comment by SmCTwelve** [comment]
The `rewrite` branch README.md does state 3.5+ but there is no reference to using rewrite which is intentional as per #946. The docs are written as they would be at release. 

I would agree that mentioning `rewrite` as an option (with a heavy warning that it is WIP) would be useful since lots of search results like Stackoverflow refer to rewrite as most consider it stable enough to use. This further confuses people who look at the `rewrite` documentation, follow the instructions, then realise they actually downloaded `master`. 

Keeping people away from rewrite is understandable, but if they are going to go looking for it anyway then a warning with correct instructions is better than nothing.

**Comment by ancestral** [comment]
OK.

Regardless though, please specify what versions are supported with async, because 3.7 isn’t supported.

**Comment by gamescom15** [comment]
the async branch is no longer updated and will soon™ be replaced by rewrite

**Comment by ancestral** [comment]
I don’t think this issue is closed: Readme.md still says 3.4.2+, which is incorrect.

I think people who are trying to build this project need to have the correct dependencies, and readme.md is the first place many people will look.

**Comment by CapnS** [comment]
That branch is not being updated so it's not going to get fixed. People already told you this.

**Comment by ancestral** [comment]
If that’s the case can the default branch be changed?

The README.md for the project, the front face of the project on GitHub, the very first information people see is incorrect.

**Comment by CapnS** [comment]
The rewrite branch is not finished yet. It will be released when it is.
