### ISSUE TITLE
Add a specific AudioSource for opus

### ISSUE THREAD

**Issue by trollodel** [Rapptz/discord.py#1846]
Real-time encoding is a very heavy operation, and encoding before into opus is a good idea, but there isn't a specific AudioSource for opus, only through ffmpeg at the moment so it's useless.

**Comment by imayhaveborkedit** [comment]
I believe this was talked about some time ago and the result was that writing a parser for opus in python wasn't worth the effort or the possible python-land performance cost.  This seems to have been before the dapi wipe so I can't find the conversation anymore.

**Comment by imayhaveborkedit** [comment]
Since I've been working with voice stuff a lot lately (specifically digging into libopus) I thought I should expand on this one a bit.  While Danny says he doesn't exactly remember the rationale for dropping this idea, I suspect it was probably due to handling arbitrary *container* formats, not opus data itself.  There are various extra opus utilities to handle reading raw opus data (`.opus` files), but that's a pretty slim use case.  The python-land performance black hole would be from pure python decoders for the containers, which include ogg, mkv, webm, mpeg-ts, and mp4.  This is why ffmpeg is useful since it can handle all of those far faster than you could in python.  

If you (or anyone else reading this) has a use-case for handling raw `.opus` files, please comment and I will look into it further.

**Comment by imayhaveborkedit** [comment]
All of that said, `AudioSource` does have an `is_opus()` function that should return True if the audio is already opus encoded from whatever outside source.  It's up to you to get the data to that point though.
