### ISSUE TITLE
Changing status type.

### ISSUE THREAD

**Issue by Sn1p3sdev** [Rapptz/discord.py#1877]
I managed to do a looping playing status and tried it exactly the same with the type statuses (dnd, idle, online, etc.). I found a few numbers for the status but it proved to be no luck in a loop. Is this even possible in Discord.py?
Here's my code:

`statusword = ['at the Waterpark.', 'with xDan_i.', 'with imgenerouus.', 'with manslo']`
`statuscolor = ['2', '3']`

`async def change_playing_status():`
`	await bot.wait_until_ready()`
`	msgs = cycle(statusword)`
`	color = cycle(statuscolor)`
`	while not bot.is_closed:`
`		current_status = next(msgs)`
`		current_color = next(color)`
`		await bot.change_presence(game=discord.Game(name=current_status, type=))`
`		print('It works.')`
`		await asyncio.sleep(5)`
`bot.loop.create_task(change_playing_status()) `
P.S That isn't all of the code I have but I just added all of what's related.

**Comment by Hornwitser** [comment]
Changing the bot status every _n_ seconds is API abuse and will get your bot banned.

**Comment by Harmon758** [comment]
On the rewrite branch, you can use [`discord.ActivityType`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.ActivityType) (with the [`Activity`](https://discordpy.readthedocs.io/en/rewrite/api.html#activity) class).
Otherwise, you'll have to manually set [`discord.Game.type`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Game.type).
For those values, see:
https://github.com/Rapptz/discord.py/blob/1222bce271cf736b4db8c1eecb2823edd22f85dc/discord/enums.py#L236-L241

You have syntax errors on the end here:
`await bot.change_presence(game=discord.Game(name=current_status, type=))`
You need to properly specify the type value as you would any other keyword argument.

Also, note, you're attempting to exceed the rate limit on presence updates with only a 5 second wait.

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.
For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
