### ISSUE TITLE
(question) send message on flask web request

### ISSUE THREAD

**Issue by PancakeGD** [Rapptz/discord.py#1915]
I want a message to be sent after a web request (with flask) is made on my website. My code looks like this:

```
@app.route('/blahblah',methods=["POST"])
def blahblah():
  await client.send_message(member,"hi")
  return ("ok, sent")
```

However python considers the await a syntax error. What do I do?

**Comment by MusicOnline** [comment]
You can only `await` within `async def` blocks. Also, combining Flask and your bot in the same script isn't a good idea. If it even worked as easy as that, that is.

**Comment by Harmon758** [comment]
See https://docs.python.org/3/reference/expressions.html#await and https://docs.python.org/3/library/asyncio-task.html.

For further help, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by antsankov** [comment]
Just solved this poblem myself after going down the rabbit hole of asyncio and threading. Turned out to be way easier than I thought.

If your goal is to just simply send a message to a channel from a flask endpoint and not use anyother functionality, try webhooks. 
```
webhook = Webhook.partial(WEB_HOOK_ID, 'WEB_HOOK_TOKEN', adapter=RequestsWebhookAdapter())
```

and then post the message

```
 webhook.send('MESSAGE', username='WEBHOOK_BOT')
```

[Creating Webhook tutorial](https://github.com/Akizo96/de.isekaidev.discord.wbbBridge/wiki/How-to-get-Webhook-ID-&-Token)

[Discord.py Webhook Info](https://discordpy.readthedocs.io/en/latest/api.html#discord.Webhook.send)

**Comment by aaditisawesome** [comment]
What if I want to DM someone? How will I do that? I tried `client.loop.create_task(user.send('message'))` but it doesn't work when I am using Flask, because apparently flask is cutting the connection of discord.py before it can do anything.

**Comment by ObiDriftKenobi** [comment]
whoa, that's one hell of a necro
