### ISSUE TITLE
create_channel not getting server?

### ISSUE THREAD

**Issue by tokotchd** [Rapptz/discord.py#1935]
Error given is:
```Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "bot.py", line 19, in on_message
    newChannel = discord.Channel()
  File "/home/user/.local/lib/python3.6/site-packages/discord/channel.py", line 89, in __init__
    self._update(**kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/discord/channel.py", line 112, in _update
    everyone_id = self.server.id
AttributeError: 'NoneType' object has no attribute 'id'
```
Code responsible for this issue, stripped down as much as possible:
```@client.event
async def on_message(message):
    if message.author == client.user:
        return

    if message.content.startswith('!thread'):
        server = message.server
        print(server.id) #doesn't error here, prints an ID to terminal
        new_channel = client.create_channel(server, "new-test-channel", type=discord.ChannelType.text) #this line errors with the above error.
```

**Comment by gamescom15** [comment]
This is not an issue with discord.py.
GitHub issues for this repository should be used to report issues with this library.
For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.


Also, consider that `message.server` can be None in DM's.
Furthermore, if you are trying to create commands, consider looking into the built-in commands extension instead of ``message.content.startswith` in `on_message`

**Comment by Harmon758** [comment]
In your traceback, the error is coming from:
```
  File "bot.py", line 19, in on_message
    newChannel = discord.Channel()
```
where you're attempting to instantiate a `Channel` object, instead of using `Client.create_channel`.

For further help, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.
