### ISSUE TITLE
[rewrite] modify cog groups from other cogs

### ISSUE THREAD

**Issue by mrc0mmand** [Rapptz/discord.py#1942]
Hello!

With an older `discord.py` version (i.e. before the `commands.Cog` inheritance became mandatory) I was able to modify commands in groups of one cog from another one. This was particularly useful for a global config cog, e.g.:

```python
class Config:
...
    @commands.group()
    async def set(self, ctx):
        ...

class MyUsefulCog:
...
    @Config.set.command()
    async def useful_setter(self, ctx):
        ...
```

However, with the current version this is unfortunately not possible anymore, as any attempt in doing so ends with an exception:
```
Traceback (most recent call last):
  File "./main.py", line 16, in <module>
    bot.load_extension(ext)
  File "/home/fsumsal/venv/WatcherBot/lib64/python3.6/site-packages/discord/ext/commands/bot.py", line 618, in load_extension
    lib.setup(self)
  File "/home/fsumsal/repos/WatcherBot/_repro/cogs/cog2.py", line 14, in setup
    bot.add_cog(Cog2(commands.Cog))
  File "/home/fsumsal/venv/WatcherBot/lib64/python3.6/site-packages/discord/ext/commands/cog.py", line 155, in __new__
    parent = lookup[parent.qualified_name]
KeyError: 'group1'
```

The PoC can be found here: https://github.com/mrc0mmand/discord.py_reference_PoC

I'm not sure if this was ever intended as an actual use case, but is there any way how to achieve the former functionality?

**Comment by Rapptz** [comment]
I don't know how this "worked" in the prior version. I don't think it ever did. This seems like it would have confused the unloader. So as far as I'm concerned, this was never supported.

If you want to do something like this properly you'll need a couple of steps to do it manually.

1. You'll need to recreate the `Command` instance somehow. 
2. Add it naturally via `__init__`: 
```py
def __init__(self, bot):
    self.other_cog = cog = bot.get_cog('Some Cog')
    if cog:
        cog.some_group.add_command(command_instance_goes_here)
```
3. Remove it via `cog_unload`.
```py
def cog_unload(self):
    if self.other_cog:
        self.other_cog.some_group.remove_command('command name to remove')
```

The issue is getting the `Command` instance. Putting it in the cog would trip up the system since it expects *all* `Command` instances mapped to a `cls` attribute to be loaded as part of the cog. So decorating it with `@commands.command(...)` won't help you there. One solution is to do it globally outside of the cog and then on `__init__` you assign the `cog` attribute so things play well, putting it all together like so:

```py
@commands.command(name='foo')
async def my_other_command(self, ctx):
    await ctx.send('...')

class SomeCog(commands.Cog):
    def __init__(self, bot):
        global my_other_command
        my_other_command.cog = self
        self.other_cog = cog = bot.get_cog('OtherCog')
        if cog:
            cog.the_group.add_command(my_other_command)

    def cog_unload(self):
        if self.other_cog:
            self.other_cog.the_group.remove_command(my_other_command.name)
```

However, even taking this into consideration you still have the issue of what happens if `OtherCog` is removed before `SomeCog`. So you have to be careful with that as well, but that was the case with the original code too.

**Comment by mrc0mmand** [comment]
As I've actually never dealt with runtime cog unloading, I haven't thought about this issue. But you're right, it would be definitely better to just rewrite my code than trying to re-implement back the old (and incorrect) behavior. Thanks a lot for the explanation!
