### ISSUE TITLE
get the user who performed the action in on_member_update

### ISSUE THREAD

**Issue by mikewojtkiewicz** [Rapptz/discord.py#1943]
In the rewrite branch, is there a way to determine the user who did an update to a user? I'm writing a bot that handles nickname changes, but I need to determine whether the nickname has been changed by the user or by the bot. Any ideas?

**Comment by laggycomputer** [comment]
If the nickname change was done by a moderator, an audit log entry would be generated. You can check for an audit log entry inside your member update event

For more help, please join the Discord API server or the discord.py server, as the README recommends.

**Comment by Rapptz** [comment]
The API does not expose this information. You need to use [`Guild.audit_logs`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Guild.audit_logs) and work that out. The appropriate [`AuditLogAction`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.AuditLogAction) is [`AuditLogAction.member_update`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.AuditLogAction.member_update) as a starting point.

Since audit logs are complicated at the API level, there are a few moving parts so to help you out a bit more:

1. You iterate over the asynchronous iterator in [`Guild.audit_logs`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Guild.audit_logs) which gives you an [`AuditLogEntry`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.AuditLogEntry).
2. Check if the [`AuditLogEntry.action`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.AuditLogEntry.action) returns the one we care about (given above).
3. The [`AuditLogEntry.before`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.AuditLogEntry.before) and [`AuditLogEntry.after`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.AuditLogEntry.after) will have accompanying `nick` attribute fields as specified in the documentation for [`AuditLogAction.member_update`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.AuditLogAction.member_update).

Hopefully with these pieces in mind you can figure out the rest.

Good luck.
