### ISSUE TITLE
get_user_info will never return if awaited before bot has reached ready state

### ISSUE THREAD

**Issue by makusu2** [Rapptz/discord.py#1953]
If `await bot.get_user_info(id)` is called before the bot has had a full connection to the network (has reached the on_ready state), the coro will never return a value, even after the bot reaches a ready state.

```
def happens_before_ready(self, id):
     await self.bot.get_user_info(id) # never returns.
```
Should instead return once the bot has reached a state in which it is able to return the user info object, and the event loop reaches this line.

**Comment by diceroll123** [comment]
`Should instead return once the bot has reached a state in which it is able to return the user info object, and the event loop reaches this line.`

on_ready would be the state you're talking about. So you want a method called `happens_before_ready` to return after the bot is ready? If that's what you want, just throw `await self.bot.wait_until_ready()` in there. But I can assure you, this won't finish executing before the bot is ready. Also remember to make it an `async def`.

In any case, the reason this does what it does is because you can't get user info until the bot is ready. It tries, sees that there are no cached users, throws a silent error (I assume), then the bot becomes ready. This is by design, I believe.

**Comment by makusu2** [comment]
I hear you, but wouldn't it make more sense, since http requests are an async operation, for the line to stay part of the event loop until it successfully gets the data? Or at least print a warning?

**Comment by Rapptz** [comment]
This issue is unactionable. There is no proper debuggable info to work with it. No traceback or anything outside of "it doesn't work". Please make your issues actionable in the future next time. 

That being said, I do have a hypothesis on why it's failing for you. Chances are there is an uncaught AttributeError exception that you're ignoring.

`aiohttp` has a change in the future that requires the `ClientSession` to be initialized inside a coroutine rather than outside. So session creation was done inside `login` to prevent the error.

I do not know from this snippet whether you actually logged in (i.e. passed the credentials *required* to actually use the API) but if you didn't then I don't know what you were expecting. `Client.run` behind the scenes calls `login` and `connect`, the latter being the actual websocket connection.

**Comment by makusu2** [comment]
I'm sorry, you're right, I think I misunderstood what was happening; I can't reproduce it anymore. I'll keep the code that causes it in the future.

The credentials and such were all fine
