### ISSUE TITLE
Add Path support for attachment.save

### ISSUE THREAD

**Issue by makusu2** [Rapptz/discord.py#1958]
I'd like to add Path support for attachment.save.
Currently if you pass a pathlib.Path object to attachment.save, you get `AttributeError: 'OSPath' object has no attribute 'write'`. In other words, you must pass a string or filelike object. 
Would that be an acceptable change?

**Comment by Rapptz** [comment]
The concept of a "path-like" object is only in Python 3.6 or higher. This library (currently) targets 3.5 or newer.

Since this is the case I am unsure of how to deal with type checking in this case. I'm probably going to lean towards only accepting "path-like" objects in 3.6 or higher since the method that separates these (`__fspath__`) was only added then. An alternative to make it consistent amongst all versions would be to just add `try except` at the problem.

**Comment by makusu2** [comment]
Um! Doesn't "3.5 or newer" include "3.6 or higher"?
Also, I had meant for this to apply to the rewrite branch, which currently (as far as I can tell) doesn't support Path objects. 
But okay! Would it be okay to add Path support for the rewrite branch, where path-like objects are a thing?

**Comment by NCPlayz** [comment]
It does, but 3.5 support would have to be dropped, which wouldn't be helpful.

**Comment by makusu2** [comment]
Ohhh, I see. Okay! Then we probably shouldn't.
Thanks!! <3

**Comment by makusu2** [comment]
Why was this reopened? :o
