### ISSUE TITLE
Rich presence asset images not high resolution

### ISSUE THREAD

**Issue by kairusds** [Rapptz/discord.py#2041]
### Summary

The rich presence assets used in a selfbot does not produce a high resolution image.

### Reproduction Steps

By using the rich presence asset id.

### Expected Results

For it to use a high resolution asset image.

### Actual Results

It produced a low resolution image instead

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- discord.py version: 1.0.0a
- Python version: latest lts
- Operating system: Linux

**Comment by kairusds** [comment]
someone told me back then that the rich presence asset images are scaled for multiple devices but in truth this isn't how it is

**Comment by Vexs** [comment]
This doesn't sound like a discord.py issue at all. What specifically are you talking about? Can you provide an example?

**Comment by kairusds** [comment]
this is a selfbot
![](https://i.ibb.co/SJvCsJn/Screenshot-20190404-081611-cropped.png)

an electron app
![](https://i.ibb.co/VvCgN2f/Screenshot-20190404-081557-cropped.png)

**Comment by Vexs** [comment]
Discord.py doesn't have anything to do with these rich presences at all. I'm fairly sure you're in the wrong place.

**Comment by Harmon758** [comment]
@Vexs It's definitely possible to get rich presence data through an `Activity`.
I'm not sure if Discord allows you to set rich presence through a self-bot, but I think it should be possible to mimic a rich presence `Activity` and send the data as part of the payload with `change_presence`.

@kairusds However, if that is what you're doing (setting rich presence through a self-bot), @Vexs is right in that this isn't an issue with discord.py, as the asset IDs should be passed properly.
Rich presence is meant to be set with Discord's [RPC](https://github.com/discordapp/discord-rpc) [SDK](https://discordapp.com/developers/docs/rich-presence/how-to#step-0-get-the-sdk), which [updates the presence](https://discordapp.com/developers/docs/rich-presence/how-to#updating-presence-update-presence-payload-fields) with a `largeImageKey` and `smallImageKey`, representing images that were uploaded as part of the Discord application. When you retrieve these asset images as part of an `Activity` object via the API, they are presented in the form of asset IDs, representing images that are probably (down)scaled by Discord. If you copy those asset IDs and send them via the [Presence Update](https://discordapp.com/developers/docs/topics/gateway#presence-update) endpoint using `change_presence`, you're passing representations of images that have already been scaled, instead of the original image keys.
Note, since self-bots on [user accounts](https://discordapp.com/developers/docs/topics/oauth2#bot-vs-user-accounts) [are forbidden now](https://support.discordapp.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-), this isn't a supported method of setting rich presence, and there is no other method of doing so other than via the RPC SDK.
If your issue is with retrieving rich presence data through an Activity object that you did not create, then that's a different matter, and feel free to re-open this issue with a reproducible example using a bot account.
