### ISSUE TITLE
Hide catagories in server.channel iterable/create a filtered server.text_channels iterable

### ISSUE THREAD

**Issue by scOwez** [Rapptz/discord.py#2046]
### The Problem

I am trying to make a simple bot that generates a permanent invite link on the `on_ready()` event. The problem I am having is that when I try to make an invite link with:

```py
some_invite = await bot.create_invite(server)
```

It will return a channel not found error as shown below:

![image](https://user-images.githubusercontent.com/30081702/55675331-dd355f00-58b8-11e9-99c9-db4e53b5bf96.png)

This is fine as the docs are just a little outdated. I then try to use `server.channels[0]` to get the first (text) channel but that does not work as it is a dict iterable, not a list. So I then loop over it once like so:

```py
for channel in server.channels:
    some_invite = await bot.create_invite(channel)
    break # only want to iterate once
```

This does not work either as for whatever reason, it returns categories that you cannot use to make an instant invite with.

### The Ideal Solution

The ideal solution to this problem would to be using the `Server` class in the `bot.create_invite()` coroutine. This is not possible with discord.py though, as discord has changed their API (hence the documentation being slightly out of date).

The next ideal solution would be to do something like:

```py
some_invite = await bot.create_invite(server.text_channels[0])
```

This would have discord.py sorting through the API returns to filter out voice channels and categories and instead, return just text channels. The bot would then use the returned iterable to get the first text channel (`Channel` class) to use.

### The Current Solution

The current solution that is a temporary workaround but does not work well is to do:

```py
for ind, channel in server.channels:
    if ind is 1:
        some_invite = await bot.create_invite(channel)
        break
```

The reasons for this not working well are as follows:

* There may not be a category as the first channel & it will therefore skip the first text channel.
* The 2nd channel (the one the bot is using) may be a voice channel and will return the same error as shown in `The Problem` (the image).

### Summary

Create a iterable named `server.text_channels` that filters the output of `server.channels` into text channels only & throw a `NotFound` exception if there are no text channels. Or re-implement using the `Server` class in `bot.create_invite()`

### Notes

* I am using `bot` instead of the usual `client` that you commonly see
* Using the original, async branch for initial testing

**Comment by Harmon758** [comment]
The async branch isn't under development anymore. I would recommend that you switch to using the rewrite branch.
This is part of the reason that the documentation for the async branch is out of date.

> I then try to use server.channels[0] to get the first (text) channel but that does not work as it is a dict iterable, not a list.

I'm not sure what you mean by "a dict iterable", but [`Server.channels`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Server.channels) is just a normal iterable.

> This does not work either as for whatever reason, it returns categories that you cannot use to make an instant invite with.

`Server.channels` does include every channel. This is intentional.
If needed, you can filter/sort them by [`ChannelType`](https://discordpy.readthedocs.io/en/latest/api.html#discord.ChannelType) using [`Channel.type`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Channel.type).

> The ideal solution to this problem would to be using the Server class in the bot.create_invite() coroutine. This is not possible with discord.py though, as discord has changed their API (hence the documentation being slightly out of date).

You're correct in that the problem with this is that it would be ambiguous and/or unclear which channel to create an invite for. This used to be possible because of default channels, but as you noted, due to [a breaking change in the API](https://discordapp.com/developers/docs/change-log#breaking-change-default-channels), that can't be relied upon anymore. That's also why `create_invite` is now erroring for you with that server.

> This would have discord.py sorting through the API returns to filter out voice channels and categories and instead, return just text channels. 

This is actually already implemented on the rewrite branch, in the form of [`Guild.voice_channels`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Guild.voice_channels), [`Guild.categories`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Guild.categories), and [`Guild.text_channels`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Guild.text_channels).

Again, I would highly recommend that you switch to the rewrite branch, as it has exactly what you're requesting.
Otherwise, you'll have to manually check `Channel.type` to find the first text channel. One method would be to use one of the provided [utility functions](https://discordpy.readthedocs.io/en/latest/api.html#utility-functions).
I'm going to close this issue as it's not actionable, but feel free to join the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), also linked in the README, if you need more help.

**Comment by scOwez** [comment]
Yep, realised after opening the issue. Sorry about that :sweat_smile:
