### ISSUE TITLE
Dark mode docs (w/ option for light still)

### ISSUE THREAD

**Issue by MattIPv4** [Rapptz/discord.py#2050]
### The Problem

The docs burn my eyes due to the light theme used.

### The Ideal Solution

A dark theme with a toggle for users that oddly prefer to have a light theme for the docs

### The Current Solution

Using some jank stylus themes that are rather broken.

### Summary

Dark mode theme for the docs w/ option to use light theme still.

**Comment by tigerism** [comment]
first world problems

**Comment by MinerChAI** [comment]
https://discord.js.org/#/docs
They made good docs, with _turn off the lights_ option and other tiny features, check it, I haven't seen better documentation
_P. S. I haven't worked with discord.js_

**Comment by tigerism** [comment]
this is a preference, not an issue, therefore shouldn't be a github issue

**Comment by MattIPv4** [comment]
@tigerism The docs are on this GitHub repo and this is a pretty valid issue to raise as theming is configured through the docs source. Equally, if you had a legitimate issue with the naming convention of some methods within the library, an issue would be the correct way to raise it.

**Comment by Rapptz** [comment]
This seems to be a common request for whatever reason so here are the issues with it as I see it:

1. Making a dark theme on my end takes considerably more effort than making a dark theme on your end using Stylish since I have to modify CSS spread across 3 different files and hope I can get Sphinx to play nice
2. Even if you get a decent theme going, Firefox does not allow styling of the scrollbar without resorting to JavaScript which will bloat up the documentation even more.
3. If I were to add a dark theme, which takes time and effort, I would also have to store the preference somewhere using cookies which I also do not like doing and do it via JavaScript to toggle etc.
4. For a vast majority of the population and in many of the sites all around the world, white background on black text is the preferred solution for actually reading text. It is also an accessibility concern for those who have contrast issues. In similar vain, [studies have shown](https://www.ncbi.nlm.nih.gov/pubmed/25141597) that positive display polarity have several advantages so making dark theme the only option would be a bad idea.

**Comment by tjubutsi** [comment]
1. I think is just a matter of tinkering a bit. Stylus is easy mode but that shouldn't mean it's not worth the slight amount of effort.
2. The docs right now are 1.3mb. Adding https://github.com/Grsmto/simplebar (for example) would add a whopping 32kb.
3. Why is this a bad thing, how else would it happen.
4. This is indeed just an argument against ONLY dark mode, not against trying to implement a toggle.

**Comment by EEKIM10** [comment]
Honestly all this reminds me of is [this](https://images.app.goo.gl/NfCdeQ4fPXSkHWPY6)

**Comment by thegergo02** [comment]
I would recommend this, because I don't really have extensions for my browser.

**Comment by slice** [comment]
> If I were to add a dark theme, which takes time and effort, I would also have to store the preference somewhere using cookies which I also do not like doing and do it via JavaScript to toggle etc.

There's actually a [`@media` query to match against the user's preferred color scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme), however support is quite limited right now.

**Comment by Rapptz** [comment]
This has been implemented in the v1.6 rewrite of the documentation.
