### ISSUE TITLE
Add checking function for Client.wait_for

### ISSUE THREAD

**Issue by sizumita** [Rapptz/discord.py#2067]
### The Ideal Solution

Have a function for `client.wait_for`.  Something like:
```python
await client.wait_for('message', check=message.author_only) # Only message.author

await client.wait_for('message', check=message.channel_only) # Only message.channel
```

### The Current Solution

We have to write `check` function when we use `Client.wait_for` but it is also very short.

### Summary

We don't have to write short `check` function.

**Comment by Gelbpunkt** [comment]
Usually you would like check the author, content and other stuff as well. This would not allow it. If you want to keep it short, use a lambda.

```py
await client.wait_for('message', check=lambda msg: msg.author == ctx.author)
```

**Comment by Phxntxm** [comment]
Your example implies that the event being waited for will have the relevant parameters needed for what you want. Every event receives different parameters, because they are for different...well...events. IE `guild_join` doesn't receive a `message`, it wouldn't apply...it doesn't have a `channel`, it wouldn't apply.

In order to support something like this, every single possibility for every single event would have to be handled...there's no way that's going to be done just to save you a very very short amount of code to add a lambda/func as a check.

**Comment by iCode230** [comment]
how do i make the bot send an error message when the check condition is not met
