### ISSUE TITLE
Other languages

### ISSUE THREAD

**Issue by MinerChAI** [Rapptz/discord.py#2084]
### The Problem
There're only English and Japanese docs versions. Some people are bad in English, but they want to use this library, so if docs have translations on many languages it will be easier to understand.

### The Ideal Solution
Translate to more languages, you can use Crowdin for it

### The Current Solution
Only Japanese translation

### Summary
Add more translations

**Comment by MinerChAI** [comment]
Sorry if my English is bad

**Comment by Rapptz** [comment]
Translations are done by volunteers. If someone wants to translate the documentation then they are free to do so. In order for it to be merged into the main repository though, there needs to be substantial work done to show that you won't give up half-way through the process because there are thousands of strings to translate.

For example, the Japanese community had the following:

1. A community server for their language
2.  An issue detailing that they want to volunteer (#1426)
3. A now deleted repository that had previous translation work of several strings.

If you think whatever language you're representing has that and is willing to volunteer *long term* and not abandon it as the project matures then by all means, feel free to do so.

**Comment by hwhsu1231** [comment]
Hello @magistau

I have published the [discordpy-docs-l10n](https://github.com/localizethedocs/discordpy-docs-l10n) project, which aims to translate the discord.py documentation into multiple languages. See the [announcement](https://github.com/Rapptz/discord.py/discussions/10462) post for more details.

If the target language is not supported in the project yet, please submit an issue to [request for the new language](https://github.com/localizethedocs/discordpy-docs-l10n/issues/new?template=language_request.yml). Once the requested language is added, you can start translating!
