### ISSUE TITLE
Voice heartbeating interval wrong

### ISSUE THREAD

**Issue by TrungNguyen1909** [Rapptz/discord.py#2132]
### Summary

There was a bug in discord api that specified [here](https://discordapp.com/developers/docs/topics/voice-connections) saying that the `heartbeat_interval` is actually 75% of the sent one. This cause the voice to be muted after an amount of time. I've fixed it locally, please fix the one on master. Thanks
the bugged file is `gateway.py`, line 687 should be something like:
`interval = (data['heartbeat_interval'] / 1000.0)*0.75`
### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- discord.py version: 1.0.1
- Python version: 3.7.3
- Operating system: All

**Comment by AutumnClove** [comment]
Omg does this fix having to move channels sometimes? And like having to disconnect and reconnect my bot from a voice channel to hear audio again?

**Comment by Rapptz** [comment]
As far as I'm concerned there are a few wrong assumptions here:

1. The library is not using v3 of the documented voice protocol, it is using v4. From what I gather this issue is fixed in that version of the protocol. v4 is not documented officially.
2. The gateway disconnects you after it misses 2 heartbeats, not one. So even if the timing were off there shouldn't be any disconnects from missing heartbeats (and, since this is the first issue to be opened in the last 1.5+ years of that code existing, chances are no one has disconnected from heartbeats).

Granted, there is no harm in heartbeating more often, even if ultimately it does nothing. I'm mainly curious on why you made the change locally and what issue that solved.
