### ISSUE TITLE
Game activity faild

### ISSUE THREAD

**Issue by FireServerPE** [Rapptz/discord.py#2136]
await bot.change_presence(activity=discord.Streaming(name="My Stream", url=""))
AttributeError: 'Command' object has no attribute 'Streaming'

**Comment by Harmon758** [comment]
You're very likely shadowing `discord`.
Make sure you're referencing the `discord` library that you've imported instead of a `discord` command that you've defined.

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README also links.
