### ISSUE TITLE
Get a discord.Colour from a status

### ISSUE THREAD

**Issue by BluePhoenixGame** [Rapptz/discord.py#2199]
_I just wanna say that i am working on this and created this feature request to discuss the aspects of it._
### The Problem

Currently it's not possible to get a colour from a status without making your own function. This i use in for example any info commands i have in the embeds to display a members status. It would be good if the library implemented this.

### The Ideal Solution

1. Have a from_status() classmethod in discord.Colour. `discord.Colour.from_status(discord.Status.online)`
2. Be able to pass in a discord.Status as a value in discord.Colour's init `discord.Colour(discord.Status.online)`
3. Add a attribute to discord.Status that returns the colour value. Maybe something like: `discord.Status.online.colour` _I know that this would need discord.Status to be redesigned and might not be able to work at all._
3. Add a method to discord.Status to return the colour value. Kind of like this: `discord.Status.online.get_colour()`
4. Have some utility function that returns the colour. Maybe something like `discord.utils.colour_from_status(discord.Status.online)`
5. Same as 4 but have it in ext.

### The Current Solution

Currently you have to design your own function, it would be nice if the library implemented this for you.
### Summary

It would be good to be able to get the colour of a status.

**Comment by OrangutanGaming** [comment]
As the colour is not actually part of the API, I don't think it really makes sense for it to be part of the main library, however, I think that a util is right for this. The use case seems pretty small though, still not sure why you would really do this.

**Comment by Rapptz** [comment]
This isn't really something I want nor does it make sense to include.

1. A status does not inherently have a colour. You don't need to look very far to know this is the case, for example the `Streaming` activity takes over from any `Status` and displays it as purple. 
2. The display of the status *icons* varies between platforms. On Android the idle status looks like a crescent moon while on the desktop it looks like a regular circle. Keeping this in mind, there is clearly no sense of consistency within the client to implement this as they could also vary by colour and we could not know.
3. The visual representation of a status is better indicated with an emoji rather than a colour, which the library obviously cannot provide.
4. The status <-> colour conversion is not available nor documented anywhere in the official API.
5. This helper function is relatively niche and can just be implemented yourself using a simple dictionary that you write once and forget about.

Given all the reasons above I don't think this feature request is worth pursuing.

**Comment by BluePhoenixGame** [comment]
Okay, i see. I get that this got disapproved, and i'll just make my own function for it.
