### ISSUE TITLE
Error adding role command, says string not found

### ISSUE THREAD

**Issue by Ilmc57** [Rapptz/discord.py#2216]
I want to use an addrole command that adds a role to a mentioned user, however when I type in the role it says "role x not found."

I tried using the role name, role id, I also tried using ``role = discord.utils.get(ctx.guild.roles, name=role)`` as well, and it still won't work.

```python
@commands.command()
async def addrole(self, ctx, user: discord.Member=None, *, role: discord.Role=None):
     author = ctx.message.author

     if user == None or role == None:
        await ctx.send("```Usage: ;addrole <user> <role>```")
     else:
         try:
             await user.add_roles(role)
         except Exception as e:
             print(e)
         else:
             await ctx.send(f'Added {role} to {user}')
```
Output in console, trying the role "Unapproved" (also de-capitalizes the role name, if that matters, no matter what I used as the input, and yes, this role exists in the server):

``Role "unapproved" not found.``

**Comment by 15695** [comment]
what is `role`? when you use `role = discord.utils.get(ctx.guild.roles, name=role)`, `name` is supposed to be a string containing the roles actual name

**Comment by Ilmc57** [comment]
Yeah, well like I said I also tried that
Like this:
```python
@commands.command()
    async def addrole(self, ctx, user: discord.Member=None, *, role: discord.Role=None):
        author = ctx.message.author

        if user == None or role == None:
            await ctx.send("```Usage: ;addrole <user> <role>```")
        else:
            try:
                role = discord.utils.get(ctx.guild.roles, name=str(role))
                await user.add_roles(role)
            except Exception as e:
                print(e)
            else:
                await ctx.send(f'Added {role} to {user}')
```
This didn't work either

**Comment by Rapptz** [comment]
1) The `discord.Role` converter does not (and will not) lower-case the text and do a comparison that way. What this means is that this statement: "also de-capitalizes the role name, if that matters, no matter what I used as the input, and yes, this role exists in the server" does not make sense.
2) If you're looking for case insensitive fetching then the `discord.Role` converter is not going to do it.
3) `discord.utils.get` also works through exact matching and not case-insensitive matching.
4) Your signature defaulting to `= None` and then checking it inside the body is generally bad practice. This can be better done by not doing that and then using an error handler: https://discordpy.readthedocs.io/en/latest/ext/commands/commands.html#error-handling
5) If this is executed inside the body then `name=role` is equivalent to the role object and this would never match because the converter has already found the role for you. See the docs [here](https://discordpy.readthedocs.io/en/latest/ext/commands/commands.html#converters) on converters for more info.

As a result, I believe this issue is unreproducible and seems to stem from user error.

**Comment by Ilmc57** [comment]
Would this be correct..?
```python
@commands.command()
    async def addrole(self, ctx, user: discord.Member, *, role: discord.Role):
        await user.add_roles(role)
        await ctx.send(f'Added role {role} to {user}.')
```
Doing ;addrole <user> Unapproved threw a ``Role "unapproved" not found.``
I also tried this:
```python
@commands.command()
    async def addrole(self, ctx, user: discord.Member, *, role):
        role = discord.utils.get(ctx.guild.roles, name=role)
        await user.add_roles(role)
        await ctx.send(f'Added role {role} to {user}.')
```
Doing the same command threw a ``AttributeError: 'NoneType' object has no attribute 'id'`` error

**Comment by TheRockettek** [comment]
simply because there's no role called unapproved. The error on the bottom one is because utils.get couldn't find a role with that name either and returned None. I recommend checking if role is None before adding the role to return some sort of message saying that role doesn't exist if you are using the bottom one or by giving an Optional for the top one.

If you need more help, hop on the discord.py server at https://discord.gg/r3sSKJJ

**Comment by Hornwitser** [comment]
The server you're invoking the command from doesn't have a role named "unapproved".

**Comment by Ilmc57** [comment]
So I just ran the command ``;addrole <user> Unverified`` on a server that has this role (using the code referenced last above) and got ``AttributeError: 'NoneType' object has no attribute 'id'`` again:
![image](https://user-images.githubusercontent.com/26722651/59553141-c9fcda80-8f5e-11e9-8edb-02a9c58189df.png)

**Comment by NCPlayz** [comment]
Hey, can we move this to the official server (https://discord.gg/r3sSKJJ)? You'll get better help and people will be relieved from their emails. 😁

**Comment by Ilmc57** [comment]
Oh, sure!
