### ISSUE TITLE
on_reaction_add won't run a all.

### ISSUE THREAD

**Issue by solsahar** [Rapptz/discord.py#2229]
Hi everyone! I'm having an error where my on_reaction_add function doesn't get run at all.

Heres my code:
`@client.event
async def on_reaction_add(ctx, reaction, user):
    print("Reaction add event run")
    if(reaction.message.id == pingRolesMessageID):
        if(reaction.emoji == "one"):
            role = discord.utils.get(user.server.roles, name="Announcements")
            await ctx.add_roles(user, role)
        if (reaction.emoji.name == "two"):
            role = discord.utils.get(user.server.roles, name="Partners")
            await ctx.add_roles(user, role)
        if (reaction.emoji.name == "three"):
            role = discord.utils.get(user.server.roles, name="Giveaways")
            await ctx.add_roles(user, role)
        if (reaction.emoji.name == "four"):
            role = discord.utils.get(user.server.roles, name="Other")
            await ctx.add_roles(user, role)
    await client.process_commands(reaction.message)
`
Nothing actually runs through.

- [x] I have searched the open issues for duplicates.
- [x] I have searched on the docs.
- [x] I have tried all other examples I have found.

I am using the following things:
Python 3.7
Latest Discord.py rewrite
Windows 10

If anyone could help, I would really appreciate it.

**Comment by laggycomputer** [comment]
`on_reaction_add` is only triggered for messages in the internal cache. If the bot seems to be "missing" added reactions, try using `on_raw_reaction_add`.

P.S. do you mind using codeblocks and re-pasting your code? The format is:
\```py
[code]
```

**Comment by CapnS** [comment]
There are so many things wrong here I don't know where to start.

1. on_reaction_add does not take a ctx argument, only reaction and user. [DOCS](https://discordpy.readthedocs.io/en/latest/api.html#discord.on_reaction_add)
2. You say you're using rewrite (Which is not even called rewrite anymore as it is the master branch), but you use async code such as `user.server`
3. You use ctx.add_roles() which is not a thing, and has never been a thing (not even in async), so I don't know where you got that from.
4. This is not an issue with discord.py. GitHub issues for this repository should be used to report issues with this library. They are not a medium for requesting help with Python. For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.
5. While this is just an aesthetic thing to make your code easier to read, It is recommended to use 3 backticks for codeblocks, instead of 1 which is used for a one-liner.
