### ISSUE TITLE
 await bot.http.remove_reaction() with custom emoji's doesn't function as expected.

### ISSUE THREAD

**Issue by SobieskiCodes** [Rapptz/discord.py#2230]
### The Problem
await bot.http.remove_reaction() doesn't handle custom emoji's as expected, if you give it a custom emoji you get;
In emoji_id: Value "577578847080546304>" is not snowflake.
because custom emoji's are name:id
### The Ideal Solution
We can let the function know we are passing it a custom emoji (or something of the sort?)
await bot.http.remove_reaction(payload.channel_id, payload.message_id, custom_emoji = custom, payload.user_id)
### The Current Solution
We currently have to create a new variable to send;
```
custom = bot.get_emoji(577578847080546304)
example = f'{custom.name}:{custom.id}'
await bot.http.remove_reaction(payload.channel_id, payload.message_id, example, payload.user_id)
```
### Summary
if we could just have a way to let it know we are passing it a custom emoji and have it create the correct http post.

**Comment by OrangutanGaming** [comment]
Why are you using an undocumented method when there is one that is meant to be used instead and is more user-friendly?

**Comment by TheRockettek** [comment]
You aren't expected to use this function as it is for internal use and is not even documented. I recommend using the function that is already documented and would support this

**Comment by avayert** [comment]
The [`HTTPClient`](https://github.com/Rapptz/discord.py/blob/master/discord/http.py) interface is by design a "lower-level" interface to make HTTP API calls to Discord. It's main purpose is to be used internally by the library, not by the end user of the library. You can tell this by the fact that it is not publicly documented.

For the higher level API,  [`Message.remove_reaction`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Message.remove_reaction) exists, which does strip the `<>` from a passed string, as demostrated [here](https://github.com/Rapptz/discord.py/blob/master/discord/message.py#L874-L877).

The [Discord API](https://discordapp.com/developers/docs/resources/channel#delete-user-reaction) expects the emoji to be in the `name:id` format for the request, so the `HTTPClient` interface also expects it in that format. As the main purpose of `HTTPClient` is to serve as internal abstraction for the developer, this behaviour is expected.

**Comment by SobieskiCodes** [comment]
> 
> 
> Why are you using an undocumented method when there is one that is meant to be used instead and is more user-friendly?

Seemed easier.
```
@bot.event
async def on_raw_reaction_add(payload):
    if payload.message_id == 590509269603057686:
        channel = bot.get_channel(payload.channel_id)
        message = await channel.fetch_message(payload.message_id)
        user = bot.get_user(payload.user_id)
        custom = bot.get_emoji(577578847080546304)
        await message.remove_reaction(custom, user)

@bot.event
async def on_raw_reaction_add(payload):
    if payload.message_id == 590509269603057686:
        custom = bot.get_emoji(577578847080546304)
        await bot.http.remove_reaction(payload.channel_id, payload.message_id, custom, payload.user_id)
```

**Comment by xoxfaby** [comment]
Maybe it would be worth considering to give better documented access to API methods that use ID's and such. If you already have the ID, there is no point in fetching the message just to call method on it directly.

**Comment by BluePhoenixGame** [comment]
I just want to leave this out there that you can instance discord.Object with the id and then just do the function you want to use.

**Comment by Rapptz** [comment]
Superseded by #5905
