### ISSUE TITLE
let the library pick it's own adapter

### ISSUE THREAD

**Issue by Blacksilver42** [Rapptz/discord.py#2241]
### The Problem

When creating a webhook from URL, I don't really care how you deliver the payload. Figure it out yourself.

### The Ideal Solution

Make the `adapter` argument in `Webhook.from_url` and `Webhook.partial` optional.

**Comment by Blacksilver42** [comment]
Don't just leave a thumbs down, at least tell me *why* this is impossible.

**Comment by CapnS** [comment]
This is not possible because AsyncWebhookAdapter requires a session, which the use has to pass. There is no way for the webhook to get the bot's session without the user explicitly telling it. And the reason we can't just choose RequestsWebhookAdapter is because it would be blocking, which could lead to disconnections. The reason the user is allowed to choose is so that this can be used in a sync or async environment.

**Comment by avayert** [comment]
The adapter exists to support both sync and async usages of webhooks. Sometimes you might want to use them in an async context e.g. inside your bot, while other times you might want to just use the webooks on their own.

The library cannot know which context the user is operating in, and no matter what you would set as a default, it would hinder the other use case. If the user was working in a sync environment and the default was the async adapter, it would not be able to run. But on the other hand, if the user was working in an async environment, and the default was the sync adapter, the requests would be blocking the event loop, which could have other effects on your program as it is not able to run.
