### ISSUE TITLE
'Bot' object has no attribute 'say'

### ISSUE THREAD

**Issue by crensyhanilas** [Rapptz/discord.py#2260]
i just maked the `@bot.command()
async def ping(ctx):
	await bot.say('Pong!')` but it's don't working...

**Comment by laggycomputer** [comment]
You seem to be using some code for the old version of this library, v0.16.x (aka async, no longer supported), and some for the latest version, v1.x.

As for how to fix your problem, `bot.say` should be replaced with `ctx.send`.
For further help, kindly see the support server at https://discord.gg/r3sSKJJ.

**Comment by Rapptz** [comment]
You are using an old version of the library, 0.16.12, which is unsupported. In order to receive support, it would be a good idea to migrate to the newest version. If you need help migrating, visit the migration guide: https://discordpy.readthedocs.io/en/latest/migrating.html

If you need more help consider joining the [official Discord server](https://discord.gg/r3sSKJJ). Please do not open more issues regarding migration or the old version. Thank you.

**Comment by crensyhanilas** [comment]
Working! Thanks
