### ISSUE TITLE
`permissions_for` to accept `Role`

### ISSUE THREAD

**Issue by dragdev** [Rapptz/discord.py#2293]
### The Problem

xyz.permissions_for only takes a `Member`. ability to accept roles as well would be awesome and so much more convenient.

### The Ideal Solution

ability to pass role objects to permissions_for

### The Current Solution

overwrites_for(role_

**Comment by Rapptz** [comment]
I don't really get the point of this concept.

`permissions_for` does a lot of handling with permissions including server permissions + channel specific overrides. The permissions resolved without taking into consideration the actual member doesn't seem to have much use since it doesn't tell you anything actionable or concrete. A member with that role won't necessarily have that resolved permission.

**Comment by dragdev** [comment]
> permissions_for does a lot of handling with permissions including server permissions + channel specific overrides
there are overwrites for roles on channels too, so, why not just list them and the guild permissions on the executed channel?
