### ISSUE TITLE
`command` decorator and custom attributes

### ISSUE THREAD

**Issue by Backdoorek** [Rapptz/discord.py#2332]
### The Problem
According to [docs](https://discordpy.readthedocs.io/en/latest/ext/commands/commands.html#):

>Any parameter that is accepted by the Command constructor can be passed into the decorator. For example, to change the name to something other than the function would be as simple as doing this:
```python
@bot.command(name='list')
async def _list(ctx, arg):
    pass
```

So I expected that when I will create something like this, that the attribute `auth_level` will be created.
```python
@command(auth_level=0)
async def howdy(self, ctx: Context):
    await ctx.send(f'I\'m fine, thanks {ctx.author.mention} UwU')
```

### The Ideal Solution

The ideal solution will be that, the custom attrs will be created or stored in something public (ex. dict)
```python
ctx.command.auth_level # Returns 0
# or
ctx.command.custom_kwargs[auth_level] # Returns 0 too
```

### The Current Solution

```python
ctx.command.__original_kwargs__[auth_level]
```

### Summary

I think that should be marked in docs, what happens with custom attrs in custom decorator.  I can make pull request or something if there is that kind of need.

**Comment by Vexs** [comment]
As per the docs you listed, anything that goes in the constructor can be put in the decorator, and putting `auth_level` in the command constructor won't do anything either. 

Further, guessing by your usecase, it looks to me like you want [checks.](https://discordpy.readthedocs.io/en/latest/ext/commands/commands.html#checks)

For your usecase, you could in fact just add the attribute wherever you want- or subclass it to make the constructor do something with the extra kwarg. In cogs you have the cog constructor `command_attrs` kwarg which sets arbitrary attributes on all commands in the cog as well.

**Comment by Backdoorek** [comment]
@Vexs 

> Further, guessing by your usecase, it looks to me like you want checks.

I was thinking about checks, but I need to use different `Context` classes according to auth_level variable.
```python
class ExtendedBot(Bot):
    async def on_message(self, message):
        ctx = await self.get_context(message, cls=Context)
        if 'auth_level' in ctx.command.__original_kwargs__:
            ctx = await self.get_context(message, cls=ExtendedContext)
        await self.invoke(ctx)
```

**Comment by Rapptz** [comment]
The approach presented in the issue is not going to be supported.

There are a few ways to do what you want.

1) Don't use two different context classes, I don't really think it makes much sense to since you basically do the potentially expensive operations twice (prefix retrieval (might query db), initial command parsing, etc). It's just not very efficient in general.

Instead, within your extended methods just check if the auth level is set to something. You can default to `None` and then inside a check or a before-invoke hook you can set the attribute for the auth level per command. 

2) If you really want to stick with your initial design, then you'll have to make a custom command class and then pass it into the decorator: 
```py
class MyCommand(commands.Command):
    def __init__(self, *args, **kwargs):
        self.auth_level = kwargs.pop('auth_level')
        super().__init__(*args, **kwargs)

# Somewhere else
@command(auth_level=0, cls=MyCommand)
async def foo(self, ctx):
    pass
```
