### ISSUE TITLE
'await' outside function

### ISSUE THREAD

**Issue by NikolaiMihov** [Rapptz/discord.py#2391]
i'm trying to make a bot go offline with a command 
i use:
   if "#go.away" in message.content.lower():
        await client.close()

and get

SyntaxError: 'await' outside function

can anyone help?

**Comment by Harmon758** [comment]
https://docs.python.org/3/library/asyncio-task.html
https://www.python.org/dev/peps/pep-0492/

This is not an issue with discord.py.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python.
For further help specific to using this library, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README also links.

**Comment by HebaruSan** [comment]
Is there any possibility of `discord.py`'s functionality being accessed via synchronous functions? Dealing with Python's async implementation may be more painful than strictly necessary for some use cases. (E.g., I just need to log in and then send messages from another source, no need to react to Discord events at all.)

**Comment by Vexs** [comment]
If you just want to send messages, use [webhooks](https://discordpy.readthedocs.io/en/latest/api.html#webhook-support) which have an async and a sync api. 
If that still doesn't work, it's easy enough to make the requests to the API using requests or some other sync lib.

Discord.py is very fundamentally async because logging in and receiving events (which is really a primary goal of discord.py) simply cannot be sync. As mentioned prior, it's very easy to do everything except event handling yourself with a library like requests.

**Comment by HebaruSan** [comment]
I take it there's some more setup required somewhere to use `discord.Webhook`? The documentation of the `id` parameter is non-informative.

```
discord.errors.NotFound: 404 NOT FOUND (error code: 10015): Unknown Webhook
```

**Comment by Rapptz** [comment]
This issue has been answered and your queries are unrelated to the original issue. If you need more help consider joining the [official Discord server](https://discord.gg/r3sSKJJ).
