### ISSUE TITLE
Channel not detected

### ISSUE THREAD

**Issue by GlitchSabre** [Rapptz/discord.py#2402]
Channel not detected
---------------------------

I just installed rewrite branch of discord .py[voice].
The bot is not able to detect any channel on my guild. But it is functioning otherwise properly.

Code:

@client.event
async def on_member_join(member): 
    #print(member.guild.('637135089150722048'))
    chnl = client.get_channel('637135089150722048')
    chnl.send('hi')

**Comment by Phxntxm** [comment]
The issue here is that IDs are `int`s not strings. However GitHub issues for this repository should be used to report issues with this library. They are not a medium for requesting help with the library. For further help specific to using this library, you should join the official [discord.py server](https://discord.gg/r3sSKJJ)

**Comment by Harmon758** [comment]
The rewrite branch does not exist anymore. It has become the regular version of discord.py.
As explained, [IDs are now `int`s](https://discordpy.readthedocs.io/en/latest/migrating.html#snowflakes-are-int). See [the documentation](https://discordpy.readthedocs.io/en/latest/migrating.html) for help migrating.

As also pointed out, for further help using the library, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README also links.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
