### ISSUE TITLE
command not found error?????

### ISSUE THREAD

**Issue by XziimP** [Rapptz/discord.py#2408]
No command found error? the only command that works is help. I know there must be a simple answer to this so please do not direct me to discord docs that does not help. 

The end result I expect:
Someone to tell me what I need to make this work

here is an example of what I am running https://github.com/XziimP/discord-tipbot

**Comment by BluePhoenixGame** [comment]
You see, your problem is that you are not loading the cogs you have created. You can do that by simply loading the extensions.
Here is a snippet from RoboDanny's `__init__`
[Source](https://github.com/Rapptz/RoboDanny/blob/rewrite/bot.py#L83)
```python
for extension in initial_extensions:
    try:
        self.load_extension(extension)
    except Exception as e:
        print(f'Failed to load extension {extension}.', file=sys.stderr)
        traceback.print_exc()
```
Inside your extension the setup function you have created is loading the cog.
NOTE:You'll need to import sys and traceback. Also `initial_extensions` is a tuple defined [here](https://github.com/Rapptz/RoboDanny/blob/rewrite/bot.py#L23)

**Comment by Harmon758** [comment]
There is a reason the issue template for bug reports asks for a full traceback and reproduction steps.
Without the actual code you're running rather than an example, it's impossible to determine what your issue is. You need to provide a reproducible example (MCVE/SSCCE) of what you're trying.

> Almost 80 issues with discord.py this so far not good..

This is not an unreasonable amount of open issues given the popularity of the library and the amount of closed issues, especially since there's a good deal of issues like this one that are just questions or asking for help, rather than issues with the library itself.

@BluePhoenixGame The provided example code loads the extensions in the subclassed `Bot`'s `__init__`, so that shouldn't be the issue.

**Comment by XziimP** [comment]
thank you for your time guys
