### ISSUE TITLE
Bot crashing for no reason?

### ISSUE THREAD

**Issue by 161134050** [Rapptz/discord.py#2448]
### Summary

I noticed my bot was offline, so I checked and it said:
![image](https://user-images.githubusercontent.com/39843740/69508481-d4d98380-0f70-11ea-92d1-879441cbe861.png)

Note where it says Killed, I did not do this manually.

### Reproduction Steps

Run bot
Bot crashes after some time?

### Expected Results

Bot doesn't crash

### Actual Results

Bot crashed

### Checklist

- [x ] I have searched the open issues for duplicates.
- [x ] I have shown the entire traceback, if possible.
- [x ] I have removed my token from display, if visible.

### System Information

- Python v3.7.3-final
- discord.py v1.2.5-final (was actually 1.2.2 at time of crash)
- aiohttp v3.5.4
- websockets v6.0
- system info: Linux 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u5 (2019-08-11)

**Comment by laggycomputer** [comment]
First, you should have enabled debug logging (see the docs) to try to diagnose the error.
Second, this sort of problem belongs in the help channels on the Discord server.
Third, this is likely a bug with the removal of the `animated` attribute of emojis that was fixed in the latest stable release. Please install that version before opening an issue here.

As stated before, this sort of help belongs on the Discord server. For further assistance, kindly reach out there.

**Comment by laggycomputer** [comment]
First, you should have enabled debug logging (see the docs) to try to diagnose the error.
Second, this sort of problem belongs in the help channels on the Discord server.
Third, this is likely a bug with the removal of the `animated` attribute of emojis that was fixed in the latest stable release. Please install that version before opening an issue here.

As stated before, this sort of help belongs on the Discord server. For further assistance, kindly reach out there.

**Comment by Rapptz** [comment]
`Killed` means the linux memory killer killed your process for taking up too much memory. It's off-topic for this issue tracker. Consider getting more RAM or investigating why it's taking up so much memory.
