### ISSUE TITLE
Request to start using anyio

### ISSUE THREAD

**Issue by ShadowJonathan** [Rapptz/discord.py#2472]
### The Problem

Discord.py currently only uses asyncio, one asynchronous library, whereas the python ecosystem currently supports and uses many other kinds of async libraries, like `trio` and `curio`

### The Ideal Solution

Transform all code to follow `anyio`, an abstract high-level library that supports `asyncio`, `trio`, and `curio` as "backends".

### The Current Solution

A faster solution can be to use `trio-asyncio`, a wrapper that converts `asyncio` code into `trio` code.

### Summary

`anyio` provides a high-level abstract layer for any program to start using with their specified or supported async backend, by using this, `discord.py` can suddenly become much more viable as a neutral library that supports many kinds of asynchronous implementations that stem from a "host" library that wants to import and use it.

**Comment by Rapptz** [comment]
As of right now, the effort involved in porting this library to anyio would probably require a complete rewrite due to the following reasons:

1. The usage of very specific asyncio idioms and behaviour that don't make sense in other asynchronous libraries, such as my debugging code for event tasks, utilities that fix the quirks of asyncio, the clean-up code that is mainly for asyncio, the tasks extension, etc.
2. The actual websocket and HTTP request code would have to be dealt with somehow and currently these are facilitated through asyncio libraries, not anyio, curio, or trio libraries.

This code is not trivial to do and quite frankly there are better things that the project can spend time on. Especially when the cons currently outweigh the pros. I'd have to maintain code that should theoretically work in 3 different types of asynchronous environments rather than just dealing with one. Mind you, even dealing with this single environment has gone through significant changes throughout Python 3.4 to Python 3.8 in this library's lifetime. To hope that anyio will bridge any gap and being able to use it within this library seems like a foolish task on my part.
