### ISSUE TITLE
Make bot.run use a different thread

### ISSUE THREAD

**Issue by Jekabs123** [Rapptz/discord.py#2497]
### The Problem

bot.run uses the main thread. If bot.run started the bot in a different thread the main thread would be left free for other things

### The Ideal Solution

I would like `bot.run(...)` to start in a different thread leaving the main thread free for other stuff.

### The Current Solution

At this time for the things I want to do, I can't get it to work.

### Summary

`bot.run()` should leave the main thread free.

**Comment by Rapptz** [comment]
This issue seems to have a fundamental misunderstanding on how asyncio works.

If you want to do something on a separate thread then you are free to encapsulate the entire asyncio portion of program into a separate thread with no issue:

```py
from discord.ext import commands
import threading
import asyncio

class MyBot(commands.Bot):
    async def on_ready(self):
        print(f'Ready {self.user}:{self.user.id}')


def run_bot_in_thread():
    # Important to make an event loop for the new thread
    asyncio.set_event_loop(asyncio.new_event_loop())
    bot = MyBot(command_prefix='!')
    bot.run('token')

threading.Thread(target=run_bot_in_thread, daemon=True).start()

# Something with main thread here
```

Note however that generally *you don't* want to do this. Instead you should do a background task like the [example](https://github.com/Rapptz/discord.py/blob/master/examples/background_task.py). If you go the threading route for whatever reason there are many [gotchas to keep in mind](https://docs.python.org/3/library/asyncio-dev.html#concurrency-and-multithreading).

**Comment by Jekabs123** [comment]
The code you have provided does not work on Python 3.7.4. Is there any way I could make it work on Python 3.7.4?

**Comment by IpProxyNeon** [comment]
@Rapptz sorry to bother you, but for some reason this isn't working in python 3.7.4, is there any other method I am able to use?

**Comment by ChillFish8** [comment]
@IpProxyNeon What is your current code?

**Comment by Rapptz** [comment]
This code works fine. Whatever issue you're having is more than likely irrelevant to that short snippet.
