### ISSUE TITLE
Userid to avatar

### ISSUE THREAD

**Issue by NieR1711** [Rapptz/discord.py#2524]
How can i get mentioned users avatar?
I can get mentioned users uerid but i cant find it how to use like message.author.avatar_url

**Comment by kaylynn234** [comment]
This is not an issue with discord.py.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python.
For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by Harmon758** [comment]
If you're using [the commands extension](https://discordpy.readthedocs.io/en/latest/ext/commands/index.html), you can use a [`MemberConverter`](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.MemberConverter) or [`UserConverter`](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.UserConverter) to get the [`Member`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Member) or [`User`](https://discordpy.readthedocs.io/en/latest/api.html#discord.User) object, respectively. Otherwise, you can use the [`Message.mentions`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Message.mentions) attribute of the [`Message`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Message) object to get a list of the `Member`s that were mentioned in the message.

Otherwise, if you have the user ID already, see the [How do I get a specific model? section of the FAQ in the documentation](https://discordpy.readthedocs.io/en/latest/faq.html#how-do-i-get-a-specific-model).

You can then use the `avatar_url` attribute of the `Member` or `User` object.

As explained, this is not an issue with the library, and for further help, you should join one of the linked servers.

**Comment by NieR1711** [comment]
Oh
