### ISSUE TITLE
discord.ext.commands.command cls attribute

### ISSUE THREAD

**Issue by TrixiS** [Rapptz/discord.py#2527]
### Summary
`cls` attribute of command decorator will be ignored after cog reloading
discord.py version - 1.2.5

I have Command subclass like:
```Python
class EconomyCommand(commands.Command):
    pass
```

Bot subclass like
```Python
class MyBot(commands.AutoShardedBot):

    async def process_commands(self, message):
        ctx = await self.get_context(message)
        if ctx.command is None:
            return
        logging.debug(f"{str(ctx.command)}\n{type(ctx.command).__name__}\n{isinstance(ctx.command, EconomyCommand}")
        await self.invoke(ctx)

    async def on_message(self, message):
        await self.process_commands(message)
```

And balance command like:
```Python
@commands.command(cls=EconomyCommand)
async def balance(self, ctx):
    pass
```

1. Load cog with balance command via `bot.load_extension`
2. Use command and get True of isinstance
3. Reload cog via `bot.reload_extension` (or `bot.unload_extension` and then `bot.load_extension`
4. Use comand ang get False of isinstance

**Comment by XuaTheGrate** [comment]
no repro. ![image](https://cdn.discordapp.com/attachments/336642776609456130/669845059750854666/unknown.png)

**Comment by Rapptz** [comment]
Using something like

```py
from discord.ext import commands

class TestCommand(commands.Command):
    pass

class Test(commands.Cog):
    @commands.command(cls=TestCommand)
    async def test(self, ctx):
        await ctx.send(f'{type(self.test)}, {type(ctx.command)}')

def setup(bot):
    bot.add_cog(Test())
```

the issue could not be reproduced.

This probably needs more info.

**Comment by TrixiS** [comment]
> needs more info

Added some stuff in topic text. So, maybe i just dumb but

I got this before i reload a cog:
```
balance
EconomyCommand
True
```

And this after reloading:
```
balance
EconomyCommand
False
```

Just in case, bot class located in another module separate from Economy Command and cog. Maybe it responsible.

**Comment by Rapptz** [comment]
When you reload the module, the `EconomyCommand` reference type that you store is stale (because it's changing upon reload). To fix this issue you need to move the `EconomyCommand` class elsewhere so when you reload it the reference doesn't change.

Basically:

Before reload your `EconomyCommand` class is the same (we'll say ID 0xdeadbeef).
After you reload the one you have in `bot.py` is still 0xdeadbeef but the one in `economy.py` would be e.g. 0xdeadc0de.

This isn't really an issue with d.py, more so a consequence of how reloading a module works and the caveat of stale references.
