### ISSUE TITLE
ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by Algodlu** [Rapptz/discord.py#2528]
Hi, I’m currently working on a bot for a game(similar to TRPG) on discord. It’s look something like this.

https://paste.pythondiscord.com/inepevuweb.py

but it appears that there's an error and I have no idea how to fix it.

```
await message.channel.send(Item.remove(Item))
ValueError: list.remove(x): x not in list
```

**Comment by Phxntxm** [comment]
A couple things here, that code does not match what's in the paste you provided, your paste has `item.remove` and you have `Item.remove`. Case matters. Second, that error is because you are trying to remove the list from itself, but as the error message says, it does not exist within itself. You need to be removing an actual element of the list.

Regardless, this is not an issue with discord.py.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python.
For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.
