### ISSUE TITLE
Command not found even tough I (believe) think it exists

### ISSUE THREAD

**Issue by juliusjonker** [Rapptz/discord.py#2542]
`
client = commands.Bot(command_prefix='!')

Token = 'A valid token'
@client.event
async def on_ready():
    print('Bot is ready.')

@client.command()
async def dm(ctx):

    embed = discord.Embed(
        title='Doesn't matter',
        description='Doesn't matter',
        colour=discord.Colour.purple()
    )

    embed.set_footer(text='Doesn't matter')
    embed.set_author(name='Fenix Restocks', icon_url='Doesn't matter')
    embed.add_field(name='Link', value='Doesn't matter')

    await ctx.send(embed=embed)

client.run(Token)
`
So when I run this and send the command !dm, it gives the error: 'Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "dm" is not found'

Why does this happen?

Thanks in advance

**Comment by Harmon758** [comment]
Disregarding the improper indentation/formatting, I'm unable to reproduce this.
This code won't even run due to syntax errors with `'Doesn't matter'`, where the string will end after `'Doesn'` and `t matter'` is invalid syntax. You're also missing imports for both `discord` and `commands`.

Even with those issues resolved, the command will successfully be invoked, but raise an `HTTPException` because the `icon_url` is not an actual URL and Discord will return 400 BAD REQUEST.

For further help, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README also links.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
