### ISSUE TITLE
Make description parameter in `@client.commands` accept any type

### ISSUE THREAD

**Issue by IpProxyNeon** [Rapptz/discord.py#2561]
Heya, I have an issue, I'm tryna make it so I can use a dict in the decorator of the command for the description, the reason I am doing this is because I am using another discord bot lib so I can use data and store them in the description, but I cannot do this with a string

The solution is to allow any type in the description parameter in the command, this will give me much more flexibility with my code, thanks for reading this!

**Comment by Vexs** [comment]
Why not store your information somewhere else? Description is intended to be used as, y'know, the description. It's required to be a string so that the help command system works etc. 
Command classes are unslotted and everything too, so there isn't anything stopping you from attaching your dict to it.

**Comment by Rapptz** [comment]
It doesn't really make sense for something intended to be a string to be a dictionary -- how would the library process it? It has default help commands that use it so it needs to be representable and a dictionary is not good information to display to a user.
