### ISSUE TITLE
Custom group subcommands forcing user to pass in ctx argument

### ISSUE THREAD

**Issue by SharpBit** [Rapptz/discord.py#2583]
### Summary

I'm trying to fix some old code someone wrote and came across an issue where subcommands of a group have the usage of `(prefix)cmd subcmd <ctx> <arg>`, 2 arguments that the user needs to pass in instead of 1. He uses custom groups so im not sure if this is a library problem or my problem but I can't seem to find the issue. This issue doesn't happen for regular commands (not part of a command group)

### Reproduction Steps

Custom classes and functions: https://github.com/SharpBit/rainbot/blob/master/ext/command.py
Example of using this: https://github.com/SharpBit/rainbot/blob/master/cogs/setup.py#L179-L200

### Expected Results

- `!!filter add word` should work
- Usage (signature) should be `!!filter add <word>`

### Actual Results

- `!!filter add word` says `word is a required argument that is missing.` (because it thinks word is ctx and that there is another required argument)
- Usage (signature) is actually `!!filter add <ctx> <word>`

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information
- Python v3.7.6-final
- discord.py v1.3.2-final
- aiohttp v3.6.2
- websockets v6.0
- system info: Windows 10 10.0.18362

Edit: 
the clean_params property: https://github.com/Rapptz/discord.py/blob/master/discord/ext/commands/core.py#L561-L578

My code:
```py
params = self.clean_params
print(params)
```

Some examples and their outputs:
```
# definition
async def add(self, ctx, *, word: lower):
# output
OrderedDict([('ctx', <Parameter "ctx">), ('word', <Parameter "word: <function lower at 0x0000016BC90120D8>">)])
# expected output
OrderedDict([('word', <Parameter "word: <function lower at 0x0000016BC90120D8>">)])
```
vs
```
# definition
async def setpermlevel(self, ctx, perm_level: int, *, role: discord.Role):
# output
OrderedDict([('perm_level', <Parameter "perm_level: int">), ('role', <Parameter "role: discord.role.Role">)])
```
Why is the add one not having ctx removed?

**Comment by Harmon758** [comment]
This is because the [overridden `RainGroup.command`](https://github.com/SharpBit/rainbot/blob/2964e2931fdbe36b4fb939ba9026c98ddd754ca1/ext/command.py#L70-L77) does not set the command's `parent` attribute to the `Group` instance when the `Command` is initialized like discord.py does: https://github.com/Rapptz/discord.py/blob/5e6335750819588062790c6b93d604d3bc7c3862/discord/ext/commands/core.py#L1161 This causes the `Cog` to add it as a normal command for the bot rather than as a subcommand of the filter command. You should see that `!!add <word>` works as intended. It also causes the `Cog` initialization not to replace the group command (in this case, the filter command)'s subcommand version of the command: https://github.com/Rapptz/discord.py/blob/5e6335750819588062790c6b93d604d3bc7c3862/discord/ext/commands/cog.py#L180-L186 That means that that version of the command's `cog` attribute is not properly set when the cog is added. Therefore, when it's invoked as a subcommand, it will not pass the instance of the cog: https://github.com/Rapptz/discord.py/blob/5e6335750819588062790c6b93d604d3bc7c3862/discord/ext/commands/core.py#L351-L354 and the context will be passed as `self`.

I would recommend that you use [checks](https://discordpy.readthedocs.io/en/latest/ext/commands/commands.html#checks) for permisisons and [`Command.usage`](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.Command.usage) or a custom [help command](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#help-commands) rather than subclassing `Command` and `Group` for these purposes.
