### ISSUE TITLE
target parameter must be either Member or Role?

### ISSUE THREAD

**Issue by hwahyang1** [Rapptz/discord.py#2592]
### Reproduction Steps

```python
if message.content.lower().startswith("-처리불가"):
        if message.author.guild_permissions.administrator:
            author = message.guild.get_member(int(message.content[9:27])) # It worked successful
            overwrite = discord.PermissionOverwrite(send_messages=False, read_messages=True, send_tts_messages=False, manage_messages=False, embed_links=True, attach_files=True, read_message_history=True, mention_everyone=False, external_emojis=False, use_external_emojis=False, add_reactions=False)
            await message.channel.edit(category=client.get_channel(686877052258746368), topic=str('(처리불가)'))
            await message.channel.set_permissions(author, overwrite=overwrite)
```

### Expected Results

target category permissions changed.

### Actual Results

```
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\SEVER\PycharmProjects\untitled4\bots.py", line 170, in on_message
    await message.channel.set_permissions(author, overwrite=overwrite)
  File "C:\Program Files\Python37\lib\site-packages\discord\abc.py", line 618, in set_permissions
    raise InvalidArgument('target parameter must be either Member or Role')
discord.errors.InvalidArgument: target parameter must be either Member or Role
```

### Checklist

- [ O ] I have searched the open issues for duplicates.
- [ O ] I have shown the entire traceback, if possible.
- [ O ] I have removed my token from display, if visible.

### System Information

Windows 10

Python 3.7.6

Discord.py 1.3.2

**Comment by Harmon758** [comment]
This is likely because `int(message.content[9:27])` does not represent a valid ID for a member of that guild. In that case, [`Guild.get_member`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Guild.get_member) will return `None`, and that error occurs when [`TextChannel.set_permissions`](https://discordpy.readthedocs.io/en/latest/api.html#discord.TextChannel.set_permissions) is passed `None` as `target`.

For further help, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README also links.

I'd also recommend that you look into using [the commands extension](https://discordpy.readthedocs.io/en/latest/ext/commands/index.html).
