### ISSUE TITLE
cannot use from_dict() on my server,but can run on local

### ISSUE THREAD

**Issue by 1599137080** [Rapptz/discord.py#2607]
### Summary

first i need to json.dumps and twice json.loads for a "right" json.
and use from_dict(embed) and still occur json.decoder.JSONDecodeError.
### Reproduction Steps

i need a embed. so i use discord.Embed.from_dict() function.and json.decoder.JSONDecodeError occur.
### Expected Results

no JSONDecodeError
### Actual Results

![image](https://user-images.githubusercontent.com/47945433/77230083-be64d100-6bcc-11ea-9d74-73d47fa466f4.png)

### Checklist

- [x ] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

**Comment by 1599137080** [comment]
![image](https://user-images.githubusercontent.com/47945433/77230345-92e2e600-6bce-11ea-92fa-054fe0bf391a.png)

**Comment by 1599137080** [comment]
![image](https://user-images.githubusercontent.com/47945433/77230377-bc037680-6bce-11ea-9947-8be4c6a6732e.png)

**Comment by J16N** [comment]
`j = json.loads(p)`

That's where to issue is. The JSON object must be str, bytes or bytearray, not dict.

**Comment by 1599137080** [comment]
> `j = json.loads(p)`
> 
> 
> 
> That's where to issue is. The JSON object must be str, bytes or bytearray, not dict.

but when i once loads cannot display any info,only loads twice  can I get the info

**Comment by 1599137080** [comment]
> > `j = json.loads(p)`
> > 
> > 
> > 
> > That's where to issue is. The JSON object must be str, bytes or bytearray, not dict.
> 
> but when i once loads cannot display any info,only loads twice  can I get the info

And once loads(response.text) on server were working before half day ago, when I restarted my server and this Json error occurred

**Comment by J16N** [comment]
Firstly, if you're dumping something in a text file, the extension name would be `.txt`. Secondly, without seeing your whole code and the contents of the `response.txt` file, we don't think we can help you out.

**Comment by 1599137080** [comment]
> Firstly, if you're dumping something in a text file, the extension name would be `.txt`. Secondly, without seeing your whole code and the contents of the `response.txt` file, we don't think we can help you out.

Sorry,sir 
response = request.get(url,headers)
#before
j = json.loads(response.text)
f = discord.Embed.from_dict(j[0][‘embeds’][0])
#these work on my local computer 

#now 
j= json.dumps(response.text)
p=....... up to the jpg

**Comment by bijij** [comment]
If you need more help please join the support server  https://discord.gg/r3sSKJJ

**Comment by 1599137080** [comment]
> If you need more help please join the support server  https://discord.gg/r3sSKJJ 

Thank you sir,already in and I prefer in there

**Comment by SilicalNZ** [comment]
This is ***not*** a matter of preference. 
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python.
Since you are already in the support server, I strongly suggest you use the help that is provided there. Otherwise a close, and a block, will be likely if you continue here.

**Comment by Harmon758** [comment]
As explained, your issue is likely with your usage of [`json.loads`](https://docs.python.org/3/library/json.html#json.loads).
Without clearer reproducible code and steps, as well as what you're trying to accomplish, it's difficult to help you further.

Regardless, this does not seem to be directly related to `Embed.from_dict` and as such, is not an issue with the library, and as mentioned, GitHub issues for this repository should be used to report issues with this library, rather than be used to request help with Python. I would also suggest that for further help, you ask in either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) if you haven't already.

For task list usage, see https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/about-task-lists.
