### ISSUE TITLE
fetch_guild raises AttributeError during http request

### ISSUE THREAD

**Issue by NoahRoseLedesma** [Rapptz/discord.py#2618]
### Summary
I am writing a `commands.check` predicate that looks up a user's role's on a predetermined guild. Calls to `get_guild` return None, so I am trying to use `fetch_guild`. Here are the relevant lines in the traceback:

```
  File "[...]/OH-Bot/cogs/roleManager.py", line 24, in isAdmin
    guild = await client.fetch_guild(DISCORD_GUILD)
  File "[...]/site-packages/discord/client.py", line 1041, in fetch_guild
    data = await self.http.get_guild(guild_id)
  File "[...]/site-packages/discord/http.py", line 165, in request
    async with self.__session.request(method, url, **kwargs) as r:
AttributeError: 'NoneType' object has no attribute 'request'
```

Note, the bot is able to service other commands that don't rely on this predicate. 

### Reproduction Steps

Here is the isAdmin predicate
```
async def isAdmin(ctx: Context) -> bool:
    """
    Checks if the user who sent the command is an admin
    """
    sender = context.author
    roles = None
    if isinstance(sender, User):
        # If the message is a DM, we need to look up the authors roles in the server
        guild = await client.fetch_guild(DISCORD_GUILD)
   ...
```

Here is the command that uses it
```
    @commands.command(aliases=["dequeue", 'dq'])
    @commands.check(isAdmin)
    async def dequeueStudent(self, context: Context):
        ...
```

I tried adding the following line right before the call to fetch_guild.
```
client.http.__session = aiohttp.ClientSession(connector=client.connector)
```
What is strange is that when I did this, my debugger would show that __session is not None. However, the same AttributeError was raised.

### Expected Results

I expect that the fetch will succeed and guild will be set. Or, I expect a discord error to be raised

### Actual Results

An attribute error is raised. client.http.__session is None

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

discord.py v1.3.2-final

**Comment by Rapptz** [comment]
The internal session is `None` when the client has not been logged in.

I'm willing to bet that somewhere in that code you're creating a fresh `discord.Client` or `commands.Bot` and using that instance instead of the one that's logged in.

Note that inside checks you can use `ctx.bot` as an attribute instead of a global `client` object. Also note that using `get_guild` is better than `fetch_guild` since it doesn't go through the HTTP layer and just uses the cache.

**Comment by NoahRoseLedesma** [comment]
I have determined that this error was due to importing the client instance from my main file. The file containing `isAdmin` is roleManager.py which is a cog. Using the client instance that was passed in through the cog setup function works.

However, this functionality was very non-intuitive. It's not clear to me why the instance of the client imported from main is unusable, but if there can be an error for this case, that would be helpful.

**Comment by NoahRoseLedesma** [comment]
@Rapptz get_guild was returning None, which I assume meant that the guild was not in the cache. Is the preferred way of doing things to check the result of get_guild and do the API call if the cache was empty?

**Comment by Rapptz** [comment]
Generally speaking globals are frowned upon since it makes it hard to reason with the entire state of the program.

That aside, I've already mentioned the cause -- which also explains why `get_guild` returns `None`, you're not logged in. A common mistake is mixing `commands.Bot` and `discord.Client` (the `Bot` inherits from `Client` so it has all of its features).
