### ISSUE TITLE
'Client' object has no attribute 'create_message'

### ISSUE THREAD

**Issue by Loneliness2** [Rapptz/discord.py#2624]
today i testing my music bot and have seen an error: "AttributeError: 'Client' object has no attribute 'create_message'". This artefact on Linux Mint, on Windows i don't found this error. pls fix
installed by 'python3.7 -m pip install discord.py[voice]==1.3.2'

**Comment by Loneliness2** [comment]
in 'iterators.py' 2 lines is 298 and 319

**Comment by Vexs** [comment]
This error would be much more actionable with a complete traceback, as well as relevant code. 
Client objects, indeed, do not have a create_message method- one of the few ways I can think of this happening is if you were creating an iterator incorrectly.

**Comment by laggycomputer** [comment]
Queries like this one are answered on the [support server](https://discord.gg/dpy), not on GitHub issues.

You are incorrectly using old, version 0.16.x functionality for this library. Please see the [migrating to version 1.x guide](https://discordpy.readthedocs.io/en/latest/migrating.html) and the documentation for [`abc.Messagable.send`](https://discordpy.readthedocs.io/en/latest/api.html#discord.abc.Messageable.send), the replacement to `Client.send_message` (which you mistakenly tried to call as `create_message`).

Also, try to use the issue template when posting issues, which would have you send relevant code, a traceback, and system info so that we can actually help you.

**Comment by Loneliness2** [comment]
closed, my issue
