### ISSUE TITLE
How to join server using slefbot?

### ISSUE THREAD

**Issue by Squuv** [Rapptz/discord.py#2633]
I want to join a server using discord.py I am using a Normal account token.

I tried this but returns error :

>   File "bot.py", line 94, in join
>     await client.accept_invite(mahlink)
> AttributeError: 'Bot' object has no attribute 'accept_invite'

```
@client.command()
async def join(mahlink):
    await client.accept_invite(mahlink)
```

**Comment by Vexs** [comment]
The accept_invite function has been removed since discord stopped selfbots from using it (without additional trickery). Further, discord has added some more blockages that prevent discord.py from being used for selfbots at all since then, so presently all selfbot functionality is broken without library modification.

I'd be amiss if I didn't mention selfbotting is not something discord wants you doing, and joining servers with a selfbot is *extra* discord does-not-want.

**Comment by Squuv** [comment]
I am Just testing something but I know some people who they can control self bots to join a server.. how?

**Comment by Vexs** [comment]
That would be the aforementioned additional trickery
