### ISSUE TITLE
on_socket_response receives non-raw data

### ISSUE THREAD

**Issue by Rapptz** [Rapptz/discord.py#323]
A reminder for Fuyu's issue.

Due to internally using the `msg` dict and modifying it, passing it to `on_socket_response` causes it to use the final version of the data instead of the one at the point of calling. Clearly it needs to be copied or something.

**Comment by Hornwitser** [comment]
May I suggest moving `socket_raw_receive` to after decompressing and removing `socket_response`?  Unless you're trying to debug the compressed data stream, getting compressed bytes is just annoying.  Existing code would then change
```py
async def on_socket_response(msg):
    ...
```
To
```py
async def on_socket_raw_receive(msg):
    msg = json.loads(msg)
    ...
```

The performance implications aren't that bad, I benchmarked this and found a 4% speedup due to dropping one dispatch call (yes, dispatch is that expensive) and 10% slowdown due to double decoding the json.  If using ujson instead of json in the event handler the total slowdown becomes less than 2%.
