### ISSUE TITLE
[suggestion] Return the server joined when `accept_invite` is called

### ISSUE THREAD

**Issue by ButterCheezii** [Rapptz/discord.py#371]
I would like this snippet to work:

```py
server = await bot.accept_invite(invite)
# do stuff with server
```

Is that possible?

**Comment by Phxntxm** [comment]
Not for bots, bots cannot use this.

**Comment by ButterCheezii** [comment]
Userbot.

**Comment by Helehelehele** [comment]
Discord API does not return a guild (server) object after accepting an invite (see [here](https://github.com/hammerandchisel/discord-api-docs/blob/21168c18f4488438a734698fb3a856eaf21a616f/docs/resources/Invite.md#accept-invite--post-invitesinvitecodedocs_inviteinvite-object)). However, you can use [`discord.Client.get_invite`](http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.get_invite) in order to get a [`discord.Invite`](http://discordpy.readthedocs.io/en/latest/api.html#discord.Invite) object which has a `server` attribute.
