### ISSUE TITLE
Long delay when doing multithreading with event loop from discord

### ISSUE THREAD

**Issue by milandamen** [Rapptz/discord.py#403]
I have discord.py running on the main thread and when I execute `send_my_message` from a different thread it takes between 9 and 41 seconds for the event loop to call `send_my_message_async`.

Inside my class:

    def send_my_message(self, message):
        global client
        client.loop.create_task(send_my_message_async(message))

Outside my class:

    async def send_my_message_async(message):
        await client.send_message(channel, message.strip())

Note that the client is already connected and logged in to Discord when `send_my_message` gets executed.

Is there a way to get it below 1 second?

Thank you in advance.

**Comment by SunDwarf** [comment]
First, if you want to run `send_my_message_async` from a different thread, you need to use `asyncio.run_coroutine_threadsafe(send_my_message_async(message), client.loop)`.

https://docs.python.org/3/library/asyncio-task.html#asyncio.run_coroutine_threadsafe

Also, there's a high chance you have many blocking operations happening in your main thread that are causing it to lag, otherwise due to the constant context switching your task should be ran very quickly.

**Comment by milandamen** [comment]
It works now, thank you!
