### ISSUE TITLE
The method "client.get_user(uid)" isn't working

### ISSUE THREAD

**Issue by LeonidMem** [Rapptz/discord.py#4035]
I was trying to send direct message and to do this I need to get user by his ID which I should write in a message
This code I got from this FAQ: [https://discordpy.readthedocs.io/en/latest/faq.html#how-do-i-send-a-dm](url)

Here's my code:
import discord
import asyncio

bot = commands.Bot(command_prefix='!')
client = discord.Client()

@bot.event
async def on_message(message):
  usid = 487994985942089738
  user = client.get_user(usid)
  await user.send('Hi!')

Error:
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\hidden\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "hidden", line 115, in on_message
    await user.send('Hi!')
AttributeError: 'NoneType' object has no attribute 'send'

Does anybody know how to solve this problem?

**Comment by WildHS** [comment]
> Does your bot shares a server with the user in question ? If that's not the case, it's not a problem with the lib, as you can't get an user from the cache if you don't have it in cache. You _could_ use fetch_user, but you wouldn't be able to send a DM to it anyway.

And what I need to do to have an ability of sending DM?

**Comment by Phxntxm** [comment]
Share a server. It is the same concept as normal users sending DMs to others, in order to be able to send a DM to someone you need to share a server or be friends with them. Since bots cannot have friends, the only option you have is to share a server with the person you want to DM

**Comment by WildHS** [comment]
> Share a server. It is the same concept as normal users sending DMs to others, in order to be able to send a DM to someone you need to share a server or be friends with them. Since bots cannot have friends, the only option you have is to share a server with the person you want to DM

When I'm trying to write DM to my friend by using bot (he can get message from unknown users with same servers) I get error, which was mentioned earlier.

**Comment by Phxntxm** [comment]
The reason you cannot find your user is you are using the wrong client to search. You have both a `discord.Client` and a `commands.Bot` instance, and it's clear that you're logging in with the `Bot` one since that is what the event is attached to. By trying to then grab the user from the `client` instance you are trying to pull it from an instance that has not logged in yet. 

In short, you should not be creating two instances of a client/bot, you should only be using one. If you're going to use the commands extension then you you should just use `commands.Bot`

As a secondary note, this is not an issue with discord.py.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python.
For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by Harmon758** [comment]
As explained, this is an issue with your client/bot instantiation, rather than an issue with discord.py, and for future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README also links.

For code block usage, see https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks.
