### ISSUE TITLE
Userconverter not using fetch_user if user is uncached

### ISSUE THREAD

**Issue by NatsumiHB** [Rapptz/discord.py#4045]
### The Problem

Using `discord.User` to convert in a function signature only works with cached users. 

### The Ideal Solution

Doing something like
 ```py
if match is not None:
    user_id = int(match.group(1))
    result = ctx.bot.get_user(user_id) or _utils_get(ctx.message.mentions, id=user_id)
    if result is None:
        result = await ctx.bot.fetch_user(user_id)
```

in the user converter in order to fetch a user if they aren't cached.

### The Current Solution

Only attempting `get_user` in the converter.

### Summary

Please make the userconverter fetch the user if the user is not cached.

I have provided the needed code changes. However, I am not experienced enough to write a pull request for my issue yet.

**Comment by SebbyLaw** [comment]
The reason this isn't done in the library is because the library converters are designed to only be simple cache lookups. If fetch methods were used, you'd have to handle potential HTTP exceptions even when there is no HTTP request made. The two types also aren't even one to one, and don't necessarily return exactly the same object, e.g. `fetch_guild`, `fetch_invite`, etc. You can simply handle and use them yourself or subclass your own method, something that R. Danny [does](https://github.com/Rapptz/RoboDanny/blob/f8c7aa74a09889060099c00c7c0a6f6f55161fc4/cogs/meta.py#L21-L30).

**Comment by Phxntxm** [comment]
> The reason this isn't done in the library is because the library converters are designed to only be simple cache lookups.

Fetch is used for both the message and the invite converters.

**Comment by NatsumiHB** [comment]
I've decided to write my own converter when I'm not lazy for once.
Thanks for the explanation @SebbyLaw!
