### ISSUE TITLE
member_descriptor object is not callable

### ISSUE THREAD

**Issue by BlackDrakonian670** [Rapptz/discord.py#4061]
I have been having this error (look at the title) i am new to python so if you answer please leave the exact way i should type it, along with the theory of why it didn't work.

My code:

    @commands.command()
    @commands.has_role("BotMaster")
    async def slowmode(self,ctx, channel : discord.TextChannel, amount):
        ctx.guild.get_channel(discord.TextChannel)
        await discord.TextChannel.slowmode_delay(limit=amount)
        await ctx.send(f'Slowmode activated. Delay: {amount} seconds.')

**Comment by webkaiyo** [comment]
GitHub issues for this repository should be used to report issues with this library. For further help specific to using this library, you should join the [official discord.py server](https://discord.gg/dpy).

**Comment by Harmon758** [comment]
You're attempting to pass the [`TextChannel`](https://discordpy.readthedocs.io/en/latest/api.html#discord.TextChannel) class itself to `get_channel` rather than the instance of it, `channel`. Regardless, [`Guild.get_channel`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Guild.get_channel) accepts an integer `channel_id`, and you already have an instance of the channel itself.
Similarly, you're subsequently attempting to again use the class itself as an instance and the [`TextChannel.slowmode_delay`](https://discordpy.readthedocs.io/en/latest/api.html#discord.TextChannel.slowmode_delay) attribute as a method. You're probably wanting to use [`TextChannel.edit`](https://discordpy.readthedocs.io/en/latest/api.html#discord.TextChannel.edit) instead.

As explained though, this is not an issue with discord.py; GitHub issues for this repository should be used to report issues with the library itself, rather than for requesting help with Python or using the library; and for future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README also links.
