### ISSUE TITLE
on_member_join add role error

### ISSUE THREAD

**Issue by YECHEZ** [Rapptz/discord.py#4094]
### Summary
Since yesterday, ceased to be given a role in on_member_join

### Reproduction Steps
Add this code in on_member_join
```
role = member.guild.get_role(ROLE_ID)
await member.add_roles(role)
```

### Expected Results
When a new member enters the guild he gets the role

### Actual Results
Member does not get the role.
Error lines:
```
role = member.guild.get_role(ROLE_ID)
await member.add_roles(role)
```
Error message:

'str' object has no attribute 'id'

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

Current Discord.py Version: 1.3.3
Current Python Version: 3.7.3

**Comment by Taarek** [comment]
Can you show the entire code? It sounds like you're shadowing variables. That error only happens if ``role`` is a string instead of a ``Role`` object.

**Comment by Vexs** [comment]
`get_role` will always return None or a role object, and will never return a string- further, it doesn't ever attempt to access an ID attribute.
`add_roles` will raise this error if passed a string, but since `role` can never be a string given this code, that means that this code, under any and all circumstances, can't and will never produce this particular error.

Please provide the entire traceback, as well as all code related to this function- but not here! GitHub issues for this repository should be used to report issues with this library.
For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by YECHEZ** [comment]
Yesterday discord release new guild preview feature. I think it's related because my code worked before without errors.
Same i see in on_message callback with role and same in on_member_update

**Comment by YECHEZ** [comment]
UPD. Works but seems discord api has latency on add roles. I tested and can get role after 2-3 mins. Weird
