### ISSUE TITLE
How to get a list of all direct messages a bot is part of

### ISSUE THREAD

**Issue by LinuxRocks2000** [Rapptz/discord.py#4118]
I know that discord.py allows bots to be part of a DM, and I know that I can record DM's using a list, but what about getting a list of dms that the bot is already part of? E.g, after a restart with no saved data.

**Comment by Phxntxm** [comment]
This is a hard concept to pull off unless **you** track this information, think about this from a normal user perspective. You DM someone, you close that DM (the x next to the person's name) and it's now gone from your list. How do you look somewhere to see **everyone** you've DM'd now? The list is missing that channel, it's gone, the only way you know that you're missing one from that list is because well, you already know. You have that precursor knowledge to let you know there's a channel missing from that list.

The same concept applies here, DM channels close, which is why the library gives you `Member.send` to facilitate the recreating of DM channels without you having to worry about that slightly weird concept. Due to this the only realistic way of knowing this information is if **you** tracked every message sent that is a DM and store that in a database. Then you can check your own table of users that have DM'd you for this information.

**Comment by Rapptz** [comment]
Discord does not provide this information so you can't get it. There's [`Client.private_channels`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.private_channels) which is a populated LRU cache of the DM channels you get as the bot is communicating. That's the best you'll get.
