### ISSUE TITLE
Say command

### ISSUE THREAD

**Issue by Adaptified** [Rapptz/discord.py#486]
I have created this command

@bot.command()
async def say(self):
    """Makes me say something :eyes:"""
    await bot.say(content)

Any help?

all I get is blank and no reply from bot if I do 
!say hi

**Comment by Repulser** [comment]
Is that in a class? If so you need to use @commands.command
and you passed self wich is for when you use a class.

Heres an example for code that is in the main script:
```@bot.command()
async def say(content):
"""Makes me say something 👀"""
await bot.say(content)```

In a class:
```@commands.command()
async def say(self, content):
"""Makes me say something 👀"""
await self.bot.say(content)```

**Comment by Adaptified** [comment]
Thanks, Do you know how to setup permissions for commands?

**Comment by NotSoSuper** [comment]
You can view an example at
https://github.com/Rapptz/RoboDanny/blob/master/cogs/utils/checks.py

You'd need to import that module and use the functions as a decorator
bellow (or etc) the @commands.command as @checks.is_owner() or other
checks. The bot also has some inbuilt checks in the commands extension.

On Feb 16, 2017 7:21 AM, "Jake Stanley" <notifications@github.com> wrote:

Thanks, Do you know how to setup permissions for commands?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Rapptz/discord.py/issues/486#issuecomment-280316411>,
or mute the thread

**Comment by Phxntxm** [comment]
Ignoring the other replies, the main issue is your `content` variable doesn't exist. Plus, it doesn't look like you're in a class, so you don't need self

Change this:
async def say(self):
To this:
async def say(*, content):

**Comment by OMGWowf** [comment]
> Thanks, Do you know how to setup permissions for commands?

after async def write 
    if (not ctx.author.guild_permissions.the permission name):
        await ctx.send('This command requires ``permission name`` permission!')
