### ISSUE TITLE
Weird Errors when executing commands.

### ISSUE THREAD

**Issue by Adaptified** [Rapptz/discord.py#488]
Code:
 - http://pastebin.com/raw/GUpQZrKL

Errors:
 - http://pastebin.com/raw/6TMxYtPh

**Comment by leovoel** [comment]
doesn't look like these commands are defined inside a class, so the use of `self` is your issue here

**Comment by Repulser** [comment]
or if it is in a class you should use ```python@commands.command()
```
Instead of @bot.command()

**Comment by Adaptified** [comment]
what do you mean inside a class?

**Comment by Repulser** [comment]
https://docs.python.org/3/tutorial/classes.html

In your code it seems that you arent using a class, try removing the self parameter.

For example:
Replace:
```async def ban(self, ctx, user:discord.Member, *, reason:str=None):```
With
```async def ban(ctx, user:discord.Member, *, reason:str=None):```

**Comment by Adaptified** [comment]
I get the same error

**Comment by Repulser** [comment]
I tested the kick command without self and it works perfectly, only issue i found is on this line:
```
await self.bot.kick(user)
```
Since self is not defined (you should be using bot and not self.bot)

This function worked properly:
```
@bot.command(pass_context=True)
@checks.is_owner()
async def kick(ctx, user:discord.Member, *, reason:str=None):
    """Kicks someone from the server"""
    if reason is None:
        reason = "The ban hammer has spoken."
        try:
            await bot.kick(user)
        except discord.errors.Forbidden:
                await bot.say("Either I do no have permission, or you do not")
                return```

**Comment by Adaptified** [comment]
ive put it into a folder and done all that
but
I get on @bot.event it says bot is not defined

**Comment by Repulser** [comment]
If you put it in a class you dont use @bot.event
And you need to load that class as a "cog"

Stick with the main script if you dont understand what that means.... 
The main issue with the code you linked above is that you passed self as a parameter, just remove self from all the functions and it should work properly...

**Comment by Adaptified** [comment]
can u help me? Like give me a main.py

**Comment by Rapptz** [comment]
For future reference, please use the discord guild to receive help. It's better than Github Issues for things like these because you don't spam everyone's emails with your question.

My advice is to not copy paste code from somewhere else and expect it to work as-is. You should understand how the code works before you copy it (and modify it). Otherwise you're going to be confused as you are right now.

The `commands.command` decorator is used to create a `Command` instance. The `bot.command` decorator is a shortcut to create the `Command` instance and then add it to the bot's command list. The `commands.command` decorator is frequently used when implementing something used 'cogs'. Which are a Python class that is composed of different commands for categorisation of state.

Since you clearly don't know enough Python to know what a class is (or what a cog is) this information would probably be better suited by learning the language. I recommend [this tutorial](http://python.swaroopch.com/).

Please take any further questions to the guild instead.
