### ISSUE TITLE
User as Channel inconsistency in send_message vs wait_for_message

### ISSUE THREAD

**Issue by WayoshiM** [Rapptz/discord.py#489]
For `send_message`, you are allowed to pass in a `User` for `destination` and have it interpreted as a `PrivateChannel` between that user and the client automatically. However for `wait_for_message`, you pass in a `User` for the `channel` parameter and it will hang forever - you must pass in the `PrivateChannel` to match.

It would be nice if the same interpretation of a `User` in `send_message` also applied to `wait_for_message`.

**Comment by Rapptz** [comment]
This isn't really possible. 

`send_message` taking a `User` is merely a convenience thing. Behind the scenes it can potentially call a coroutine (`start_private_message`) and then uses that `PrivateChannel` that we created behind the scenes. In the predicate we cannot call the coroutine.

Since this is an X/Y problem, you can solve this differently. e.g. `wait_for_message(author=user, check=lambda m: m.channel.is_private)`.

**Comment by WayoshiM** [comment]
I figured there was a reason, still wanted to bring it up, Thanks!
