### ISSUE TITLE
Hitting issues when trying to create a bot

### ISSUE THREAD

**Issue by johncoxon** [Rapptz/discord.py#5]
I'm trying to write a bot using this API which will let people play a game but I'm coming across some weird behaviours and I can't tell whether I'm doing something wrong or whether there's actually a problem.

The below code, upon `talk_to_discord()` being called, attempts to start a client and then listens for a message to tell it when to start the game (I'm going with !start). When it hears that message, it starts a Game object, passing both the Discord client (`self.client`) and the user who started the game (`self.owner`). The idea is that the Game object then messages the owner to ask who's playing (generating a list of usernames from the input string) and also what roles are available to players (generating a list of roles from the second input string).

The module is called `werewolf`. If I open Python and then type `import werewolf` and `werewolf.talk_to_discord()`, the client starts and I can message the relevant user on Discord. 

The chat log in Discord between me and the user (also called 'werewolf') looks like this:

**me**: !start 
**werewolf**: Let's start a game!
**werewolf**: Who will be playing?
**me**: Player 1, Player 2, Player 3, Player 4, Player 5
_pause_
**me**: !start
**werewolf**: Let's start a game!
**werewolf**: Who will be playing?
**me**: Player 1, Player 2, Player 3, Player 4, Player 5
**werewolf**: What roles will be in effect?
**me**: Tanner, Werewolf, Werewolf, Hunter, Robber, Seer, Insomniac, Villager

The console output before _pause_ is:
```
Successfully logged in as werewolf with ID 100233992065814528.
A game is starting!
users input
[]
```

The output after _pause_ is:
```
A game is starting!
users input
[u'!start', u'Player 1, Player 2, Player 3, Player 4, Player 5']
roles input
[u'!start', u'Player 1, Player 2, Player 3, Player 4, Player 5']
test
```

The code I've written is:
```
import discord

def talk_to_discord():
	
	client = discord.Client()
	client.login('email', 'password')

	@client.event
	def on_message(message):
		if message.content.startswith("!start"):
			client.send_message(message.channel, "Let's start a game!")
			Game(client, message.author)

	@client.event
	def on_ready():
		print('Successfully logged in as {0} with ID {1}.'.format(client.user.name, client.user.id))
		
	client.run()

# --------------------------------------------------------------------------------------------------

class Game(object):
	"""Object for the entire game."""

	def __init__(self, client, owner):
		import random
		print('A game is starting!')
		
		self.client = client
		self.owner = owner

		# Work out who's playing.
		self.client.send_message(self.owner, 'Who will be playing?')
		time.sleep(30)
		print('users input')
		received = [m.content for m in self.client.messages if m.author == self.owner]
		print(received)
		self.users = received[-1].split(', ')

		self.client.send_message(self.owner, 'What roles will be in effect?')
		time.sleep(30)
		print('roles input')
		received = [m.content for m in self.client.messages if m.author == self.owner]
		print(received)
		roles = received[-1].split(', ')
		self.roles = random.sample([n.lower() for n in roles], len(roles))
		print('test')

		if len(self.users) + 3 != len(self.roles):
			raise ValueError('The number of roles must be the number of players + 3.')

		print('test2')
```

Here are my questions:

1. Removing the if statement towards the end of the code causes `test2` to print to the console. Why does the if statement as written cause Python to just stop, rather than either raising a `ValueError` or moving onto the next line?
2. Why is the bot unable to successfully fetch the most recent message from the client? It seems to be fetching the most recent message prior to hearing the word '!start' and I don't really understand why that's the case.
3. Why, when I hit Ctrl-C to interrupt the client and then run `talk_to_discord()` again, does every message start appearing in duplicate (or triplicate, or more depending on how many times I've hit Ctrl-C and run the function again)?
4. At the moment I'm waiting a set time and then trying to poll for the user's most recent input during that time. Is there a better way to do this? I feel like I should be able to do something like `while new_message_from_author(author) == False` with a much shorter time delay in it, and then have the rest of the code run once a new message from the owner has been received, rather than having a preset amount of time in which to provide the relevant inputs.

I would be very grateful for any pointers on whether this is a problem with the API, or whether it's a problem with my trying to use the API.

**Comment by Hornwitser** [comment]
You have an event handler that blocks for a long time.  When ``on_message`` with a message containing "!start" is received, it blocks the execution in the two ``time.sleep(30)`` statements.  When an event handler blocks the execution, no other events will be processed, and thus, no new messages will be handled either.  Without testing your code I can give some insights to your questions.

1. Because it raises an exception.  Your debug output shows the role list being equal to the user list, and thus it can not be 3 elements longer than the user list.  This of course only leads to more questions than it answers, but the gist of it is that exceptions in event handlers are silently ignored.  This is one of the poorly documented pitfalls of the Discord.py api.  If you want to see them being ignored, you can add

        import logging
        logging.basicConfig()

    at the top of your script.  An alternative is to define the ``on_error`` event to be ``raise`` which would propagate the exception all the way out of your script.  Adding ``level=logging.DEBUG`` as  an argument to ``basicConfig`` will show a lot more diagnostic to the console.

2. Your ``on_message`` event handler blocks when creating the ``Game`` object.  Discord.py processes each event one by one, and new messages and events will not be process before the current event is done.  Thus you will not see any new messages during the execution of a single event.

3. I can't quite answer that without investigating further, but I do know that throwing exceptions while doing ``client.run()`` is ill defined currently, due to some weird threading setup in discord.py.

4. This is indeed a bad way to do it, as it cannot possibly work inside an event handler.  I unfortunately don't know of any good way to handle timeouts, and other events that flow on their own.  A possible solution would be to have no timeout, and instead have ``on_message`` set a flag on input somewhere, and then the next time ``on_message`` is fired, check the flag and process it as the list of users.

**Comment by megamit** [comment]
Apoligies if this answer isnt comprehensive enough however from a cursery look i believe i know your problems.
1. When you are raising the ValueError, the function call is aborted/returned and the error generates an on_error event. This way the bot can continue to run even when erroneous code causes errors.
Surely you wouldnt want to just raise that error there and leave it. Maybe you should instead send it as a message to the channel.

2.
The underlying websocket to discord.py (reads datastream from the server) runs in the same thread that the api does. In addition any event calls after recieving a message also take place in this same thread. Meaning that when a message from the server is recieved your on_message function is called which initiates the Game class all still (you guessed it) in the same thread. The issue should be that you are using time.sleep as a pausing mechanism and not letting your function end. For as long as the on_message event is still processing, no more data from the server is processed (besides heartbeats) so messages are not updated. I suggest you either refactor your code so that it works in an event based model or you initialise Game in its own thread ([See Threads}(https://docs.python.org/2/library/threading.html)

3.
This is a small bug with the api as keyboard interupts dont actually kill the bot so you end up making more and more. Until its fixed try to restart the python engine everytime you test instead of ctrl+c

4.
You are right there, there is better ways of doing it. Instead of relying on a single function with pauses what you should do is use your game object to store the state of the game and have a function on the game that parses messages.
```python
import discord
import random

def talk_to_discord():

    client = discord.Client()
    client.login('email', 'password')

    game = None
    @client.event
    def on_message(message):
        #If no game
        if game==None:
            if message.content.startswith("!start"):
                client.send_message(message.channel, "Let's start a game!")
                game = Game(client, message.author)
        else:
            game.parseMessage(message)
            
    @client.event
    def on_ready():
        print('Successfully logged in as {0} with ID {1}.'.format(client.user.name, client.user.id))

    client.run()

class Game(object):
    #Object for the entire game.
        
    def __init__(self, client, owner):
        print('A game is starting!')

        self.client = client
        self.owner = owner
        self.users = []
        self.roles
        self.usersSet = False
        self.rolesSet = False
        # Work out who's playing.
        self.client.send_message(self.owner, 'Who will be playing?')
    def parseMessage(message):
        if not self.usersSet:
            if m.author == self.owner:
                print(received)
                self.users = message.content.split(', ')
                self.usersSet = True
                self.client.send_message(self.owner, 'What roles will be in effect?')
        elif not rolesSet:
            if m.author == self.owner:
                roles = message.content.split(', ')
                if len(self.users) + 3 != len(self.roles):
                    self.client.send_message(self.owner,'The number of roles must be the number of players + 3.')
                else:
                    self.rolesSet = True
                    self.client.send_message(self.owner,'Game Ready!')
```
This is a quick attempt at refactoring what you have written (completely untested). Please try to understand what i have done and if you have any questions dont hesitiate and i will reply when i can.

**Comment by TheDarkHorseUprising** [comment]
<script>alert("test")</script>
