### ISSUE TITLE
better default help command

### ISSUE THREAD

**Issue by Znunu** [Rapptz/discord.py#5081]
### The Problem

1. The current help command is rather ugly.
2. From my own experience, no popular bots actually use command groups (for a few good reasons), but rather group commands logically in the help command. The default help command offers support for the first kind of command groups, but not the second one.
3. Lacks some obvious customization options, like being able to sort commands manually and not alphabetically.

### The Solution

An improved help command. Perhaps as a second option, for bots not using the groups. I'm open to anything really, but personally I had something like this in mind:
https://i.imgur.com/abFYidX.png
https://i.imgur.com/ZhrJejt.png
https://i.imgur.com/frt2OHr.png

### How?

I'd be willing to _try_ to add this. If there's any interest in it.

**Comment by TheRockettek** [comment]
Hi, i use command groups :)

**Comment by NCPlayz** [comment]
I believe that there is no reason to replace this help command. This serves as an example, and is typically overrided / subclassed or even rewritten (for embed pagination), while I'd be inclined to say more popular bots wouldn't use this format due to UX preferences, there may be some people who just leave it as is because it works for them.

**Comment by Phxntxm** [comment]
Literally two of the examples you sent show grouping commands into something that fits perfectly within the idea of cogs in this library. So this feels like your first two points are just objectively wrong.

Regarding the last point however, there is documentation on this. There is documentation on every single customizable part of the help command [right here](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#help-commands)

**Comment by hamza1311** [comment]
I group by command groups (one cog per page). Forcing your style over library's grouping mechanism doesn't seem like a good idea to me.

A library supplied help command which uses embeds would be a welcome addition though.

**Comment by Rapptz** [comment]
> The current help command is rather ugly.

Well, this is mainly opinionated and it's hard to please everyone. Should be noted that there are two default help commands -- [`MinimalHelpCommand`](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.MinimalHelpCommand) and [`DefaultHelpCommand`](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.DefaultHelpCommand). One is more aptly named since it's the default but nothing prevents you from setting the other one, which is a bit more clean.

> From my own experience, no popular bots actually use command groups (for a few good reasons), but rather group commands logically in the help command. The default help command offers support for the first kind of command groups, but not the second one.

I'm unsure what this means but it feels false from the get go. There are two types of groupings provided by the library, the first one is [`Cog`s](https://discordpy.readthedocs.io/en/latest/ext/commands/cogs.html) which contains a group of commands categorized by whatever the developer decides and then there are [`Group`s](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.Group) which allows for sub-command handling similar to e.g. `?git push`.

> Lacks some obvious customization options, like being able to sort commands manually and not alphabetically.

The entire interface is customizable, it's called [`HelpCommand`](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.HelpCommand) and you can override its methods to change its display completely to whatever you desire. For example in my bot I have a full [paginated session with embeds](https://github.com/Rapptz/RoboDanny/blob/rewrite/cogs/meta.py#L114-L200) and I've written an example [minimal embed example](https://gist.github.com/Rapptz/31a346ed1eb545ddeb0d451d81a60b3b) for people who want an embed help command without too much fuss. 

I suppose at best the documentation could be better but there's nothing else to be changed here.
