### ISSUE TITLE
Bot execution stops occurring after running client.run(token)

### ISSUE THREAD

**Issue by 1byte2bytes** [Rapptz/discord.py#528]
Hi! I've been trying to wrap my head around a strange bug in my bot for the past few days and discovered that it seems to be a problem with Discord.py? I had made some [potentially breaking changes](https://github.com/StarbotDiscord/Starbot/blob/master/main.py#L60) so I reverted back to a state [that has worked before.](https://github.com/StarbotDiscord/Starbot/blob/8ce016fbe33b3420af08fd834f358144c4286d4f/main.py#L164)

This afternoon I opened up PyCharm 2017.1 and set a breakpoint for the highlighted line in both, and ran using the debugger. Sure enough, they both go to that line, I step over... and nothing. Okay, so let's just let it run. Maybe this is normal behavior? There are zero threads being executed, seemingly not a thing. But okay. I run a command... nothing. No threads appear, nothing is called... the interpreter is still running but seemingly nothing is being executed. 

This was executed most recently with
```
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
```
which ships with Xubuntu 17.04 Zesty Zapus Beta 2, however it occurs on Windows with Python 3.5.2

**Comment by 1byte2bytes** [comment]
I forgot to add that I am using the pip installed Discord.py 0.16.7

**Comment by Rapptz** [comment]
As per [the documentation](http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.run)...

There's a big warning:

![](http://i.imgur.com/NfkP1O3.png)

That's what 'blocking' means. It blocks until your bot logs off. If you want better control of the event loop use the lower level primitives ([`login`](http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.login) and [`connect`](http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.connect), see the docs for those.)

**Comment by 1byte2bytes** [comment]
It still does not execute anything after a certain point. Please read the ticket, **nothing** executes after. The main thread seems to end, which would lead me to believe that Discord.py isn't even listening to Discord. Also, there is no intake of inbound traffic, and the on_ready function Discord.py provides is never called either.

**Comment by 1byte2bytes** [comment]
And no, the console does not provide any errors, warnings, or any information at all about what could have happened. This happens inside or outside the debugger, and I have made sure the execution is not paused while using the debugger.

**Comment by 1byte2bytes** [comment]
Watching the process for the bot while it's running outside of the debugger so I can't have it accidentally paused, the Python process the bot is on does not use any CPU time after that function regardless of if commands are called or not. It should be using CPU time anyway to process at least the heartbeats Discord's API requires.

**Comment by 1byte2bytes** [comment]
As suspected, watching the working copy on my server the CPU time does go up, however with the updated copy on my local machine (and my Windows machine) we are lacking 4 threads in the task manager or htop and the CPU time is not going up. The bot doesn't spawn any threads by itself, this would all be the doing of external modules.

**Comment by Rapptz** [comment]
You have a debugger set up. When a debugger hits a **breakpoint** it also halts all execution. That's what a debugger does. You can't 'step over' the `run` function because, like I said, it's blocking. 

Fundamentally speaking your woes with your debugger are completely irrelevant to the code you posted. Nothing will run after that `Client.run` call. **Nothing will run after that statement**. You will have no events registered. No events will be called. The only thing that will end up happening is that a KeepAliveThread is created. `asyncio` is **single-threaded**, the only thing that is running is the main thread and the keep alive thread (along with any other daemons the other modules need). 

I do not want to walk you through a debugger. I don't use PyCharm. It does not take much effort however to know that your entire debugging woes are fundamentally because of what I posted in the first comment. I would appreciate it if you read it and understood it instead of posting irrelevant comments in my issues.

If you truly feel like your bug is elsewhere (and I doubt it) then you can open another issue.
