### ISSUE TITLE
Using the reverse=True flag on client.logs_from doesn't return messages in chronological order

### ISSUE THREAD

**Issue by belguawhale** [Rapptz/discord.py#548]
When I use client.logs_from without the reverse=True flag, it returns messages in order from most recent to least recent. However when I use client.logs_from with the reverse=True flag, the order is generally least recent to most recent but has some inconsistencies. In the following screenshot of message timestamps, you can see that the times are in order however the date jumps from April 28 to 26 (and jumps around other times too)
Screenshot: https://cdn.discordapp.com/attachments/84319995256905728/307539987400753154/unknown.png

**Comment by Rapptz** [comment]
This is just how the endpoint works. It fetches data and then we reverse it. Since you're paginating (i.e. >100 limit) then you'll end up with that behaviour.

I'm not sure if it's possible to change the behaviour since the reversing is done completely on our side (same with mixing before/after etc).

**Comment by khazhyk** [comment]
Messages returned by the endpoint are always in the same order (newest->oldest).

For fetches greater than 100, since we do lazy fetching, if specifying after= we must fetch from oldest to newest, as when we increase our "page" we are moving after forward to new messages. In this case, setting reversed=True is recommended to get messages in order. For before=, we must fetch from newest to oldest, as when we increase our page we are moving to older messages, for this reversed=False is recommended.

>If set to true, return messages in oldest->newest order. Recommended
>when using with "after" queries with limit over 100, otherwise messages
>will be out of order. Defaults to False for backwards compatability.
