### ISSUE TITLE
Question about User info

### ISSUE THREAD

**Issue by helicoptersarecool** [Rapptz/discord.py#549]
When a `User` instance is created and then referred back to later, is the user information kept as it was when the instance was created, or does it get updated somehow? For example, let's say I created a `User` instance for a user. If that user changed their username, would `User.name` show as the user's username when the instance was created or their updated username?

**Comment by ButterCheezii** [comment]
The information is changed when the WebSocket event is recieved.

For example, if their change their name, `User.name == <their new username>`

**Comment by Rapptz** [comment]
A couple of things.

1) You cannot create these instances yourself. They're read-only models that you can use, provided by the library.
2) If you are referring to an instance in the cache then there is no guarantee that instance will not be overwritten or re-created (i.e. `member is member_from_future` is not guaranteed to hold). This is because the API can do some removal/addition events that would "refresh" the instance so making this guarantee is a bit too difficult.
