### ISSUE TITLE
Embedded Messages

### ISSUE THREAD

**Issue by Cyrogen** [Rapptz/discord.py#553]
I've tried the documentation can someone give me an example of a message with a red line and title?

**Comment by Cyrogen** [comment]
bump

**Comment by Phxntxm** [comment]
Setting a colour: http://discordpy.readthedocs.io/en/latest/api.html#discord.Embed.colour
The colour you want: http://discordpy.readthedocs.io/en/latest/api.html#discord.Colour.red
Setting a title: http://discordpy.readthedocs.io/en/latest/api.html#discord.Embed.title

It's all in the docs. Also, please do not bump github issues, this is not a forum. Additionally, if you want to ask for simple questions like this instead of having an actual issue, you should ask here:
https://discordapp.com/invite/0SBTUU1wZTUzBx2q

And not on a discord issue.
