### ISSUE TITLE
Disabling guild subscriptions causes stale Message.author.roles

### ISSUE THREAD

**Issue by iomintz** [Rapptz/discord.py#5819]
## Summary

Disabling guild subscriptions can prevent Message.author from having up to date role information.

## Reproduction Steps

Note that I cannot reproduce this on my local machine, only in production. As such I cannot provide less code than the entire [bot's codebase](https://github.com/EmoteBot/EmoteManager). I am using guild_subscriptions=False, request_offline_members=False in the bot's constructor call. If, after the bot boots up, a user Muhammad grants a role to another user Rohit that in turn grants the Manage Emojis permission, Rohit cannot use any of my emoji management commands due to the [cog_check](https://github.com/EmoteBot/EmoteManager/blob/56e9d00c03211e6890531d917409859be8be9a67/cogs/emote.py#L103-L107) on those commands.

## Expected Results

I would expect that Rohit would be able to use them given that they have the right permissions.

## Actual Results

Rohit is not able to use emoji management commands.

## Details

As you can see, the MESSAGE_CREATE event did contain all the proper roles:

```
DEBUG:discord.gateway:For Shard ID 4: WebSocket Event: {'t': 'MESSAGE_CREATE', 's': 455247, 'op': 0, 'd': {'type': 0, 'tts': False, 'timestamp': '2020-09-14T23:57:30.596000+00:00', 'pinned': False, 'nonce': '755215684673208320', 'mentions': [{'username': 'Emote Manager', 'public_flags': 65536, 'member': {'roles': ['634444732071673856', '734054422409248800', '731091525139955812'], 'premium_since': None, 'nick': None, 'mute': False, 'joined_at': '2020-07-10T10:16:42.637401+00:00', 'hoisted_role': '734054422409248800', 'deaf': False}, 'id': '473370418007244852', 'discriminator': '7300', 'bot': True, 'avatar': '170751ffbf88b653b1388c95aafff606'}], 'mention_roles': [], 'mention_everyone': False, 'member': {'roles': ['734054422409248800', '731093012192690207'], 'premium_since': None, 'nick': None, 'mute': False, 'joined_at': [REDACTED], 'hoisted_role': '734054422409248800', 'deaf': False}, 'id': '755215685264605184', 'flags': 0, 'embeds': [], 'edited_timestamp': None, 'content': '<@473370418007244852> add [REDACTED]', 'channel_id': [REDACTED], 'author': {'username': [REDACTED], 'public_flags': 256, 'id': [REDACTED], 'discriminator': [REDACTED], 'avatar': [REDACTED]}, 'attachments': [], 'guild_id': [REDACTED]}}
```

The important part here is

```py
'member': {'roles': ['734054422409248800', '731093012192690207'], ...}
```

however the actual Message object received in dpy does not contain role ID 731093012192690207. `Message.author.roles` only contains @everyone and 734054422409248800. Role ID 731093012192690207 was only added after the bot did its initial chunking on bootup.

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

## System Information

- Python v3.8.2-final
- discord.py v1.4.0-final
- aiohttp v3.6.2
- system info: Linux 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07)

**Comment by iomintz** [comment]
@Rapptz if necessary I can provide you access to my VPS / admin access to my bot to help debug this

**Comment by Rapptz** [comment]
> if necessary I can provide you access to my VPS / admin access to my bot to help debug this

There is no need.

The reason why this bug happens is probably because currently there is no cache consistency when those two options are disabled. Internally when those two flags are enabled it toggles an internal "stop caching members" flag as seen here:

https://github.com/Rapptz/discord.py/blob/986adae108df6350baebd7b28807777f2333dc19/discord/state.py#L94-L95

However, this was mainly a bandaid and through other ways you could end up with cached members. In the features/intents branch there's a commit that introduced some form of cache consistency and more explicit cache control (though admittedly, it's still mostly a bandaid). Now, when a member would get cache through other ways and we have guild subscriptions disabled then the library no longer knows how to update the cache for that member since it disables all member related events. This is usually mitigated by making use of the internal member objects and returning that.

Finally, this brings us to our actual issue. Those members are cached -- and within the `Message` class when we handle the `member` key from the payload we decide to update the references to the pre-existing object. This reference update however is incomplete -- it only updates `joined_at` because it expects the other events to update the member through other means (e.g. `GUILD_MEMBER_UPDATE`).  This can be seen here:

https://github.com/Rapptz/discord.py/blob/986adae108df6350baebd7b28807777f2333dc19/discord/message.py#L478-L480

As a result if a member is cached internally and there are no update events (such as when you disable `guild_subscriptions`) then the reference is stale and you'll never get the update for the other fields. This will be corrected in a future commit.
