### ISSUE TITLE
Method for every reconnect (just like for every disconnect `on_disconnect` is called)

### ISSUE THREAD

**Issue by Ahsoka** [Rapptz/discord.py#5820]
### The Problem
The problem I would like to solve is to monitor uptime and downtime of my bot.

### The Ideal Solution
The ideal solution to the problem is to have a complimentary method to `on_disconnect()`, maybe `on_reconnect()`?  This method would be called every time the discord bot reconnects to discord.

### The Current Solution
Right now there are a handful of methods that are called when reconnecting to discord, which are `on_ready`, `on_resume`, and `on_connect`.  However, there is not a set of methods or single method that encompass every time the bot reconnects to discord.  I currently have logging in `on_disconnect` as well as in `on_ready`, `on_resume`, and `on_connect`.  However, for every time the bot logs a disconnection there is not a complimentary logging for a reconnection, at least not consistently.  Sometimes the bot will log a disconnect and a reconnect, which is the expected result, however, sometimes there will be many disconnects logged without any reconnects logged at all.

### Summary
I would greatly appreciate if an `on_reconnect()` method is created.  This method would be called everytime the bot reconnects to discord.  There should in be equal number of calls to `on_disconnect()` and `on_reconnect()` assuming that program is ended while the bot is connected.

-------
Feel free to ask any clarification questions!

**Comment by drewburr** [comment]
@TurretAA12 I'm not sure what your exact use-case is, but it sounds like you're looking for an `on_connect`, but the first connection is not triggered. As a workaround, I'm wondering if we could have a global variable of type bool that would be set to `True` after that first initial connection..

You may be able to do something like this:

```python
has_connected = False

@BOT.event
async def on_connect():
    if has_connected:
        await on_reconnect()
    else:
        has_connected = True


async def on_reconnect():
   ...
```

Is this the functionality you're looking for?

**Comment by TurretAA12** [comment]
> @TurretAA12 I'm not sure what your exact use-case is, but it sounds like you're looking for an `on_connect`, but the first connection is not triggered. As a workaround, I'm wondering if we could have a global variable of type bool that would be set to `True` after that first initial connection..
> 
> You may be able to do something like this:
> 
> ```python
> has_connected = False
> 
> @BOT.event
> async def on_connect():
>     if has_connected:
>         await on_reconnect()
>     else:
>         has_connected = True
> 
> 
> async def on_reconnect():
>    ...
> ```
> 
> Is this the functionality you're looking for?

No I don't believe this would solve my issue.  The `on_connect()` method is not called for every time the `on_disconnect()` method is called.  My use case is to try and monitor uptime and downtime of the my bot (so I want to know how long my bot goes offline because of internet issues or what-not and how long the bot is connected to Discord).
I tried something along the lines of...
```python
@bot.event
async def on_connect():
    print("Reconnected!")

@bot.event
async def on_ready():
    print("Reconnected!")

@bot.event
async def on_resume():
    print("Reconnected!")

@bot.event
async def on_disconnect():
    print("Disconnected!")
````

And the output usually looks something like this.
```
Disconnected!
Disconnected!
Disconnected!
Disconnected!
Reconnected!
Disconnected!
Reconnected!
Disconnected!
Disconnected!
Disconnected!
```
As you can tell the `Disconnected!` message is displayed multiple times in a row despite having print statements in `on_resume()`, `on_connect()`, and `on_ready()`.  This means that the bot must be disconnecting and reconnecting **without ever logging the reconnection to the console**.  I have looked at the `discord.py` API quite extensively and I have found no such method(s) that can reliably track all the times when the bot reconnects.  I have run my bot for several weeks on end and have dozens of log files showcasing this phenomena.

If I am able to reliably track reconnections then I can measure how long my bot is connected to Discord and how long the bot is disconnected from Discord.

**Comment by alkatar21** [comment]
I logged some of the events as well on multiple bots/linux servers and all my bots have:
```
On disconnect called.
On resumed called.
```
This happens a few times every day and there are only a few milliseconds between those events and they are always in that order.

The other events are just called once during startup or after ethernet disconnects or after the gateway unavailable
```
On connect called.
On ready called.
```
And there is no event during shutdown.
However, I don't know if the lib calls any events by itself when there is no internet or the gateway is not available, because this never happened to me in production and I never simulated it during testing.

So I think someone else know this? For me this behavior makes sense, even if I don't know exactly why bots reconnect several times a day

**Comment by nekokatt** [comment]
@alkatar21 if Discord resize any ASGs that they run to downscale them, then you will be disconnected, because a websocket connection is usually stateful unless some voodoo magic is done internally to move an open connection to a different host.

Likewise if a server decides to just crash, or they do a blue-green deployment, then that also will potentially change the machines sitting in any auto-scaling group, so you won't be able to retain a connection.

If their individual servers stayed up 24/7, they'd never be able to update them unless you got everyone using Discord to just log out every time an update was pushed :)

Unfortunately if you are unlucky enough to be on one of those servers, you get kicked. I've seen reconnects every two hours some days, which can be annoying.

> gateway is not available

If the gateway is completely dead, you'll probably get a 5xx cloudflare error. Aiohttp will throw a [`WSServerHandshakeError`](https://docs.aiohttp.org/en/v3.0.1/client_reference.html?highlight=exceptions#aiohttp.WSServerHandshakeError) because it received a non 101 Switching Protocols response. That will likely just propagate out immediately.

If the gateway itself just has internal connectivity issues, [Discord say you should expect it to go quiet but continue heartbeating until such a time that it works again](https://discord.com/developers/docs/topics/gateway#heartbeating). How true that really is, I have no idea.

**Comment by Ahsoka** [comment]
If my understanding of `discord.py` is correct, the `while loop` below is responsible for `discord.py`'s reconnection logic.  I will see if perhaps maybe an `on_reconnect()` method can be inserted somewhere it this loop to provide the functionality I described above.
https://github.com/Rapptz/discord.py/blob/28e5b2a5e133970aff7d0f4db1d973c7516e429a/discord/client.py#L545-L597

It looks like this line below is responsible for the calls to `on_disconnect()`.
https://github.com/Rapptz/discord.py/blob/28e5b2a5e133970aff7d0f4db1d973c7516e429a/discord/client.py#L554
So possibly a call to `on_reconnect()` can be added to for whenever the bot reconnects to Discord.

**Comment by Ahsoka** [comment]
Also this a bit of an unrelated question, but how do I add a label to this issue? I've seen some other ppl, who appear not to have any admin access, add labels.

**Comment by Rapptz** [comment]
This seems like a feature request to reduce the calls to `disconnect` or maybe a doc request, I am unsure. A disconnect is called whenever a connection attempt fails. This could be internet or something else entirely. As a result you can end up in cases where disconnect is called many times without a corresponding connect, this is by design and not something I plan on reworking. The other events such as `on_connect`/`on_ready` and their friends are called after a successful connect.

If you keep disconnecting and want to maintain state then you're free to do so with something like this:

```py
class Client(discord.Client):
    def __init__(self):
        super().__init__(...)
        self.reconnected = False
        self.last_disconnect = None

    async def on_connect(self):
        self.reconnected = True

    async def on_disconnect(self):
        if self.reconnected:
            self.reconnected = False
            self.last_disconnect = datetime.datetime.utcnow()

    def total_downtime(self):
        if self.last_disconnect is None:
            return 0.0

        return (datetime.datetime.utcnow() - self.last_disconnect).total_seconds()
```

**Comment by Ahsoka** [comment]
> This seems like a feature request to reduce the calls to `disconnect` or maybe a doc request, I am unsure. A disconnect is called whenever a connection attempt fails. This could be internet or something else entirely. As a result you can end up in cases where disconnect is called many times without a corresponding connect, this is by design and not something I plan on reworking. The other events such as `on_connect`/`on_ready` and their friends are called after a successful connect.
> 
> If you keep disconnecting and want to maintain state then you're free to do so with something like this:
> 
> ```python
> class Client(discord.Client):
>     def __init__(self):
>         super().__init__(...)
>         self.reconnected = False
>         self.last_disconnect = None
> 
>     async def on_connect(self):
>         self.reconnected = True
> 
>     async def on_disconnect(self):
>         if self.reconnected:
>             self.reconnected = False
>             self.last_disconnect = datetime.datetime.utcnow()
> 
>     def total_downtime(self):
>         if self.last_disconnect is None:
>             return 0.0
> 
>         return (datetime.datetime.utcnow() - self.last_disconnect).total_seconds()
> ```

So it appears my initial presumption was incorrect.  I was under the impression that a call to `on_disconnect()` was **exclusively an indication that the bot is now no longer connected to Discord**, which up until the call to `on_disconnect()` was connected to Discord.  But appears, if I am understanding your message above correctly, that calls to `on_disconnect()` can be made even while the bot is disconnected, which would occur when a reconnection attempt happens and fails.
