### ISSUE TITLE
Discord.py is specifying intents '32509' without you asking it to

### ISSUE THREAD

**Issue by Taarek** [Rapptz/discord.py#5861]
## Summary

If you have a bot running on 1.5.0, without specifying intents, you might run into stuff like get_member failing. I experienced this on a test bot with 1 guild and 8 members.

## Reproduction Steps

Create a bot instance without specifying any intents with the ``intents`` parameter and observe how get_member will always return None.

## Expected Results

The default behavior if you don't specify intents. Considering we're still on V6.

## Actual Results

D.py specifying intents ``32509`` and ``Guild.get_member`` returning None, even though no intents were specified but was enabled in dev portal.

## Checklist

- [x] I have searched the open issues for duplicates.
- [ ] I have shown the entire traceback, if possible.
- [ ] I have removed my token from display, if visible.

## System Information

- Python v3.8.1-final
- discord.py v1.5.0-alpha
    - discord.py pkg_resources: v1.5.0a2528+g28e5b2a
- aiohttp v3.6.2
- system info: Windows 10 10.0.19041

**Comment by apple502j** [comment]
This is working as intended. You must opt-in both in Developer Portals and in code to enable Privileged Intents (such as `members`)

**Comment by Rapptz** [comment]
This is by design. If you don't pass intents then the library will create a default intents instance with everything but members and presences enabled. This is documented in a few places already.

With the intents changes the gateway splits into two. Unfortunately supporting both "v6" (not passing the intents key) and "v6.1" (passing the intents key) is too taxing for the library since there were significant changes in how chunking had to be written in order to support "v6.1" with intents. 

If you want your bot to go back to the time before the intent key was required or passed you'll have to use v1.4.
