### ISSUE TITLE
custom_status() helper function

### ISSUE THREAD

**Issue by ChrisGallardo** [Rapptz/discord.py#5884]
## The Problem
Like I said in my question (#5883), getting a member's custom status seems way too difficult for something that seems to be needed often. Here is the easiest way I've found to get a user's custom status: 
```python
for act in member.activities:
    if isinstance(act, discord.CustomActivity):
        return str(act)
```
This took me a little while to find, and I don't want to make it this hard for others.

## The Ideal Solution
The ideal solution would be to add this helper function to the Member class, like this:
```python
class Member(discord.abc.Messageable, _BaseUser):
    ...
    def custom_status(self):
        """returns a member's custom status"""
        for act in member.activities:
            if isinstance(act, discord.CustomActivity):
                return act
    ...
```

## The Current Solution
Right now, the only solution I've found is to write this function yourself.

## Summary
Add a helper function, `custom_status()` that returns a member's custom status.
If possible, I'd like to be assigned to this.

**Comment by Rapptz** [comment]
This is a bit too niche.

There are many types of statuses out there that someone else might be interested in to the point where your helper special cases one because you, personally, consider it important. This might not be the case for someone else. Nevertheless, there's nothing wrong with making a helper function and using it, that's just how programming tends to be. Not every helper function has a place in the main library.
