### ISSUE TITLE
client.users does not return all members

### ISSUE THREAD

**Issue by Sky-NiniKo** [Rapptz/discord.py#5926]
## Summary
client.users and client.get_all_members() do not see all members but only the client (client.user).
Noted that client.users seems to “learn” a member if the member sends a message.
I also note that I don't have this bug in version 1.4.2 of discord.py

## Reproduction Steps
```python
from discord.ext import commands

client = commands.Bot(command_prefix="!")


@client.event
async def on_ready():
    print("client.get_all_members():")
    for user in client.get_all_members():
        print(user)
        
    print("\nclient.users:")
    for user in client.users:
        print(user)

client.run(TOKEN)
```

## Expected Results
client.get_all_members():
My Bot#0001
Sky NiniKo#0001 (me and it's not my real one #)
[Other member]

client.users:
My Bot#0001
Sky NiniKo#0001 (me and it's not my real one #)
[Other member]

## Actual Results
client.get_all_members():
My Bot#0001

client.users:
My Bot#0001

## Check
- [x] I have searched the open issues for duplicates.
- [x] I have removed my token from display, if visible.

## System Information
- Python v3.8.5-final
- discord.py v1.5.0-final
- aiohttp v3.6.2
- system info: windows 10 10.0.19041

**Comment by AbstractUmbra** [comment]
Please do not disregard the checkboxes provided on the Bug Report template.

This issue is caused by a lack of Intent subscription. As noted in the [version 1.5 changelog](https://discordpy.readthedocs.io/en/latest/whats_new.html#v1-5-0) "API Changes" section, you are required to pass the required [`Intents`](https://discordpy.readthedocs.io/en/latest/api.html?highlight=intents#discord.Intents) to your `commands.Bot` constructor to receive this information from the gateway.
