### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Jovantri10** [Rapptz/discord.py#5936]
Well guys, am trying this on my commands : 

```python
a = "hello"
await ctx.send(a+str(" friend!"))
```

Nah, when am run the command, there is error like this

```unsupported operand type(s) for +: 'NoneType' and 'str'```

Help, or this bug?

**Comment by Rapptz** [comment]
I want you to remove all the library related bits and realize you're essentially left with a minimal example:

```py
a = "hello"
b = a + str(" friend!")
```

Which will not fail had you done any sort of testing. Your issue occurs when `a` is `None`, which is not in this example that you have provided. Likewise, the cast to a `str` here is the same as leaving it out since it's a string literal.

When opening an issue next time please follow the templates and test your code before reporting a bug.
