### ISSUE TITLE
Getting command informations and handling voice

### ISSUE THREAD

**Issue by Foxlider** [Rapptz/discord.py#597]
I tried to make a bot using `@bot.command()` and `async def cmd(args)`
I need the bot to join the command author's voice channel and play music. 
So I first need to get the author ID (or just author) How ? 
Then the channel he's connected in, and then connect.

**Comment by sliceofcode** [comment]
According to the [documentation that you didn't read](http://discordpy.readthedocs.io/en/latest/faq.html#how-do-i-get-the-original-message), you are able to grab the original message from a command by passing the `pass_context` kwarg to the command decorator, like so:
```py
@bot.command(pass_context=True)
```
With this kwarg active, you will receive a [`discord.ext.commands.Context` object](https://github.com/Rapptz/discord.py/blob/async/discord/ext/commands/context.py) as the first parameter of your command. With it, you may access the [`message` attribute](https://github.com/Rapptz/discord.py/blob/async/discord/ext/commands/context.py#L37). This will give you the original message. With it, you may access [the `author` attribute](http://discordpy.readthedocs.io/en/latest/api.html#discord.Message.author) as normal, as it is a plain `Message` object.

Next, comes the part where you want to "join the command author's voice channel". Because you already have the command author, you can use the [`voice` attribute of the `Member`](http://discordpy.readthedocs.io/en/latest/api.html#discord.Member.voice) in order to access the current voice channel that the member is in. Using the information provided by that attribute, you can use [`Client.join_voice_channel`](http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.join_voice_channel) to join the voice channel. Then, use [`create_ytdl_player`](http://discordpy.readthedocs.io/en/latest/api.html#discord.VoiceClient.create_ytdl_player) (a method of the [`VoiceClient` object](http://discordpy.readthedocs.io/en/latest/api.html#discord.VoiceClient) returned by `join_voice_channel`) to create a YoutubeDL player. Make sure to install `youtube-dl` via pip.

**Comment by Foxlider** [comment]
Now my issue is to play the video, wait for it to finish and then to stop
player and disconnect the voice

**Comment by sliceofcode** [comment]
The [`VoiceClient.disconnect` coroutine method](http://discordpy.readthedocs.io/en/latest/api.html#discord.VoiceClient.disconnect) of `VoiceClient` allows you to disconnect it.

Regarding "wait for it to finish" — you can pass the `after` kwarg to [`VoiceClient.create_ytdl_player`](http://discordpy.readthedocs.io/en/latest/api.html#discord.VoiceClient.create_ytdl_player) in order to have some code run when the player finishes.

**Comment by Foxlider** [comment]
I made the after function but it can't be an coroutine. So I can't call the
voice.disconnect() inside

Le 15 juin 2017 10:30, "ryan" <notifications@github.com> a écrit :

The VoiceClient.disconnect coroutine method
<http://discordpy.readthedocs.io/en/latest/api.html#discord.VoiceClient.disconnect>
of VoiceClient allows you to disconnect it.

Regarding "wait for it to finish" — you can pass the after kwarg to
VoiceClient.create_ytdl_player
<http://discordpy.readthedocs.io/en/latest/api.html#discord.VoiceClient.create_ytdl_player>
in order to have some code run when the player finishes.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Rapptz/discord.py/issues/597#issuecomment-308665366>,
or mute the thread

**Comment by sliceofcode** [comment]
You may execute a coroutine using `asyncio.run_coroutine_threadsafe`. This is documented in the FAQ: http://discordpy.readthedocs.io/en/latest/faq.html#how-do-i-pass-a-coroutine-to-the-player-s-after-function

Because it is apparent that you haven't read the documentation or FAQ, I highly recommend that you do so. At least skim the documentation, please! It helps a lot.

**Comment by Foxlider** [comment]
I did. I truly did. And I don't know why but nothing happens.
It never disconnects
--
Lonchambon Alexis
Etudiant IUT Informatique

**Comment by Foxlider** [comment]
async def playYtVid(link):
```
[...]
player = await voice.create_ytdl_player(link, use_aconv=False, after=lambda: closePlayer(player, voice))
[...]
```


def closePlayer(player, voice):
```
print('Closing player')
player.stop
print('Disconnecting...')
coro = voice.disconnect()
fut = asyncio.run_coroutine_threadsafe(coro, bot.loop)
try:
fut.result()
except:
print('error')
pass
print('Disconnected')
```

Console output :
```
Closing player
Disconnecting...
```

**Comment by xNinjaKittyx** [comment]
Please write your code in a way that's readable. You didn't put any spaces on your code, so it's almost unreadable. (almost.)

`player = await voice.create_ytdl_player(link, use_aconv=False, after=lambda: closePlayer(player, voice))`

is not going to work because the `player` inside `closePlayer(player, voice)` gets defined first before `player` that you're setting the `StreamPlayer` to. If this is using cogs, just have a class variable set to current_player. Or have another class that keeps track of current_player per server (i.e. Danny's example here: https://github.com/Rapptz/discord.py/blob/master/examples/playlist.py)
