### ISSUE TITLE
`on_member_join` doesn't work anymore

### ISSUE THREAD

**Issue by Thundo54** [Rapptz/discord.py#5989]
## Summary

One day I saw that my `welcome message` doesn't show up and I checked for error, but I found nothing. One day it was working, but next day it wasn't.

## Reproduction Steps

```from discord.ext import commands
import discord
import asyncio

version = open("data/bot.ver", "r").read()

class WelcomeCog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.Cog.listener()
    async def on_member_join(self, member):
      <code>

def setup(bot):
    bot.add_cog(WelcomeCog(bot))
```

## Expected Results

The cog with this code should work as normal (as it worked before that issue) and send embed with welcome message.

## Actual Results

Nothing is send and there's no errors at all.
(btw my for loop with counting all guilds members doesn't work. guild.members returns everytime 0. both of this issues happened at the same time)

## Intents

None

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

- Python v3.7.3-final
- discord.py v1.5.1-final
- aiohttp v3.6.2
- system info: Linux 5.4.72-v8+ #1356 SMP PREEMPT

**Comment by Rapptz** [comment]
Discord recently released a mandatory update to their gateway requiring the usage of gateway intents. You can find documentation on this [here](https://discordpy.readthedocs.io/en/latest/intents.html). 

Member related events will no longer work due to this change by default. Since these are [privileged intents](https://discordpy.readthedocs.io/en/latest/intents.html#privileged-intents) you need to both enable it in your portal and in your code. For more info see the ["Where’d my members go?"](https://discordpy.readthedocs.io/en/latest/intents.html#where-d-my-members-go) section in the documentation.
