### ISSUE TITLE
Trigger on_reaction_add everytime

### ISSUE THREAD

**Issue by jantracktiv** [Rapptz/discord.py#599]
`on_reaction_add` is not triggered. How do I get a specific message in `client.messages`, which is not changed (server rules), so that the on_reaction_add event is always thrown?

**Comment by Rapptz** [comment]
You cannot modify the internal message cache reliably to do this.

In the next major version of the library, v1.0.0, there will be counterpart events that do what you ask. They're called "raw" events because they do not provide as much rich data as the corresponding full event.

In your case, that'd be [`on_raw_reaction_add`](http://discordpy.readthedocs.io/en/rewrite/api.html#discord.on_raw_reaction_add). However, this does not exist in the currently released version of the library (v0.16.x series) and never will be.

You can try migrating to the newest version, but it's non-trivial: http://discordpy.readthedocs.io/en/rewrite/migrating.html
