### ISSUE TITLE
Check whether guild is Discord Partnered.

### ISSUE THREAD

**Issue by scrazzz** [Rapptz/discord.py#6007]
## The Problem
Even though it's possible to get the guild features and check if the guild is having `PARTNERED` feature or not, it would be great if there's a bool which returns whether the guild is partnered or not.

## The Ideal Solution
By implementing a check which returns a bool indicating whether the guild is Discord Partnered or not.

## The Current Solution
Make our own check.

## Summary
Add `discord.Guild.is_partnered()` which returns a bool.

**Comment by AbstractUmbra** [comment]
I believe this to be unnecessary.

It is entirely trivial to create and maintain a custom check or an inline statement for this.

```py
def feature_check(feature: str):
  def predicate(ctx: commands.Context):
    return feature.upper() in ctx.guild.features
  return commands.check(predicate)
```

and then decorate a command as such:

```py
@feature_check("partnered")
@bot.command()
async def foo(ctx: commands.Context):
  ...
```

Is one basic implementation that comes to mind.

**Comment by NCPlayz** [comment]
Creating `Guild.is_x` for features would still require you to create custom checks, or creating checks for each `is_x` would get messy. There is also a chance that features are removed by Discord as was done for the `Community` feature (where it replaced a few other features that are now removed), which is why they are in a list of strings rather than properties. 

It would make more sense for a generic decorator like `@has_feature('PARTNERED')`, but that in itself seems too simple to be an implemented decorator.

**Comment by scrazzz** [comment]
Yes.
