### ISSUE TITLE
set_thumbnail doesn't support height and width

### ISSUE THREAD

**Issue by Extarys** [Rapptz/discord.py#603]
set_thumbnail doesn't support height and width.
According to discord documentation, thumbnails support height and width but are not implemented in this code.

https://discordapp.com/developers/docs/resources/channel#message-formatting

**Comment by leovoel** [comment]
no, the api docs don't say anything about supporting that.

in practice, you don't get an error for sending those properties, but discord will ignore them completely. you can verify that manually by doing the appropriate http request on your own.

these properties used to actually be sent by the library, but they were removed in c4ee4c1, because of the above.
