### ISSUE TITLE
Use ujson, an ultra fast JSON library

### ISSUE THREAD

**Issue by chauffer** [Rapptz/discord.py#605]
https://pypi.python.org/pypi/ujson

Something like a try/except ImportError would also be nice

**Comment by NotSoSuper** [comment]
If you look at benchmarks for Python 3.5 (around the version most people on discord.py use) it's not too much, ujson used to be a vast improvement in older python versions.

http://artem.krylysov.com/blog/2015/09/29/benchmark-python-json-libraries/

Since discord.py does a lot of json.loads on small and large objects there is a slight performance increase but nothing you'd really notice.

**Comment by chauffer** [comment]
@NotSoSuper I don't think it'd be bad to have it, though. `rapidjson` seems to be maintaned as opposed to ujson, so that might actually be even better 👍

**Comment by Rapptz** [comment]
In the rewrite version of the library users will be able to specify etf or json at import-time via installation of Earl-ETF (an ETF unpacker I wrote in C++) that will be faster than JSON.

I see no reason to improve JSON speeds when that will be a choice.

**Comment by chauffer** [comment]
@Rapptz neat! any approximate idea when this could be ready for public consumption? :D
