### ISSUE TITLE
Add Progress Bar for channel.send(file=discord.File('filename'))

### ISSUE THREAD

**Issue by BluelyTASer** [Rapptz/discord.py#6072]
## The Problem

It doesn't display progress bar.

## The Ideal Solution

Add progress bar so we can know what uploading progress of the file is!

## The Current Solution

Also include a progress percentage, estimated time remaining and time elapsed.

## Summary

`Uploading File... [IIIIIIIIIIIIIIIIII                   ] 99% 00:15<00:30`

**Comment by kaylynn234** [comment]
Since other users (usually) do not see the terminal the bot is attached to, this makes very little sense. Doing it on the discord side of things instead also makes no sense, since you would have to edit a progress bar message constantly, and that's a whole other can of worms that brings its own problems.
It's also noisy - if this is default behavior and your bot sends images often, you don't want your terminal to be filled with progress bars instead of useful information - and generally just seems like a waste.
Additionally, I see no reason why you couldn't implement something like this yourself, or use debug prints/an online speedtest to get an idea of how long uploading a file takes/will take.

**Comment by Rapptz** [comment]
This is outside of the scope of the library.
