### ISSUE TITLE
Reconnecting issue after global rate limit has been hit.

### ISSUE THREAD

**Issue by FightMan01** [Rapptz/discord.py#6074]
## Summary

Issue with reconnecting a shard after a global rate limit has been hit.

## Reproduction Steps

Hit the global rate limit, shard X will stop responding and it will throw timeout errors.

## Expected Results

Shard reconnects fine.

## Actual Results

Timeout errors will happen.

## Intents

All

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

- Python v3.8.5-final
- discord.py v1.5.1-final
- aiohttp v3.6.2
- system info: Linux 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020

![image](https://user-images.githubusercontent.com/29693718/99902190-35062100-2cbc-11eb-9eb1-c95e613641fc.png)

**Comment by Rapptz** [comment]
That log line means it's being handled and that it'll attempt a reconnect. As far as I'm concerned this is working as intended. I don't know the cause of why it's timing out but the library does not care as it will just reconnect eventually.

**Comment by FightMan01** [comment]
> That log line means it's being handled and that it'll attempt a reconnect. As far as I'm concerned this is working as intended. I don't know the cause of why it's timing out but the library does not care as it will just reconnect eventually.

It won't reconnect until I restart the entire bot. I waited about 5 minutes and it is just continued timing out.

**Comment by Rapptz** [comment]
The reconnect handler waits up to about 2^11 seconds (or about 2048 seconds, ~34 minutes) after multiple unsuccessful attempts. You can terminate the bot early if you want to but as far as I can tell unless there is some massive state desync going on (unlikely, since most things gets cleared on reconnect) then there's really not much I can do here. 

Like I said, working as intended. If you want to terminate the script early instead of waiting that's fine too.
