### ISSUE TITLE
Having a bot to write instead of a user

### ISSUE THREAD

**Issue by jeremieSimula** [Rapptz/discord.py#608]
Hi Everyone,

This is probably a dumb question, if so, I am really sorry for this.

So I have my bot running, and I was wondering if somehow I could have it to write messages not in its own name, but in my name.
Basically I want the bot to write:
[jeremie] hello
instead of
[name of my bot] hello

Is this possible?
If yes, can you point me where I should in the documentation to implement such a functionality?

Thank you in advance for your help.

Also, I realize that this is not an issue with discord.py.
However, I do not know where to post my questions: is there a forum somewhere?

**Comment by GiovanniMCMXCIX** [comment]
you know that you just made an "issue" for something that can be found on the library docs which is linked in the repository description if you weren't lazy
also read the fucking [README](https://github.com/Rapptz/discord.py/blob/async/README.md)

**Comment by Pazran** [comment]
i don't you are allow to do that.

From discord site:

"Bots within the Discord API are a separate type of users that are owned by applications (which are owned by users), and authenticate to the system using a token rather than a username and password. Anybody wishing to create a public bot must use a bot account and the OAuth2 API. **Accounts violating this and using normal user accounts for public bots will be suspended and forced to use a bot account for their bot**. "

**Comment by GiovanniMCMXCIX** [comment]
@Pazran he could just used server nicks

**Comment by martmists** [comment]
The others have given enough information about the matter already, but if you have any further questions, feel free to join the [Discord API Server](https://discord.dd/discord-developers) and go to #python_discord-py

**Comment by GiovanniMCMXCIX** [comment]
mart pls

**Comment by jeremieSimula** [comment]
Ok, thanks for the replies.

I will look up for "nicks".

Thanks also for assuming that I did not do any search before posting. I stand corrected and more educated now.

**Comment by Rapptz** [comment]
Yeah, the place to ask for generic questions is in [the official server](https://discord.gg/discord-api).
