### ISSUE TITLE
Unable to set role position as second highest

### ISSUE THREAD

**Issue by therealsujitk** [Rapptz/discord.py#6224]
## Summary
Unable to set position of role as the second highest, works only till the third highest position.

## My Command

```py
@client.command()
async def myCommand(ctx):
    role = await ctx.guild.create_role(name = "myRole")
    await role.edit(position = len(ctx.guild.roles) - 2)
    await ctx.send('Success!')
```

## Expected Results
The role should be created at the second highest position and a success message should be sent in the channel from which the command was called.

## Actual Results
The role gets created, however it stays at position **1** (penultimate) and the success message doesn't get sent. It doesn't show any errors in terminal either.

## Documentation

**position** (`int`) – The new role’s position. This must be below your top role’s position or it will fail.

The role *@everyone* takes position **0**. So the minimum possible value of position is **1** and setting the position as the very top role is not allowed according to the documentation, so why does `len(ctx.guild.roles) - 2` fail? However `len(ctx.guild.roles) - 3` doesn't fail, it creates the role at the third position from the top.

## System Information

> Python: **3.8.7**
>
> Discord: **1.4.1**

**Comment by Rapptz** [comment]
This stuff is sent as-is in the API. If there's anything wonky it's due to the role not being added to the internal role cache for the guild yet. If the edit isn't going through and the message isn't being sent then chances are you don't have permission to do this and your error handler isn't handling it. 

For more information on handling errors in the `discord.ext.commands` library, see the [documentation](https://discordpy.readthedocs.io/en/latest/ext/commands/commands.html#error-handling).
