### ISSUE TITLE
Guild method.

### ISSUE THREAD

**Issue by Geige2** [Rapptz/discord.py#6267]
## The Problem
"set_preferred_locale" is missing from the guild object.

## The Ideal Solution
A method for guilds to access their preferred locale and created templates.

## The Current Solution
As far as I can tell there is none.

## Summary
await guild.set_preferred_locale()

**Comment by SebbyLaw** [comment]
The `region` kwarg in [`Guild.edit`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Guild.edit) is used to set voice region.

There is no way for bots to fetch templates from guilds. This is a discord limitation.

**Comment by Rapptz** [comment]
This issue is made up of two requests. Please limit your feature requests to 1 per issue, that way they can be tracked individually.

Unfortunately the second half of this (fetching templates from guilds) has an upstream bug that needs to be fixed before I can tackle it (ref: https://github.com/discord/discord-api-docs/issues/2457). I can work around it for this particular case but `Client.fetch_template` broke in the process as well.
