### ISSUE TITLE
Doesnt work async functions in on_ready

### ISSUE THREAD

**Issue by RAINGM1** [Rapptz/discord.py#6312]
Doesnt work async functions in on_ready

working only asd() function
What is the problem?
Code:
```
async def on_ready(self)
    async def asd()
    async def change_status()
    async def change_topic()

    await asd()
    await change_status()
    await change_topic()
```

**Comment by SebbyLaw** [comment]
I can't reproduce this.

**Comment by Rapptz** [comment]
The code presented isn't valid python code.

However once fixed this becomes a regular Python interaction where inner functions are called within a function. It is unlikely this wouldn't work since that would imply a bug with Python itself. Either way, this has nothing to do with the library itself.

**Comment by fwrs** [comment]
also please don’t delete the issue template when posting issues
