### ISSUE TITLE
.

### ISSUE THREAD

**Issue by msoes11882** [Rapptz/discord.py#6356]

**Comment by Harmon758** [comment]
First of all, you'll want to reset your token now.

It's not clear what exactly your problem is, but GitHub issues for this repository should be used to report issues with discord.py itself.
They are not a medium for requesting help with your code.
For further help specific to using this library, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README also links.

For code block usage, see https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks.
