### ISSUE TITLE
Reload bot with code changes in `Bot.reload`

### ISSUE THREAD

**Issue by feelingnothing** [Rapptz/discord.py#6432]
**Summary**

Bot.reload() to reload all bot's files

**What is the feature request for?**

discord.ext.commands

**The Problem**

There's no actual way to reload bot without completely shutting it down
I think this feature cost too much to be made, but for big bot owners this is priceless
This feature removes a lot of ass pain from the bot's owners

**The Ideal Solution**

Bot.reload and corresponding events `on_reload`

**The Current Solution**

Complete shutdown and rebooting

edit: No duplicates found

**Comment by Rapptz** [comment]
I'm not really sure what this would do.

The way people "reload their bot" using the command framework is by using extensions and reloading them one by one using [`Bot.reload_extension`](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.Bot.reload_extension). 

Any form of reloading outside of that managed case isn't going to happen since reloading Python code that isn't "controlled" has a lot of gotchas with stale references. That's why the reload mechanism works mainly within the bounds that it's defined to work with (it only removes/adds commands/cogs/listeners). Anything more complicated than this brings into question issues like ownership and stale references. Issues that people still do suffer from even with the library taking a rather strict approach to what it reloads. For example, an extension importing an exception from another extension would lead to that exception never passing an `isinstance` test due to the underlying reference of that object changing. These types of failure are silent to a majority of developers.

It's for those reasons that I don't think a bot-wide reload (whatever that entails) is necessarily a good idea. If you want to reload your commands then there's mechanism to do that, the extension mechanism. If you want to abstract it to allow you to reload *all* your extensions then you can write a command to do that for you as well. Just iterate [`Bot.extensions`](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.Bot.extensions) and reload them one by one using [`Bot.reload_extension`](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.Bot.reload_extension).
