### ISSUE TITLE
API Reference missing

### ISSUE THREAD

**Issue by karintou8710** [Rapptz/discord.py#6553]
### Summary

discord.Member.create_dm() is async def, but the API reference says def.

### Reproduction Steps

async def on_message(self, message):
        dmChannel = message.author.create_dm()
	print(type(dmChannel))

It can be reproduced by the user sending a message.

### Expected Results

<class 'discord.channel.DMChannel'> is output

### Actual Results

<class 'coroutine'> is output

### Intents

all intents.

### System Information

- Python v3.8.5-final
- discord.py v1.7.0-alpha
    - discord.py pkg_resources: v1.6.0
- aiohttp v3.7.4.post0
- system info: Linux 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

API Reference version : latest  

<img width="394" alt="discord-issue" src="https://user-images.githubusercontent.com/80200187/111898997-e6e80b00-8a6c-11eb-9543-a1a4d1ad2fd5.png">

**Comment by SebbyLaw** [comment]
This issue only mentions the attribute table, but the method reference also has the issue of not including the *`await`* before the method name. Probably due to being "inherited" from `User`
<img width="309" alt="Screen Shot 2021-03-21 at 3 31 00 AM" src="https://user-images.githubusercontent.com/44045823/111901500-dcd6f580-89f5-11eb-96fa-a13697066ea5.png">
