### ISSUE TITLE
Return notification message when pinning

### ISSUE THREAD

**Issue by Smerdokryl** [Rapptz/discord.py#6571]
### Summary

Return notification message when pinning

### What is the feature request for?

The core library

### The Problem

Accessing the notification message ("User foo pinned a message bar blah-blah") after pinning a message, e.g. to delete it.

### The Ideal Solution

Make the discord.Message.pin() method return the resulting message of type 'pins_add'.

### The Current Solution

Search all messages after the pinned one, checking their type and reference

An alternative though somewhat different solution would be to make it a parameter like `Message.pin(silent=True)`.

**Comment by SebbyLaw** [comment]
Unfortunately, discord [does not return this information](https://discord.com/developers/docs/resources/channel#add-pinned-channel-message) in the pin message endpoint. The "foolproof" way to do this is with `wait_for` ie:
```py
# assume `message` and `bot` are already defined as the message being pinned and the bot

def check(m):
    return m.type == discord.MessageType.pins_add and m.reference.message_id == message.id

# create a task waiting for the "User foo pinned a message" message
task = create_task(bot.wait_for("message", check=check))

try:
    await message.pin()
except discord.HTTPException:
    task.cancel()  # if this fails you probably want to cancel the task

# the message you wanted
pin_add_message = await task
```
This probably won't be added to the library due to unreliability with permissions, intents, etc.

You can ask for this discord feature by creating an issue here: https://github.com/discord/discord-api-docs/issues/

**Comment by Rapptz** [comment]
This feature request was proposed to Discord and [subsequently denied](https://github.com/discord/discord-api-docs/issues/1617).
