### ISSUE TITLE
Store or be able to reload StreamPlayer object

### ISSUE THREAD

**Issue by GRA0007** [Rapptz/discord.py#669]
So my bot can play music in multiple servers, but I need to be able to deal with a different `StreamPlayer` object for the server that the command (i.e. play a yt video) is being run on. Without this, I could start playing a video in one server then start playing in the second server but using a stop command stops the video in the first server because it's using the original `StreamPlayer` object.

I've tried pickling the `StreamPlayer` object but it's locked and there's no way to _get_ the `StreamPlayer` object from a voice channel or anything. Either I need to be able to serialize the `StreamPlayer` object or return it from another function.

Maybe I'm doing this all wrong, please let me know how I can do this it's my first Discord bot.

**Comment by xNinjaKittyx** [comment]
I'm assuming you're using the current version and not rewrite since you say `StreamPlayer`

You need to make an object that keeps track of current StreamPlayer of every server. You get a StreamPlayer every time you pass `create_ytdl_player` and you need to save that instance.

https://github.com/Rapptz/discord.py/blob/master/examples/playlist.py
Danny (Rapptz) already has a good example of this. Study his code and you can figure it out.
