### ISSUE TITLE
invalid atribut

### ISSUE THREAD

**Issue by mrGG2** [Rapptz/discord.py#6721]
### Summary

atribut eroor

### Reproduction Steps

out of no where it gave me an atribu error on line 1017, and i'm sure 100% i just have about 30 lines. i tested runned the program again and it didn't report an error, instead it didn't run the program at all. It just turned off and put out the next three arrows>>>.

### Minimal Reproducible Code

```python
line 1017, in event
    setattr(self, coro.name, coro)
AttributeError: can't set attribute





(this isn't in my program it reported it from other file)
```

### Expected Results

First it worked, i didn't even change the code from what i remembered before it gave an error. i expected my botto go online and say random greeting message frommy list. ["hi","hello", "godmorning"] etc

### Actual Results

it just turned of ot gave errors. thats the weird thing, without changing th code it sometimes give error and sometimes just turnes off itself.

### Intents

for now i just wanted it to turn online

### System Information

'-m' is not recognized as an internal or external command,
operable program or batch file.

### Checklist

I have searched the open issues for duplicates.
I have shown the entire traceback, if possible.
I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
Hello.

Sorry, this issue doesn't make any sense to me. It's full of errors that make it indecipherable to me. Right now, judging from the way the issue is worded, I suspect you're new to Python and programming in general. If that's so, you might be better suited [seeking help from a tutorial](https://docs.python.org/3/tutorial/) before attempting to work on a Discord bot.
