### ISSUE TITLE
The discord module doesn’t work

### ISSUE THREAD

**Issue by ShivanshPlays1** [Rapptz/discord.py#6815]
### Summary

I am using the latest version of python (Python 9) but it doesn’t let me use discord!

### Reproduction Steps

import discord

### Expected Results

I expected it to download the discord module.

### Actual Results

Error, discord module not found

### Intents

I wanted to make a bot

### System Information

import discord

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by ImVaskel** [comment]
You need to install it with pip.

**Comment by ShivanshPlays1** [comment]
I think I know the problem, I searched the issue up on google and it says to uninstall python 3.9 and install python 3.8.6, so if you have the same issue, just uninstall python 3.9 and use python 3.8.6.

**Comment by simmsb** [comment]
Hm, downgrading python is likely a solution for you simply because you had dpy installed on the version of python you downgraded to.

Python doesn't magically fetch packages when you import them, so expecting `import discord`
to fetch the package is going to result in disappointment.

You might want to read the 'installing' section of the readme: https://github.com/Rapptz/discord.py#installing

**Comment by ShivanshPlays1** [comment]
@simmsb I already know the solution so that's why I closed the issue

**Comment by Rapptz** [comment]
discord.py works fine with 3.9 -- however in order to use the module you need to install it with `pip`.
