### ISSUE TITLE
Is there a way to use input() without the bot pausing

### ISSUE THREAD

**Issue by ThePiGuy24** [Rapptz/discord.py#697]
i have tried many things to try and use `input()` in my code, but unfortunately i cant get it to work, there is nothing about this in the documentation to my knowledge, please help

**Comment by mgardne8** [comment]
Your issue is you're trying to use a blocking function within an asynchronous system. 
There are ways to achieve keyboard polling within an asynchronous library but I would suggest you read up on asynchronous and blocking vs non-blocking functions, here are a few resources:
[AsyncIO docsl](https://docs.python.org/3/library/asyncio.htmll) (Python AsyncIO Documentation)
[Blocking vs Non-Blocking](https://nodejs.org/en/docs/guides/blocking-vs-non-blocking/) (This is written for node but the underlying theory is the same)
[AsyncIO tutorial](https://www.blog.pythonlibrary.org/2016/07/26/python-3-an-intro-to-asyncio/) (I find this as a decent intro to AsyncIO in python)

This is also not an `Issue` with the library itself and would better be served as a question within [our discord](https://discord.gg/0SBTUU1wZTUzBx2q) (This will join `#General`, then move to `#python_discord-py` for library related help)

**Comment by ThePiGuy24** [comment]
Rapptz, why you always closing issues without solving, please don't set this to contributors only like you did with issue #125

**Comment by Rapptz** [comment]
Because this issue has nothing to do with the library.

This is reserved for library questions not general python questions about how to use `input` with `asyncio`.

Go ask Google.

**Comment by mgardne8** [comment]
@ThePiGuy24 this isnt an issue with the library, I also responded to you two days ago including where to seek help from, resulting in no response from you until just now. If there a problem with the library that we can help you with you are free you are free to open another issue, if you want more help in using Input within your bot please refer to my previous post and join our discord channel. 

-Matt
