### ISSUE TITLE
Ignore command misspellings

### ISSUE THREAD

**Issue by Nimboss2411** [Rapptz/discord.py#6998]
### Summary

When a command is misspelled, invoke the closest version of what the user was supposedly trying to say

### What is the feature request for?

discord.ext.commands

### The Problem

For example when a user accidentaly types "!hel" instead of "!help", instead of raising CommandNotFound help can be invoked

### The Ideal Solution

It can be a bot attribute
Bot(..., ..., ignore_misspellings = True) (idk bout the attribute name my mind is blank rn)

### The Current Solution

I don't know if there's a current solution through on_message, but even if there is it would still be a handy attribute

### Additional Context

N/A

**Comment by Rapptz** [comment]
This is too computationally expensive to do for the core library and requires dependencies that some people might not want either due to licensing or other issues. Not to mention invoking a command that the user didn't ask for could be surprising depending on the distance between the two commands. For example `help` and `hell` have the same distance, if you typed `hel` which would you choose? Assume `help` gives you help and `hell` bans you from the server. Suddenly your invocation for `help` might have banned someone instead.

I'm gonna go with no for this one.

**Comment by Nimboss2411** [comment]
Gotchu

**Comment by AnotherTwinkle** [comment]
@Nimboss2411 For your information, You can easily achieve this in your bot by using a Fuzzy Search Algorithm with a `CommandNotFound` handler.

**Comment by Nimboss2411** [comment]
> @Nimboss2411 For your information, You can easily achieve this in your bot by using a Fuzzy Search Algorithm with a `CommandNotFound` handler.

Okay, thanks!

**Comment by timothypidashev** [comment]
you could also go the easy way and just have aliases set to commonly mispelled ways
`commands.command(aliases=["hel", "he", "h"]`
