### ISSUE TITLE
Uploading File blocks other commands

### ISSUE THREAD

**Issue by BlackThunder01001** [Rapptz/discord.py#7003]
### Summary

Uploading File blocks other commands and doesn't send any message or any other bot action until the file upload is completed

### Reproduction Steps

Start uploading a big file. Meanwhile use any command such as ping. The bot will only invoke the command once that file upload is completed. 

### Expected Results

Bot should do all other async actions (send message, edit message, add reaction... all sorts of actions)  while uploading the file.

### Actual Results

Bot uploads the file first, and once the file upload is completed, it then processes other actions,

### Intents

<Intents value=32511>

### System Information

```
- Python v3.9.5-final
- discord.py v1.7.2-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19043

```

### Checklist

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by AwesomeSam9523** [comment]
Yes, reproducible.

**Comment by Rapptz** [comment]
This is because for rate limiting reasons, a lock is held on the major parameters and route until the request is completed. You'll note that sending a message in a different channel works fine or a completely different endpoint.

Fixing this is non-trivial since it requires porting over to a mass concurrent implementation. We tried. As far as I know, no library implements it this way because it's prone for bugs.
