### ISSUE TITLE
On message edit

### ISSUE THREAD

**Issue by starnakin** [Rapptz/discord.py#7072]
### Summary

Some time the edit event not be execute

### Reproduction Steps

edit a message already edit before the bot was started

### Minimal Reproducible Code

```python
import discord
from discord.ext import commands

bot=commands.Bot(command_prefix="!")
    
@bot.event
async def on_message_edit(before, after):
    print(1)

bot.run("token")
```

### Expected Results

I expect the bot execute my code if the message was edited 

### Actual Results

Actually that work perfectely only if message has doesn't edited before the start of the bot

### Intents

Sorry I don't have understand

### System Information

- Python v3.9.5-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19043

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Dorukyum** [comment]
`on_message_edit` listens to messages that are in the bot's internal cache, you can use `on_raw_message_edit` for all messages.

**Comment by Vexs** [comment]
On_message_edit only runs for messages in cache- which is the last 5000(?) messages since the bot was started by default.

To handle messages prior you'll want to use on_raw_message_edit- which doesn't give you the prior content, notably so you'd have to handle that yourself. 

Also, just load your config json once and fetch the keys from the resultant dict instead of loading twice.

**Comment by NCPlayz** [comment]
For more information on the `on_raw_message_edit` event, see the [documentation](https://discordpy.readthedocs.io/en/stable/api.html#discord.on_raw_message_edit). 

Further help should be done in the [discord.py server](https://discord.gg/dpy).

**Comment by starnakin** [comment]
Thank a lot
