### ISSUE TITLE
Dpy 2.0 - Member.avatar_url returns AttributeError: 'Member' object has no attribute 'avatar_url'

### ISSUE THREAD

**Issue by Jerry-py** [Rapptz/discord.py#7074]
### Summary

When I install discord.py 2.0. I tried it. It worked but now I decide to test it out with some of my bots so I tried and what happen was that it returned AttributeError: 'Member' object has no attribute 'avatar_url'.

### Reproduction Steps

What happened was that I install dpy 2.0 and tested out with my own discord bots. Then it returned the error AttributeError: 'Member' object has no attribute 'avatar_url'. When I uninstalled discord.py 2.0 it worked but not for 2.0.

### Minimal Reproducible Code

```python
embed.set_author(name=member.name, icon_url=member.avatar_url)
```

### Expected Results

I excepted to work and show the user's pfp.

### Actual Results

The result was that it would return the error: discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'Member' object has no attribute 'avatar_url'

### Intents

discord.Intents.all()

### System Information

- Python v3.9.4-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19041

### Checklist

- [x] I have searched the open issues for duplicates.
- [X] I've tried to reach out to my friends that can do dpy
- [X] I haved retry to install 2.0

**Comment by Rapptz** [comment]
The 2 in v2.0 means it has breaking changes from v1.0 since it follows [semantic versioning](https://semver.org). Asset was one of the breaking changes in the library. So there is no expectation for this to work since this is by design.

It isn't recommended to install v2.0 if you don't know what you're doing since it's not meant for public consumption -- it has a lot of breaking changes and is not a simple upgrade from v1.x.
