### ISSUE TITLE
Can't add role to someone when using `pending`.

### ISSUE THREAD

**Issue by mmattbtw** [Rapptz/discord.py#7199]
### Summary

When a member joins the server and accepts the rules, it doesn't add the member role.

### Reproduction Steps

1. Member joins the server
2. Member accepts rules
3. `on_member_update` triggers
4. Everything works except for `await after.add_roles....`

### Minimal Reproducible Code

```python
@Cog.listener()
    async def on_member_update(self, before, after):
        if before.pending != after.pending:
            logchannel = # log channel id

            member_role = # member role id
    
            print(member_role)
            
            await after.add_roles(after.guild.get_role(member_role))        # Add the Member role to the user.
            
			await logchannel.send(f"{before.display_name} agreed to the rules.")        # Send a message to the logchannel.
```

### Expected Results

Expected to add the role to the user.

### Actual Results

Doesn't add the role, does everything before that line, then stops.

### Intents

intents = discord.Intents.default()         intents.members = True         intents.presences = False

### System Information

- Python v3.9.5-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19042

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I can add roles in the same way in another command as I did here, it's just adding a role during this, doesn't work.

**Comment by Phxntxm** [comment]
This isn't "Minimal reproducible code" because this is a syntax error, since the indentation doesn't match up. I assume you just pulled out "irrelevant" stuff and that was inside of an if statement or something similar. 

It won't just stop there, it will either succeed or error. If you're getting an error, then you need to show that. If you're not then either it is successful, or it's not reaching that point (which means there is other code that is effecting this). This is very unlikely to be a problem with the library, and is just a problem with your code or something similar... I'd recommend joining the guild and asking for further help there with your actual code https://discord.gg/r3sSKJJ
