### ISSUE TITLE
Add a separate fetch_thread method for client and guild objects

### ISSUE THREAD

**Issue by JustAnyones** [Rapptz/discord.py#7399]
### Summary

I want a separate method to fetch threads.

### What is the feature request for?

The core library

### The Problem

I was storing threads in a database and would lock them after some time to prevent super old threads from being woken up. I tried using various channel methods but none of them seemed to fit for the task.

I thought I could just fetch threads manually with an API call, unfortunately I couldn't find a such method anywhere. Finally, after doing some searching, I found this PR https://github.com/Rapptz/discord.py/pull/7156.

The problem is that there isn't any _good_ documentation on how to fetch threads.

### The Ideal Solution

Either make fetch_thread an alias of fetch_channel or implement it properly, as ``Guild.fetch_channel`` does not support fetching of threads.

### The Current Solution

Right now it's possible to retrieve threads using the ``Client.fetch_channel()`` method, however the method name is not very clear and not very well documented (I couldn't easily find it by just searching the term thread in docs).

**Comment by Rapptz** [comment]
`Guild.fetch_channel` now supports fetching threads via #7402

The question of symmetry still remains. Fundamentally the API does not do the type-level split in their routes which is why `fetch_channel` ended up in the situation it is today. The library however needs the type split for type safety reasons since threads are incompatible with other guild channel types. Right now the library has 3 cache lookup functions:

- `Guild.get_channel`: This returns `GuildChannel`.
- `Guild.get_thread`: This returns a `Thread`.
- `Guild.get_channel_or_thread`: This returns a `Union[GuildChannel, Thread]`.

The last one was added since it was a common operation for people who indiscriminately store `channel_id` in their databases and presumably just need the common `Messageable` base type. The `fetch` situation is different and has no such symmetry, `Guild.fetch_channel` returns a `Union[GuildChannel, Thread]`. There is no `fetch_thread` and there is no `fetch_channel_or_thread`. This lack of symmetry is also shown in `Client`, there is `Client.get_channel` and `Client.fetch_channel` but no corresponding methods for `get_thread` or `get_channel_or_thread`.

I'm not entirely sure what the best course of action is but I figure laying it all out here would be good. Personally while I enjoy symmetry the current approach could get hairy really quickly so keeping it as it is today makes sense to me though it is unfortunate. There could be a future where there's `Guild.fetch_thread` which does a client-side check if the types match and then a `Guild.fetch_channel_or_thread` which does what the current `Guild.fetch_channel` does but personally I'm split on it.
