### ISSUE TITLE
[v2] DM channels are not cached when messages are received

### ISSUE THREAD

**Issue by attendeany** [Rapptz/discord.py#7409]
### Summary

Client.get_channel(id) returns None after the start of the chat with the bot.

### Reproduction Steps

1. Type and run Minimal Reproducible Code
2. Send a message to the bot's DM

### Minimal Reproducible Code

```python
import discord

client = discord.Client(intents=discord.Intents.default())


@client.event
async def on_ready():
    print(f"Logged in as {client.user}")


@client.event
async def on_message(message):
    channel_id = message.channel.id
    print(f"Message from {message.channel.type.name} channel has been received. {channel_id=}")
    print(f"{len(client.private_channels)=}, {client.get_channel(channel_id)=}\n")

client.run('TOKEN')
```

### Expected Results

```
len(client.private_channels) > 0 and client.get_channel(channel_id) is not None
```

### Actual Results

```
Logged in as Spicy#2388
Message from private channel has been received. channel_id=779835698651332610
len(client.private_channels)=0, client.get_channel(channel_id)=None
```

### Intents

discord.Intents.default()

### System Information

- Python v3.9.6-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v1.7.3
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19042

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

In version 1.7.3, message.channel got into the internal cache, but in version 2.0 it was not possible to get the channel. I looked for the reasons for this in Breaking Changes and in opened Issues, but did not find anything. I guess this is a bug.

**Comment by Wordsetter0** [comment]
`
from discord.ext import commands

client = commands.Bot(command_prefix="!")

@client.event
async def on_ready():
    print(f"Logged in as {client.user}")

@client.event
async def on_message(message):
    channel_id = message.channel.id
    print(f"Message from {message.channel.type.name} channel has been received. {channel_id=}")
    print(f"{len(client.private_channels)=}, {client.get_channel(channel_id)=}\n")

client.run("TOKEN") 
`
I executed this code and I got this output(I put CENSORED over some data)

Message from private channel has been received. channel_id="CENSORED"
len(client.private_channels)=1, client.get_channel(channel_id)=<DMChannel id="CENSORED"recipient=<User id="CENSORED" name="CENSORED" discriminator="CENSORED" bot=False>>

As you can see everything works fine, so I don't think this is a bug.

**Comment by SebbyLaw** [comment]
Please don't write comments with misinformation @Wordsetter0.

I can reproduce this on the latest commit of the master branch. Seems like this is caused by #6701 (f1fac96e33e20d70859ebcf6bac439d406c04727). To have private channels cached on v2.0 in [`private_channels`](https://discordpy.readthedocs.io/en/master/api.html?highlight=create_dm#discord.Client.private_channels) you should now either call [`Client.create_dm()`](https://discordpy.readthedocs.io/en/master/api.html?highlight=create_dm#discord.Client.create_dm), [`User.create_dm()`](https://discordpy.readthedocs.io/en/master/api.html?highlight=create_dm#discord.User.create_dm), or [`User.send()`](https://discordpy.readthedocs.io/en/master/api.html?highlight=create_dm#discord.User.send).

This probably needs documentation.

**Comment by attendeany** [comment]
It would be nice to get confirmation that this behavior in the new version is not a bug.

It turns out that if I need this channel to be in the cache after starting a chat with a user, I'll have to do something like this:
```
@client.event
async def on_message(message):
    if isinstance(message.channel, discord.DMChannel) and client.get_channel(message.channel.id) is None:
        await message.author.create_dm()
```

I might be wrong, but this sounds potentially confusing to some developers:
```
await message.author.send('Hey!')  # DM Channel in client cache now
await message.channel.send('Hey!')  # DM Channel not in client cache
```
The bot begins to communicate with the user, but the state of the cache of private channels depends on which method of the same name we use. _However, this is already beyond the scope of this issue._

**Comment by Rapptz** [comment]
The Discord gateway update to v8 made it so we no longer get `CHANNEL_CREATE` for DM channels in the gateway. The library tries to rectify this by creating fake `DMChannel` objects with some incomplete data. Since the data is incomplete, it would be wrong to add it to the cache when the endpoint call would be more up to date. As a result, this isn't a bug but rather intended and a consequence of a breaking change in the API.

It might help to refactor your code so you don't need these incomplete DMChannels cached, though I'm not exactly sure how.
