### ISSUE TITLE
The roles have no color?

### ISSUE THREAD

**Issue by Angel-Bokkuyoshi** [Rapptz/discord.py#743]
I tried to do the seemingly simple:
`await my_bot.bot.edit_role(message.server, role, color = discord.Color.red())`
But as usual to my dismay SOMETHING was wrong, giving me the error:
`AttributeError: 'Role' object has no attribute 'colour'`
Someone please tell me this is a dream.

**Comment by Rapptz** [comment]
Gonna need a full traceback for this one.

**Comment by piggeywig2000** [comment]
here's what I do:
`await client.edit_role(message.server, message.author.roles[1], colour=discord.Colour.red())`
The client is set to discord.Client()
The message is the message sent in. The reason why I do message.author.roles[1] is because message.author.roles returns a list of all the roles, and everyone is always the first item into the list.

Hope this helps

**Comment by Rapptz** [comment]
Too long without a traceback. Gonna close this. Make another issue if you get it again, preferably with the traceback.
