### ISSUE TITLE
what did i fuck up here

### ISSUE THREAD

**Issue by cmncaled** [Rapptz/discord.py#747]
```
class CommandErrorHandler:
    def __init__(self, bot):
        self.bot = bot

    async def on_command_error(self, ctx, error):

        if isinstance(error, discord.ext.commands.CommandNotFound):
            await self.bot.say("This command does not exist.")
```

**Comment by Rapptz** [comment]
`ctx, error` is for the rewrite branch
`error, ctx` is for the v0.16.x release series.

ergo, your arguments are probably swapped.

**Comment by cmncaled** [comment]
swapping the args accomplished nothing

**Comment by cmncaled** [comment]
swapping the args accomplished nothing

**Comment by Rapptz** [comment]
This code is fine otherwise. Assuming you added the cog. e.g.

```py
def setup(bot):
   bot.add_cog(CommandErrorHandler(bot))
```

in global scope.

I'm not here to guess what the issue is though so you're going to need to be more proactive and figure out how to debug issues yourself before asking questions here.

If you want to ask easy questions then the proper place to ask them would be in the official [Discord API server](https://discord.gg/discord-api).

Don't repost your comment either.
