### ISSUE TITLE
Randomly skipping over some songs- errors below.

### ISSUE THREAD

**Issue by KitLUL** [Rapptz/discord.py#756]
I have a basic Discord bot that utilises youtube_dl to play songs from YouTube.  50% of the time, the bot is fine and will play a song from start-to-finish without issue.  However, sometimes, it will completely skip over a song and produce the following error.

    [tls @ 000000d6c5df0f40] The TLS connection was non-properly terminated.
    [tls @ 000000d6c5df0f40] The specified session has been invalidated for some reason.
    [tls @ 0000004d13626720] Error in the pull function.
    [matroska,webm @ 0000004d1363afc0] Read error
    [tls @ 0000004d13626720] The specified session has been invalidated for some reason.
        Last message repeated 1 times

My code is below in a pastebin- can anyone spot anything obvious?  I've tried looking this up but it put it down to a shaky internet connection- my internet is a stable 120/40, and is never under high load.  Any help is appreciated!

https://pastebin.com/y188k0vq

**Comment by tom-GER** [comment]
I currently have the same issue, I sadly found no solution to this :/

**Comment by ccubed** [comment]
This isn't a discord.py issue. This is a youtube links expire issue. Welcome to the joys of streaming content. One solution to this is download before play.

**Comment by SunDwarf** [comment]
This is caused by the video URL used being old or invalid; the web player fetches a new one every time you open the video so this isn't an issue whereas your bots are pretending to be YouTube and don't.

One solution is store the URL of the video instead of downloading info, and download the info either shortly before the next track is to play (pipelining) or to download the info as soon as the next track plays. This ensures that the URL is always fresh when playing.

The other solution is to download the entire video data, which avoids having to rely on the links not being stale.

**Comment by KitLUL** [comment]
I assume that the download-the-video option is available through youtube_dl itself- hence the name?  How would I go about this?  Is it simply a parameter I can add, or would I have to build a function to extract the audio from the video?

**Comment by jfun** [comment]
It's fairly simple to do so: https://github.com/rg3/youtube-dl/blob/master/README.md#embedding-youtube-dl

**Comment by s0hvaperuna** [comment]
Try adding this to your before_args `" -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5"`
