### ISSUE TITLE
Add slash command permissions

### ISSUE THREAD

**Issue by tuna2134** [Rapptz/discord.py#7592]
### Summary

I want you to be able to set the permissions of the slash command by default.

### What is the feature request for?

The core library

### The Problem

Filtering such as slash command permissions becomes easier.

### The Ideal Solution

I want it to be like discord.ext.commands.has_permissions.

**Comment by joannx** [comment]
im not too keen on how interaction permissions work, but im pretty sure its on a member/role basis. not exactly permissions based. (i could and probably am wrong).

would like to see the feature implemented though

**Comment by Rapptz** [comment]
I'm currently waiting for the so-called "Permissions v2" to release before tackling permissions in application commands since the old permission approach will end up deprecated.

**Comment by joannx** [comment]
> I'm currently waiting for the so-called "Permissions v2" to release before tackling permissions in application commands since the old permission approach will end up deprecated.

whenever said perms v2 is released, and actually committed, will checks be included in that to or would that be seperate?

**Comment by Rapptz** [comment]
Checks for app_commands needs design work since they're not as simple as they were for ext.commands. The latter has a `Context` object but the former only has an `Interaction` object. There can also be a `Namespace` object that would store the options before they're being transformed but I'd need to see what kind of use cases people have with checks before actually confirming or committing to anything.

**Comment by tuna2134** [comment]
fmm

**Comment by itttgg** [comment]
this is a good idea

**Comment by tuna2134** [comment]
> this is a good idea

thanks

**Comment by Codingboy65** [comment]
any update?

**Comment by AbstractUmbra** [comment]
> I'm currently waiting for the so-called "Permissions v2" to release before tackling permissions in application commands since the old permission approach will end up deprecated.

What Rapptz said here is still the case.
I'm sure there will be communications in-server when this changes. Feel free to join and keep an ear to the ground.

**Comment by Codingboy65** [comment]
Will do! Thanks for the update!

**Comment by anselal** [comment]
> im not too keen on how interaction permissions work, but im pretty sure its on a member/role basis. not exactly permissions based. (i could and probably am wrong).
> 
> would like to see the feature implemented though

Yes, they work on a member/role basis. 
And of course they should be implemented.
Let's see what discord will change in v2...

**Comment by GoogleGenius** [comment]
[Link to an official Discord article on Permissions v2](https://support.discord.com/hc/en-us/articles/4644915651095-Command-Permissions)

And: https://msciotti.notion.site/msciotti/Command-Permissions-V2-4d113cb49090409f998f3bd80a06c3bd

**Comment by UltimateSppy765** [comment]
> > im not too keen on how interaction permissions work, but im pretty sure its on a member/role basis. not exactly permissions based. (i could and probably am wrong).
> > would like to see the feature implemented though
> 
> Yes, they work on a member/role basis. And of course they should be implemented. Let's see what discord will change in v2...

Including channels too! (type 3, they don't grey out but don't work as per the permission overwrites)



> > I'm currently waiting for the so-called "Permissions v2" to release before tackling permissions in application commands since the old permission approach will end up deprecated.
> 
> whenever said perms v2 is released, and actually committed, will checks be included in that to or would that be seperate?

I'd prefer checks to be separate from API command permissions because:

- I can put custom error messages if the checks fail.
- It would be slightly annoying if some person updates a command's permissions in the server and on bot restarts or such it gets reset to what was set in the code.

_And I doubt checks and command permissions can be merged easily provided that they work on a per guild basis, except for the `default_member_permissions` part. (which also is for the sole purpose of Discord automatically looking for roles with those perms and then updating overrides for those particular roles in the guild when the integration is added)_

**Comment by tuna2134** [comment]
Permissions v2 is released.

**Comment by tuna2134** [comment]
https://github.com/discord/discord-api-docs/discussions/4831

**Comment by tuna2134** [comment]
https://github.com/discord/discord-api-docs/discussions/4831
