### ISSUE TITLE
From on_member_join(), is it possible to get the server id and channel id of the server that triggered it?

### ISSUE THREAD

**Issue by AMScaglione** [Rapptz/discord.py#763]
I'm trying to write a welcome message system, that posts a greeting in #general. Up to this point I've just used message.channel as the destination for the commands I've written. I tried using something super convoluted like

`
discord.Object(id=member.server.default_channel.id)`

but that spat back this error:

`AttributeError: 'NoneType' object has no attribute 'id'`

**Comment by Rapptz** [comment]
The concept of a default_channel no longer exists reliably (you can delete it and now a days it's an artefact of legacy).

You can get the server ID via `member.server.id`. The rest you would have to do yourself, e.g. some configuration value that your users would place to post the welcome messages in.

Alternatively, scrap the feature since Discord comes with this built-in now.

**Comment by samdelong** [comment]
The `member` class no longer has a `server` attribute. You should be using `member.guild.id` now
