### ISSUE TITLE
Support for Forum Channels

### ISSUE THREAD

**Issue by Eanae** [Rapptz/discord.py#7652]
### Summary

Support for Forum Channels

### What is the feature request for?

The core library

### The Problem

Discord has recently started pushing Forums to select Discords. Bots running Discord.py cannot currently see messages from inside forum threads.

### The Ideal Solution

Implement Forums

**Comment by Pysics** [comment]
I am sending this for people who don't have this feature in any of there servers. 
_This is the [source](https://github.com/Pycord-Development/pycord/pull/1095#issuecomment-1053907439)._

Forum channel in the channel list:
![image](https://user-images.githubusercontent.com/79257339/158018025-9dffa31a-1774-490c-beac-6f7fa56359e3.png)

Main forum channel view:
![image](https://user-images.githubusercontent.com/79257339/158018054-d855f89b-3e21-46d0-8989-2af27d5ad4f6.png)

**Comment by JDJGInc** [comment]
I think the only way to implement them would be if they are documented on the discord api docs.

**Comment by Eanae** [comment]
The forum topics are just threads so in theory I believe most of the ground work should be in place. I spoke to Discord and the forum channel channel type is 15.

**Comment by Eanae** [comment]
Did some quick hacking together on personal code and can verify adding in channel type 15 allows the bot to see Forum messages.

**Comment by ryry013** [comment]
Forum channels are treated kind of like text channels where users can make threads in them but can't send messages in the parent text channel. I put together some code in a pull request for pycord before discord.py opened back up and you can see it here: https://github.com/Pycord-Development/pycord/pull/1095

I got it mostly working except I couldn't guess the API endpoint for properly opening a new thread. There's `start_thread_without_message()` because there's no message in the parent channel to start the thread from (make sure you set the type to 15 to avoid the default of being set to a private thread type), but it makes a glitched out public thread with no starting message. Doing something like editing the name of the thread sends a system notification message in the thread and that opens it up.

**Comment by Rapptz** [comment]
I added preliminary support that aj asked for, notably missing is the tag information since that's in flux. Forums won't be releasing for a while though.

**Comment by tweirtx** [comment]
With the current state of things (including support for it from discord.js) would it be possible to revisit adding tag information and handling now?

**Comment by Rapptz** [comment]
It's been implemented in the master branch for weeks now, it'll be in a v2.1 release.
