### ISSUE TITLE
guild.member_count isn't always filled

### ISSUE THREAD

**Issue by FrequencyX4** [Rapptz/discord.py#7656]
### Summary

Out of the 5k guilds my bot has, guild.member_count is None on 37 of them. I can't tell if that's normal or a bug

### Reproduction Steps

try printing something like `len([g for g in bot.guilds if not g.member_count])​` and you might see some are None
I found this because it caused a type error while using the member_count attribute in an equation

### Expected Results

guild.member_count is always filled

### Actual Results

it sometimes returns None

### Intents

all

### System Information

- Python v3.9.7-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3837+gc95d12dc
- aiohttp v3.7.4.post0
- system info: Linux 5.13.0-28-generic #31-Ubuntu SMP Thu Jan 13 17:41:06 UTC 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by AbstractUmbra** [comment]
This is not a bug.

As of 03687fb616e8aa60d4ecbf05b80b7a275d8184f2 this is now as designed with the library.
The alternative of not having this change, is that you would suffer an `AttributeError` upon accessing this attribute if the key had not been given in the payload from discord, which seemingly happens when a guild is unavailable.

**Comment by Rapptz** [comment]
There's a bug with the implementation of that commit so this issue is valid.
