### ISSUE TITLE
Improve app commands and cog interop

### ISSUE THREAD

**Issue by GoogleGenius** [Rapptz/discord.py#7658]
### Summary

Potentially improve the implementation of app commands in the command extensions library as it requires some handling of message command things even if creating a solely interaction-based bot.

### What is the feature request for?

discord.ext.commands

### The Problem

The current implementation of application commands in cogs still listens to message events and has integration with the conventional message commands. This requires the `commands.Bot()` to require the `command_prefix` as it listens to the `on_message` event in order to execute and process any message commands. However, if building an interaction-based bot, this is completely unnecessary. 

### The Ideal Solution

The ability to use other features of the command extension, i.e., cogs, with application commands without needing to override things for message commands. 

### The Current Solution

 - Possibly overriding the `on_message` event to prevent command processing
 - Passing an empty string to `command_prefix` in `commands.Bot()`

**Comment by Rapptz** [comment]
If you want a pure `app_commands` based bot then you can just use the conventional `discord.Client` with your own tree. There is no "plugin" system like extensions but other than that the remaining concepts map out fine.

The only other form of planned interop is for hybrid commands. Anything outside of things that come from that use case are unlikely to be added. `commands.Bot` will always be primarily for message based commands, to imply otherwise would be a bizarre design decision on my part.
