### ISSUE TITLE
compare AppCommand and Command

### ISSUE THREAD

**Issue by m1raynee** [Rapptz/discord.py#7669]
### Summary

Add posibility to compare `AppCommand` - API object and `Command` - runtime one

### What is the feature request for?

The core library

### The Problem

It would be easier to determine if command synchronization is required.

### The Ideal Solution

```py
synced_commands = await bot.tree.fetch_commands()
existing_commands = bot.tree.get_commands()

if synced_commands != existing_commands:
    await bot.tree.sync()
```

### The Current Solution

In turn, compare first the type of command, then the options if any.

**Comment by nmsturcke** [comment]
Don't think this is needed, you can do the following if you want:

```py
synced_commands = [command.name for command in (await bot.tree.fetch_commands())]
existing_commands = [command.name for command in bot.tree.get_commands()]
synced_commands.sort()
existing_commands.sort()

if synced_commands != existing_commands:
    await bot.tree.sync()
```

**Comment by Rapptz** [comment]
> It would be easier to determine if command synchronization is required.

I just want to note that the server knows nothing is changed and doesn't count anything towards your rate limit. The rate limit is 200 *new* commands per day. Changing a command doesn't count. Likewise, not modifying a command at all doesn't do anything since the request is idempotent. 

Since the original goal of this request doesn't have a necessarily strong merit, compounded by the fact that the localisation aspect of commands makes this infeasible, I don't think I will work on this. Sorry.
