### ISSUE TITLE
CategoryChannel should not implement abc.GuildChannel

### ISSUE THREAD

**Issue by diceroll123** [Rapptz/discord.py#776]
Given an instance:
- `CategoryChannel.category` returns None (I don't think it ever won't do that)
- `CategoryChannel.mention` returns  something along the lines of `<#357575435170742273>`, which turns into `#test category` (unclickable text)
- This one's my favorite. If you do `CategoryChannel.create_invite()` it makes an invite to the category itself, and when it's joined, the interface is messed up, it's as if you're messaging the category channel, thus Clyde does not allow this.

This should probably be mentioned to Jake or someone up-there as well, because of this image:

![image](https://user-images.githubusercontent.com/1243957/30391628-217db97a-9888-11e7-9cb6-ce274d12692d.png)

It shows the invite as pointing to the category.

---

Exhibit 2:

![image](https://user-images.githubusercontent.com/1243957/30391556-d90e582a-9887-11e7-9937-bcee25009571.png)

I'd list the things wrong in this screenshot here but it's rather obvious.

disclaimer: this screenshot is in stable discordapp.com chat, though that shouldn't change anything besides visibility of categories on the left.

**Comment by SunDwarf** [comment]
Well, it is a guild channel, so naturally it should implement abc.GuildChannel.

Maybe it should raise errors on those methods instead of replacing the correct superclass.

**Comment by Rapptz** [comment]
The first point is kind of moot. It's there because it needs to be there for compatibility. I'm not gonna remove it.

The second point is being handled fine by the client so not much change there either. Voice channels have the same thing as far as I know.

The final point seems to be a client bug rather than one with the library. Probably bad handling of category invites rather than it being something meant to be forbidden. However I don't actually know.
