### ISSUE TITLE
move_channel does not do anything.

### ISSUE THREAD

**Issue by Rain288** [Rapptz/discord.py#789]
Greetings. So, I  am making a bot that should automate users creating their own text channels, but when a new channel is made it's moved to the top of the server. No problem, since `move_channel` exists, right? Well in my case the command simply does not do anything, not even throw an error.
My code on question:
```python
channel = await client.create_channel(message.server, arg + name, everyone, owner)
await client.move_channel(channel, 7)
```
My server does have more than 7 channels but theoretically I wouldn't use a static int anyways, but I'm using it for testing purposes. It just simply will not move the channel. I even tried using `await asyncio.sleep(5)` but that didn't change anything so I don't think the command is simply being skipped over, rather it just has no result for whatever reason.
I have read the documentation and I have already asked for help in the Discord API server but nobody could figure out what was wrong so I decided to make a GitHub issue. In case I'm actually still overlooking something, my apologies.
As a side-note after printing the positions for all the channels it seems that the position numbers are completely broken which is probably the cause of this issue and so that would make the issue discord-side most likely.

**Comment by Rapptz** [comment]
This is a cache issue.

The channel you create via `client.create_channel` is *not* the one that's in cache. The one in cache is until the websocket receives a corresponding `CHANNEL_CREATE` event.

Why bring this up? That's because `move_channel` requires a consistent cache to work so it knows how to send the request to Discord (it has to calculate the positions of other channels to know where to place yours).

Since the channel is not in cache, the calculation completely ignores the fact your channel exists and thus it doesn't move it anywhere.

You should be able to solve this by doing `await asyncio.sleep(1)` right before the move. You said you've tried a sleep but didn't designate where.

**Comment by Rain288** [comment]
Yeah that was my bad for not mentioning where, I put the `await asyncio.sleep(5)` right after the channel creation, like this
```python
channel = await client.create_channel(message.server, arg + name, everyone, owner)
await asyncio.sleep(5)
await client.move_channel(channel, 7)
```
Maybe I should wait a bit longer?
The explanation with the cache though makes sense, thanks for pointing it out.

**Comment by Rain288** [comment]
Also this is what I'm getting in the log when running the command that creates the channel
https://gist.github.com/Rain288/e28adb2c552fa628f33fbd9cbcd40836

**Comment by The-Tasty-Jaffa** [comment]
I am also having issues with move_channel. I've ```await asyncio.sleep(1)``` just before moving the channel . However, I think that there is a problem related to the categories of discord.
