### ISSUE TITLE
Add method shortcuts for Threads

### ISSUE THREAD

**Issue by IIHERO4** [Rapptz/discord.py#7911]
### Summary

Adding method shortcuts for Thread operations such as .lock or .archive

### What is the feature request for?

The core library

### The Problem

**Its not necessary but gives a bit of sugar to the new Thread API**

So I wanted to close a thread, i got lost in the docs until i saw `.edit` which is fine considering only doing `.edit(locked=True)` does the job pretty well. but its a bit hidden but does make sense for `.edit` to do so.

### The Ideal Solution

Honestly this could be closed as its not nessecary but i feel a method shortcut as `.lock(*, lock=True)` and `.archive(*, archive=True)` might be good or redundant which its up to you to decide

> Maybe add smth to the docs?

**Comment by Rapptz** [comment]
Generally speaking, I don't like adding redundant methods that `edit` already provides. My reasoning for this is mainly consistency since `edit` does everything and it's consistent with other methods. It's also, admittedly, a form of laziness because it doesn't require documenting and implementing it and all that jazz.

Some endpoints require special behaviour that isn't done with `edit`, such as `Message.pin`. Some methods are sugar for `edit` such as `Member.timeout` or `Member.move_to`. The former is because it provides something extra on top of the `Member.edit` call and the latter is mainly legacy.

I get the discoverability angle but also not really sure where it ends. I suppose for verb actions it's not too bad, such as `lock`, `unlock`, `archive`, `unarchive`, `pin`, and `unpin`. But, as you can see here that's 6 methods for something that is easily just done with 1. It could also give users the impression that in order to do a combination of these they need to do multiple requests, which isn't true.

**Comment by IIHERO4** [comment]
totally understandable, np
