### ISSUE TITLE
Mentioning the user that issued the command

### ISSUE THREAD

**Issue by 5tanly** [Rapptz/discord.py#793]
`@bot.command()`
`async def checked():`
`    await bot.say(INSERT_@USER_HERE + ' has checked')`

How do I make this alert the user, either with the @User tag or just their username.

Looking at [this](http://discordpy.readthedocs.io/en/rewrite/api.html?highlight=mention#discord.User) didnt help at all because im stupid

**Comment by Rapptz** [comment]
I'm not sure what version of the library you're using since you're linking to the rewrite docs but your code is for the v0.16.x branch.

Nevertheless, the concept is the same in each one.

One, you need to [pass the context](http://discordpy.readthedocs.io/en/latest/faq.html#how-do-i-get-the-original-message) to get the original message.

Then you need to use [`User.mention`](http://discordpy.readthedocs.io/en/latest/api.html#discord.User.mention) to actually get the string to mention them.

Putting it all together:

```py
@bot.command(pass_context=True)
async def checked(ctx):
    await bot.say('{0.mention} has checked.'.format(ctx.message.author))
```
