### ISSUE TITLE
Provide Constants for Max Files and Max Embeds When Sending a Message

### ISSUE THREAD

**Issue by Yay295** [Rapptz/discord.py#8002]
### Summary

Provide constants for the max number of files and of embeds a message can be sent with.

### What is the feature request for?

The core library

### The Problem

When sending a message, the number of embeds and files are limited to 10, and an exception is thrown if you exceed that. So we have to make sure we don't go over the limit.

### The Ideal Solution

I would like there to be a constant I can refer to that has the limit so I don't have to hardcode it myself and remember to update it if it ever changes.

### The Current Solution

The current solution is to hardcode in the limits and hope they don't change (which, to be fair, I don't think they ever have).

**Comment by RGBCube** [comment]
the limit is 10 and won't change any time soon

**Comment by Yay295** [comment]
But if it did change I would have to go through my code checking for every usage of "10". If these values were stored as a constant instead I wouldn't have to worry about that. I could just code to the constant being some number, and my code would still work whenever it was changed.

**Comment by JelNiSlaw** [comment]
> If these values were stored as a constant

Then why not do that in your own code?

**Comment by Yay295** [comment]
Because that wouldn't change anything??? I would still have to update my code if these values ever changed. If these were provided by discord.py, then if they ever changed, I would just have to update discord.py.

I see this as similar to the values on Guild instances: max_presences, max_members, and max_video_channel_users. Except those values are provided by Discord, and these ones appear to be hard-coded.

Also I didn't notice this before, but stickers are also limited (to 3), so that would be another one to have a constant for.

**Comment by Rapptz** [comment]
I don't think there's anything inherently wrong with this feature request. I'm just not sure how far you want it to go. There are many many limits throughout the API and it'd be kind of absurd for me to make a constant for each one, especially since that places the burden of maintenance of those constants on me rather than Discord's backend.

There are a few constants that I check client side in the library, those are generally constants that Discord very rarely changes such as the embed limit, file limit, and the application command name limits. Other than specific cases I avoid doing checks client side and just let the backend deal with it since it reduces the burden of maintenance for me.

But yeah, not sure what you're expecting here considering the difference in scope.
