### ISSUE TITLE
Cogs absolutely do not function with 2.0

### ISSUE THREAD

**Issue by LK-Simon** [Rapptz/discord.py#8055]
### Summary

Register cogs as you do in 1.7... the commands are not present

### Reproduction Steps

Make a working Bot in 1.7... switch to 2.0 of this library... boom, your Bot commands will not work (they claim to register, but aren't there)

Type <prefix>help, and you'll see no commands available at all!

### Expected Results

I expected basic Bot commands to function as they have in previous versions of the library... not for the entire codebase to be ruined simply for the sake of trying to obtain functionality for Threads.

### Actual Results

Everything went to hell!

### Intents

All intents

### System Information

Python 3.10... v 2.0 pre-release of this library

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
Since the "2" in v2 signifies a major version bump following SemVer principles, that means there are breaking changes in the library. There is a migrating guide detailing all the changes from v1.7 to v2.0. This particular change is documented [here](https://discordpy.readthedocs.io/en/latest/migrating.html#extension-and-cog-loading-unloading-is-now-asynchronous).

**Comment by LK-Simon** [comment]
@Rapptz Absolutely my bad! I pulled up the Migration docs but for the wrong version 😆 

I got worried when I couldn't see or use any of the commands on my Bot suddenly, and my Admin team (who use those commands to administer our game servers) were (understandably) complaining that they couldn't do their jobs 😆 

Thank you so much for pointing me to the correct docs! You're a lifesaver!
