### ISSUE TITLE
Example "background_task_asyncio.py " does not work

### ISSUE THREAD

**Issue by tarchive** [Rapptz/discord.py#8157]
### Summary

Nothing happens

### Reproduction Steps

download example.
change channel ID
run

### Minimal Reproducible Code

```python
https://github.com/Rapptz/discord.py/blob/master/examples/background_task_asyncio.py
```

### Expected Results

Send a message to the specified channel ID every 60 seconds

### Actual Results

Nothing happens because the create_task in setup_hook is not run. Only the on_ready message is printed

### Intents

discord.Intents.default()

### System Information

- Python v3.9.13-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Linux 5.10.28 Wed Apr 7 08:23:18 PDT 2021

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by LostLuma** [comment]
The example in the `master` branch is for the upcoming 2.0 version of the library, rather than the stable one, as development takes place there and they are updated as changes are made to the library.

You might be looking for the [stable version example](https://github.com/Rapptz/discord.py/blob/v1.x/examples/background_task_asyncio.py) on the 1.x branch instead.

**Comment by tarchive** [comment]
Indeed that was the issue. Branch v1.x example worked. Thank you for a prompt response.
