### ISSUE TITLE
NameError: name 'RequestsWebhookAdapter' is not defined

### ISSUE THREAD

**Issue by Loko415** [Rapptz/discord.py#8206]
### Summary

big fail

### Reproduction Steps

imported RequestsWebhookAdapter from webhook and discord.py didnt work

### Minimal Reproducible Code

```python
from discord import Webhook, RequestsWebhookAdapter
from PIL import Image, ImageDraw, ImageFilter
from bs4 import BeautifulSoup
```

### Expected Results

it works.qrfq

### Actual Results

FAILEDqrfqrfq

### Intents

qrfqrf

### System Information

windows 11qwqwrq

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by jack1142** [comment]
This issue does not contain information to be actionable but based on the little information you did provide, I'm guessing you installed discord.py from the master branch on GitHub which no longer has `RequestsWebhookAdapter`. The master branch contains the upcoming (in-development) 2.0 version of the library, rather than the stable 1.7 one, and per SemVer principles (which discord.py adheres to) this means that it contains breaking changes.

The latest documentation has a migration guide for moving from v1.0 to v2.0 here:
https://discordpy.readthedocs.io/en/latest/migrating.html

The particular change that you're affected by in your issue is mentioned here:
https://discordpy.readthedocs.io/en/latest/migrating.html#major-webhook-changes
