### ISSUE TITLE
on_reaction_add Syntax Error

### ISSUE THREAD

**Issue by MoWizard** [Rapptz/discord.py#821]
Hello,
I have tried to use the `discord.on_reaction_add` event but has an error saying `Syntax Error: unexpected character after line continuation character`. I have tried to take the `discord.` or add `await` to the start but that won't fix it. I tried removing the colon but that removes the arrow in the terminal to the closing bracket.
Here is the code...
```
@bot.group(pass_context=True)
async def games(ctx):
    if ctx.invoked_subcommand is None:
        print('Error No. 2, Invalid query')
        await bot.say('**Error No. 2, Invalid query**')


@games.command(pass_context=True)
async def text_adventure(ctx):
    player = ctx.message.author
    msg = await bot.send_message(ctx.message.author, str(player.name) + ', do you want to start the text adventure?')
    await bot.add_reaction(msg, '\U0001F44D')
    await bot.add_reaction(msg, '\U0001F44E')
    await discord.on_reaction_add(\U0001F44D, player):
        await bot.clear_reactions(msg)
        await bot.send_message(ctx.message.author, 'You have started an unforgettable journey')
    await discord.on_reaction_add(\U0001F44E, player):
        await bot.clear_reactions(msg)
        await bot.send_message(ctx.message.author, 'Ok ' + str(player.name) + ', we will wait for you')
```

Thanks for your help

**Comment by henry232323** [comment]
Syntax Errors will never be bugs in the library, they are always bugs with your code. The line continuation character is a \ (backslash) used in certain contexts, Google is your friend with this error.

**Comment by Vexs** [comment]
You want wait_for_reaction not "discord.on_reaction_add", which is not a thing. Also, make sure you have a commands.group() decorator above def games

**Comment by henry232323** [comment]
Those are other issues, however this issue is, youre trying to use unicode literals outside a string, they need to be within quotation marks

**Comment by MoWizard** [comment]
It doesn't recognise `on_reaction_add`

**Comment by Vexs** [comment]
> You want wait_for_reaction not "discord.on_reaction_add", which is not a thing. Also, make sure you have a commands.group() decorator above def games

Also, you should join the discord for these small issues. discord.gg/discord-api #python_discord-py

**Comment by MoWizard** [comment]
And discord.on_reaction_add is a thing
http://discordpy.readthedocs.io/en/latest/api.html#discord.on_reaction_add

**Comment by Rapptz** [comment]
Those are events. They are meant to be registered via `@client.event` or subclassing. Not how you're using them. The `discord` prefix is there because it's a quirk of Sphinx.

If you want to wait for a reaction, you have to use [`wait_for_reaction`](http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.wait_for_reaction). There are examples given. 

However, you seem to have a huge misunderstanding on how Python works and functions so I suggest starting with a tutorial instead of brute forcing your way to making a Discord bot and sprinkling `await` when things don't work. It would make the ride a lot smoother in the future.
