### ISSUE TITLE
app_commands.Group.error raises error (TypeError: The error handler must have 2 parameters.) when used inside a cog

### ISSUE THREAD

**Issue by Skyla-Dev** [Rapptz/discord.py#8251]
### Summary

app_commands.Group.error raises TypeError inside of cogs

### Reproduction Steps

- Create a cog with a group command inside
- Create an group error handler using the [error decorator](https://discordpy.readthedocs.io/en/latest/interactions/api.html#discord.app_commands.Group.error)

### Minimal Reproducible Code

```python
class MyCog(commands.Cog, name='MyCog'):
    def __init__(self, bot):
        self.bot = bot

    test = app_commands.Group(name='test', description='test')

    @test.error
    async def on_test_error(self, interaction, error):
        print('error handling would go here')
```

### Expected Results

The cog loads as expected with the handler set up for the group and its subcommands.

### Actual Results

```
ERROR:core.yuri:loading command file "commands\image.py" returned an error: <class 'discord.ext.commands.errors.ExtensionFailed'> (Extension 'commands.image' raised an error: TypeError: The error handler must have 2 parameters.)Traceback (most recent call last):
  File "C:\Users\stshr\Documents\Programming projects\Yuri PyBot\venv\lib\site-packages\discord\ext\commands\bot.py", line 917, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\stshr\Documents\Programming projects\Yuri PyBot\commands\image.py", line 24, in <module>
    class ImageCommand(commands.Cog, name='ImageCommand'):
  File "C:\Users\stshr\Documents\Programming projects\Yuri PyBot\commands\image.py", line 1124, in ImageCommand
    async def on_image_error(self, interaction: discord.Interaction, error: app_commands.AppCommandError):
  File "C:\Users\stshr\Documents\Programming projects\Yuri PyBot\venv\lib\site-packages\discord\app_commands\commands.py", line 1416, in error
    raise TypeError('The error handler must have 2 parameters.')
TypeError: The error handler must have 2 parameters.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\stshr\Documents\Programming projects\Yuri PyBot\core\yuri.py", line 59, in setup_hook
    await self.load_extension(f'commands.{file[:-3]}')
  File "C:\Users\stshr\Documents\Programming projects\Yuri PyBot\venv\lib\site-packages\discord\ext\commands\bot.py", line 995, in load_extension
    await self._load_from_module_spec(spec, name)
  File "C:\Users\stshr\Documents\Programming projects\Yuri PyBot\venv\lib\site-packages\discord\ext\commands\bot.py", line 920, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'commands.image' raised an error: TypeError: The error handler must have 2 parameters.
```

### Intents

Default intents (Intents.default)

### System Information

- Python v3.10.0-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4418+g87bc79e6
- aiohttp v3.8.1
- system info: Windows 10 10.0.19043

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
Groups such as `app_commands.Group` and their subclasses do not store any binding information in them. A binding is the `self` parameter. Instead, command objects store the `self` binding since it needs it to call the actual callback. There is no current way for the library to know whether a binding is needed or not for groups, and realistically adding binding tracking code to things has historically been a source of bugs in the library so I'm reluctant to add more places where this is needed.

You might have better luck using the `cog_app_command_error` special method on cogs and checking whether the command's group is the one you're interested in. Alternatively, make a subclass of `Group` and override `on_error` that way, if applicable (i.e. you do not need the `self` to represent the cog object.

I'll leave this issue open for a bit to see if there's actual demand for this feature since to me it feels like more complication than it's worth, especially since there are viable alternatives.
