### ISSUE TITLE
Permission Decorator for Commands

### ISSUE THREAD

**Issue by antinuke0day** [Rapptz/discord.py#8261]
### Summary

commands.command(name=, permissions=)

### What is the feature request for?

discord.ext.commands

### The Problem

Ability to include necessary permissions for commands or maybe a way to do it automatically for help menus

### The Ideal Solution

a kwarg in the command

### The Current Solution

use up a different decorator like usage or brief

**Comment by Rapptz** [comment]
There are [countless of checks](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#ext-commands-api-checks) for this use case.

**Comment by SquadRealityProject** [comment]
I'm also looking for a feature that implements command permissions API: https://discord.com/developers/docs/interactions/application-commands#permissions

It provides way better user experience compared to current decorator pattern as it moves control to Discord client instead of checking permissions on Bot server side.
Can it be reconsidered? @Rapptz
