### ISSUE TITLE
Provide some git flow with pull requests

### ISSUE THREAD

**Issue by Randomneo** [Rapptz/discord.py#8320]
### Summary

Commiting to master every hour would not do any good for development

### What is the feature request for?

The core library

### The Problem

For those who want to stay on edge with development should be able to stick to master. 

### The Ideal Solution

Master should contain only merges or typo/small fixes. Any other change must past code review

### The Current Solution

Any contributor can put some breaking code in to master branch

**Comment by ImVaskel** [comment]
Rapptz is the only one who has commit access to master, all other changes must be done via pull requests.

**Comment by IAmTomahawkx** [comment]
> For those who want to stay on edge with development should be able to stick to master.
You can! However the master branch is unstable, so by using it you acknowledge that there will be breaking changes, and sometimes things may break. As Vaskel said, Rapptz is the only person with commit access.
If this is a complaint due to #8319 , this code was reviewed and merged via PR.

**Comment by Randomneo** [comment]
Oh i'm sorry. If this code was approved. My bad

**Comment by Rapptz** [comment]
Please don't try to lecture me on how I should operate my repository. It is rude. Not to mention that this issue comes from a place of ignorance and assumptions, which only makes it look worse.

For starters, as mentioned, all pull requests are reviewed and merged by me. This is pretty explicitly shown in the GitHub UI so I don't know where you got the assumption otherwise.

The pull request that you seem so fixated and angry over was not adding "global state". These things are called context variables, they are *meant* to be global but they represent task-local variables. I understand that this is unusual for those who are unfamiliar with asynchronous programming in Python but making all these uneducated and ignorant comments while attempting to be condescending and passive aggressive in the issue tracker and in the comments of commits is definitely not acceptable behaviour in this repository.
