### ISSUE TITLE
server.roles returns a blank list

### ISSUE THREAD

**Issue by IHim2341** [Rapptz/discord.py#840]
Using server.roles gives a blank array.

Code is:

`client = commands.Bot(description=description, command_prefix=bot_prefix)
server = discord.Server(id='331815810353987584')
channels = discord.Channel
print(server.roles)`

**Comment by datmellow** [comment]
You are trying to get a list of roles before the bot has connected to discord's servers. It only populates this information after you log in.

**Comment by IHim2341** [comment]
Would this work?

`client = commands.Bot(description=description, command_prefix=bot_prefix)
server = discord.Server(id='331815810353987584')
channels = discord.Channel`

`@client.event
async def on_ready():
    print('Logged in')
    print('Name : {}'.format(client.user.name))
    print('ID : {}'.format(client.user.id))
    print(discord.__version__)


print(server.roles)`

**Comment by datmellow** [comment]
If you read the big warning here: 
http://discordpy.readthedocs.io/en/latest/api.html#data-classes
You will see that you are not supposed to be creating these objects yourself. 
wait until the bot has called ``on_ready`` then you can do ``server = client.get_server(id)``
http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.get_server

But otherwise questions like this should probably be posted in the python_discord.py channel in the api server:
inv link: https://discord.gg/discord-api

**Comment by IHim2341** [comment]
Thank you.
