### ISSUE TITLE
Actual type-hints inconsistent with docstring.

### ISSUE THREAD

**Issue by wookie184** [Rapptz/discord.py#8460]
Some docstrings show a different type to the actual type hint.

For example, compare
https://github.com/Rapptz/discord.py/blob/9971c2e09a0ed989c2c6a8c16a8eaf77f9270897/discord/abc.py#L1366-L1367
with
https://github.com/Rapptz/discord.py/blob/9971c2e09a0ed989c2c6a8c16a8eaf77f9270897/discord/abc.py#L1427-L1434

It would be nice if the docs could be changed to use `Sequence` instead of `list` to confirm that all sequences are supported (e.g. tuples). It could also be worth looking for other instances of this anyway, even if both the docs and type hint say list where it could be sequence instead.

I'd prefer if someone else opened a PR for this, although I could if nobody else takes it up.

(this really didn't fit the template, although it doesn't really fit the other one either and I can't work out how to open a plain issue)

**Comment by Rapptz** [comment]
This was a compromise that was made explicit when we loosened the type hints. The idea was that the documentation would explicitly only support lists rather than sequences for implementation leeway while the type hints would be looser due to variance requirements.

**Comment by wookie184** [comment]
I'm not sure I understand. If you want the implementation leeway shouldn't you type them strictly as well to prevent misuse that may break that code in the future? And vice versa, if you want to allow variance why not document that too? The trade-off isn't solved by documenting/type-hinting them inconsistently.

I believe the only difference between operations on lists and sequences would be methods mutating the list, and mutating the input list would be surprising anyway, so in this case implementation leeway doesn't seem too applicable.

**Comment by Rapptz** [comment]
The variance problem is that `List[T]` is invariant so e.g. passing a list of role and snowflake objects can't be valid for `List[Snowflake]` where as for `Sequence` it's covariant so it can be. This discrepancy only makes sense in a type hinting context and the library does not actually document or stabilise anything relating to type hinting because it breaks every single release or few commits. Note that the difference between `Sequence` and `List` might be small, but what I'm talking about is a lot more general than just that, the change of loosening type hints vs documentation was also evident in things that technically took `Iterable` instead of `List`.

**Comment by wookie184** [comment]
Ah, sorry, I'd misinterpreted what you meant by variance before. Thanks for explaining, that makes sense.

I still think there's not much of a reason not to document allowing Sequence instead of list. I understand why you might not want to change to Iterable, and you don't need to, Sequence still gives the user more flexibility without any real loss in flexibility for you.
