### ISSUE TITLE
No reactions in Message.reactions

### ISSUE THREAD

**Issue by danshat** [Rapptz/discord.py#861]
The bot sends a message to the channel and then waits for user's reaction (it should).
It reacts to it's own message, like this:

![](https://i.imgur.com/RbyFaDX.png)
Anyway, when I check the `Message.reactions` list, it's empty.
Here goes the code:

```python
        botmsg = await bot.send_message(msg.message.channel,'Are you sure?')
        await bot.add_reaction(botmsg,'👎')
        await bot.add_reaction(botmsg,'👍')
        await asyncio.sleep(5)
        for item in botmsg.reactions:
                print(item)```

**Comment by khazhyk** [comment]
This is because the message returned by bot.send_message is a temporary that is *not* the message that is in the cache. Only the message in the cache has reactions updated.

You will need to wait 0-1s for the msg to arrive via websocket, then grab the message from the cache.

e.g. `cache_msg = discord.utils.get(bot.messages, id=botmsg.id)`
then use `cache_msg.reactions`

**Comment by danshat** [comment]
That worked! Thanks.

**Comment by danshat** [comment]
By the way, what if I am using rewrite? `Client.messages` was removed there.

**Comment by QairexStudio** [comment]
> By the way, what if I am using rewrite? `Client.messages` was removed from there.
> Edit:
> I understood, there is now `Context.get_message()`.

anymore its `client.cached_messages`

**Comment by QairexStudio** [comment]
anymore its client.cached_messages
