### ISSUE TITLE
A new method for discord.ui.View()

### ISSUE THREAD

**Issue by sami0596** [Rapptz/discord.py#8979]
### Summary

A new method discord.ui.View(), calling it  add_items(), to be able to add multiple items at the same time

### What is the feature request for?

The core library

### The Problem

Being able to add multiple items to a View, at the same time, using one code line

### The Ideal Solution

This is for creating multiple buttons or other components, which we are saving to a list..
to then later, whenever we want to, adding it to a view discord.ui.View() with the method add_items(*items).

### The Current Solution

We can only add one item at a time

### Additional Context

```py
# buttons_list = [multiple buttons from somewhere]

view = discord.ui.View()
view.add_items(*buttons_list)
```

**Comment by Rapptz** [comment]
The problem with this request is that for it to be useful it needs to be atomic compared to a simple for loop. In other words, if adding the item in index 5 causes an error, then the items added in index 0 to 4 should have been reverted. Otherwise the view is in a corrupted state. However, implementing this is complicated and error prone, especially with the different widths in place. 

On top of that, doing this for most people amounts to just syntax sugar over a simple for loop, which doesn't really seem like it's worth doing.
