### ISSUE TITLE
Sync WebhookMessage requires a guild to use .create_thread()

### ISSUE THREAD

**Issue by iandouglas** [Rapptz/discord.py#9008]
### Summary

A WebhookMessage cannot use create_thread in some circumstances

### Reproduction Steps

Create a SyncWebhook, use `from_url`, and this successfully posts a message into a channel for which I have a webhook URL made.

I want to turn that message into a thread, so the next time the user posts a message in Twitch, their messages get put into a Discord thread instead of individual messages.

Calling msg.create_thread() fails saying it can't create a thread without guild information.

### Minimal Reproducible Code

```python
webhook = discord.SyncWebhook.from_url(discord_webhook_url, bot_token=discord_bot_token)
        msg = webhook.send(f'[Twitch message]: {message}', wait=True)

        th = await msg.create_thread(
            name=thread_name, 
            auto_archive_duration=30,
            slowmode_delay=None)
```

### Expected Results

I expected, from the documentation, that I could use the returned WebhookMessage object and call its respective `.create_thread()` method to turn the message into a thread, so I could store the Thread object and call thread.send() to add more messages to the thread later.

Given the exception thrown, I would expect that the WebhookMessage object could either have the guild information be retrieved from the webhook URL for me, or give me a `.set_guild_by_id()` method or something where I could pass a known guild ID value (since I'm not using the typical `discord.Client` kind of setup here.

At a minimum, perhaps https://discordpy.readthedocs.io/en/stable/api.html#discord.WebhookMessage.create_thread could be updated to reflect that the WebhookMessage, when used with SyncWebhook, needs Guild information somehow, or see an example of how to get the guild information from the webhook URL and maybe set `msg.guild` manually or something?

### Actual Results

 File "/Users/id/src/chatbot/venv/lib/python3.9/site-packages/twitchio/client.py", line 193, in wrapped
    await func(*args)
  File "/Users/id/src/chatbot/prodbot.py", line 278, in event_message
    await track_whisper_on_discord(message.author.name.lower(), message.content)
  File "/Users/id/src/chatbot/prodbot.py", line 231, in track_whisper_on_discord
    th = await msg.create_thread(
  File "/Users/id/src/chatbot/venv/lib/python3.9/site-packages/discord/message.py", line 1205, in create_thread
    raise ValueError('This message does not have guild info attached.')
ValueError: This message does not have guild info attached.

### Intents

none

### System Information

- Python v3.9.10-final
- discord.py v2.0.1-final
- aiohttp v3.8.3
- system info: Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Thanks for an amazing library, I'm having a lot of fun with it!

**Comment by Rapptz** [comment]
This is by design.

The webhook you made is a partial one, so it doesn't have the full information necessary for certain methods to work. `Message.create_thread` for example only works if there's a `Guild` instance attached and the error is just reporting that. For the record, the same limitation applies to regular `WebhookMessage` as well.

It *might* be possible to mock the information for `WebhookMessage.guild` but I'd have to investigate a bit.

**Comment by iandouglas** [comment]
Gotcha, thanks @Rapptz ... should that method be overridden to report a "not implemented" error or something so people know this is on purpose? Right now, newcomers to the library (like me) could think this should be possible.

**Comment by Rapptz** [comment]
The exception being raised is custom, from my perspective on its own that should signal that it's on purpose. After all, the Python interpreter didn't inject that in there.

I'll try and see if I can get this specific instance fixed though.

**Comment by ziyadm** [comment]
Even if it is by design, it is not clear to the caller that they shouldn't be using this. 

A user goes here: https://discordpy.readthedocs.io/en/stable/api.html#webhookmessage

and sees the create_thread method in the Methods list.

"The exception being raised is custom, from my perspective on its own that should signal that it's on purpose. After all, the Python interpreter didn't inject that in there." <- this is a weak argument

**Comment by ziyadm** [comment]
@iandouglas did you work around this somehow (fetch guild, channel, message, and then create the thread)?

**Comment by Rapptz** [comment]
Those methods are all inherited from the documentation. It would take an obscene amount of time to override everything, on top of having too much repetition. 

To that end, I don't think it's a weak argument or an argument at all. It's a factual statement. It's clearly by design because I made the exception to raise it and it's on purpose. If it wasn't on purpose you'd see other general exceptions such as an `AttributeError` or something coming direct from the interpreter, rather than the one I provided.

**Comment by ziyadm** [comment]
it's not clear to users what to do or that they shouldn't be doing this

in any case, seems like we can just set the guild id on the webhook message obj and things will work

send a link where you accept donations @Rapptz because hopefully you have been able to get some recognition or benefit for your work here

**Comment by ziyadm** [comment]
can I update the docs somehow @Rapptz - not sure how it is all set up but even just adding a link to this thread or a message saying not to use in this case would be helpful imo

**Comment by Rapptz** [comment]
> it's not clear to users what to do or that they shouldn't be doing this

An exception is a clear indication that the action is unsupported. That's what an exception is for, "you're doing this wrong". Rewording the message might make this a bit more clear but I don't think there's anything inherently wrong with the current message. It can pop up in more situations than just this one, for example doing `create_thread` in a message received from a `DMChannel` or  an ephemeral message.

> in any case, seems like we can just set the guild id on the webhook message obj and things will work

No, if it was this simple it would have been fixed already. The thing is that these webhook objects have a partial mocked state and an incomplete or missing HTTPClient. Without this HTTPClient object the request can't go through because it doesn't have the rate limiting information that the rest of the library does. Flat out, this is entirely unsupported.

> can I update the docs somehow

Sorry, you can read my message as "I don't want to". It's a maintenance nightmare because now I have to change it in multiple places instead of one whenever we update the docs, on top of the weird interaction with translations.

**Comment by iandouglas** [comment]
> @iandouglas did you work around this somehow (fetch guild, channel, message, and then create the thread)?

Yeah, sorta.

I use something like this:

```python

discord_bot = commands.Bot(...)
discord_client = discord.Client(...)

guild = discord_bot.get_guild(my_guild_id)
channel = guild.get_channel(my_channel_id)

# write a message into my channel
webhook = AsyncDiscordWebhook(url=channel_webhook_url, content='hello world')
response = await webhook.execute()
resp = response.json()

# fetch the message object
msg = await channel.fetch_message(resp['id'])

# create a thread
thread = await msg.create_thread(name='unique_name', auto_archie_duration=60)

# store thread ID for later
thread_id = thread.id

# ... do other work

# update message thread with new message
thread = channel.get_thread(thread_id)
await thread.send('next message in the thread')
```
