### ISSUE TITLE
Generic Select types raise NameError due to #9126

### ISSUE THREAD

**Issue by AbstractUmbra** [Rapptz/discord.py#9136]
### Summary

Generic Type arguments for `discord.ui.Select` when used in a View class with decorator error.

### Reproduction Steps

I had a `ui.View` class that defined two selects. After updating beyond the commit from #9126 merge I now get a NameError on launch.

This will now raise a `NameError: name 'MangaView' is not defined`.

To reproduce:
1) Define and use a View subclass.
2) Define a method decorated with `discord.ui.select`
2a) Have the argument for `select` be Generic over the subclass. 

Full traceback if needed:-

<details>
<br>

```python3
Extension 'extensions.manga' raised an error: NameError: name 'MangaView' is not defined
Traceback (most recent call last):
  File "/home/penumbra/.cache/pypoetry/virtualenvs/mipha-kl4lG4Iw-py3.11/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 935, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/penumbra/projects/personal/mipha/extensions/manga.py", line 60, in <module>
    class MangaView(MiphaBaseView):
  File "/home/penumbra/projects/personal/mipha/extensions/manga.py", line 74, in MangaView
    @discord.ui.select(min_values=1, max_values=1, options=[])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/penumbra/.cache/pypoetry/virtualenvs/mipha-kl4lG4Iw-py3.11/lib/python3.11/site-packages/discord/ui/select.py", line 779, in decorator
    callback_cls = _get_select_callback_parameter(func)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/penumbra/.cache/pypoetry/virtualenvs/mipha-kl4lG4Iw-py3.11/lib/python3.11/site-packages/discord/ui/select.py", line 681, in _get_select_callback_parameter
    resolved = resolve_annotation(parameter.annotation, func.__globals__, func.__globals__, {})
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/penumbra/.cache/pypoetry/virtualenvs/mipha-kl4lG4Iw-py3.11/lib/python3.11/site-packages/discord/utils.py", line 1144, in resolve_annotation
    return evaluate_annotation(annotation, globalns, locals, cache)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/penumbra/.cache/pypoetry/virtualenvs/mipha-kl4lG4Iw-py3.11/lib/python3.11/site-packages/discord/utils.py", line 1086, in evaluate_annotation
    evaluated = evaluate_annotation(eval(tp, globals, locals), globals, locals, cache)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'MangaView' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/penumbra/projects/personal/mipha/bot.py", line 511, in main
    await bot.load_extension(ext)
  File "/home/penumbra/.cache/pypoetry/virtualenvs/mipha-kl4lG4Iw-py3.11/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1013, in load_extension
    await self._load_from_module_spec(spec, name)
  File "/home/penumbra/.cache/pypoetry/virtualenvs/mipha-kl4lG4Iw-py3.11/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 938, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'extensions.manga' raised an error: NameError: name 'MangaView' is not defined
```

</details>

### Minimal Reproducible Code

```python
class MangaView(discord.ui.View):
    def __init__(self) -> None:
        ...

    @discord.ui.select(min_values=1, max_values=1, options=[])
    async def select(self, interaction: discord.Interaction, item: discord.ui.Select["MangaView"]) -> None:
        ...
```

### Expected Results

I expected the class and decorators to function before #9126 was merged, that is to say, the decorator transformed `self.<method>` to a `ui.Select`.

### Actual Results

Raises a `NameError`.

### Intents

`discord.Intents(3258111)`

### System Information

$ python -m discord -v

- Python v3.11.1-final
- discord.py v2.2.0-alpha
    - discord.py metadata: v2.2.0a4658+gb671958e
- aiohttp v3.8.3
- system info: Linux 5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

This can currently be worked around by using `typing.Self` or `typing_extensions.Self` but this relies on >Python 3.8 or an external dependency we technically do not rely on.

**Comment by Zephyrkul** [comment]
I'll note really quick that another workaround is to explicitly provide `cls=discord.ui.Select` to the `@select` decorator - no additional dependency required. Not ideal given the goal of my PR was to *reduce* redundancy, but it's there.

I can work on this one since it's my mistake, but I'll have to ask Danny (or anyone interested) to weigh in on four solutions I can see.

The first and simpler solution is simply not try to eagerly evaluate the annotation if it's already not a string. This fix is already written and can be seen at [Zephyrkul:fix-9136](https://github.com/Zephyrkul/discord.py/tree/fix-9136). The downside is that this wouldn't fix the issue if a fully-stringified annotation like `"discord.ui.Select[MangaView]"` is provided (though it would at least raise a TypeError to complain about it).

The second is to delay evaluating the annotation to `View`'s `__init_subclass__`. This can guarantee that the View subclass is resolvable when resolving the annotation, but wouldn't work if, for instance, a custom Select subclass is defined *below* the View subclass and used in the View annotation. I frankly doubt this edge case would happen, but it's still a possibility.

The third is to delay evaluating the annotation even further, to `View`'s `__init__`, and cache the result then. This would be the most "robust" against forward annotations, but also might be going a bit too far into the reeds to fix a minor edge case that likely wouldn't happen very often, if at all, in real code.

**Comment by Rapptz** [comment]
Yeah this is one of the main problems with evaluating annotations. By necessity a lot of times they won't refer to actual nameable types since they'd be under a `TYPE_CHECKING` block. Realistically the easiest course of action is just to revert the commit. The harder approach would be to properly fix it so it evaluates to `discord.ui.Select[typing.ForwardRef['MangaView']]` but this is actually incredibly finicky because if you don't do the string literal approach then the NameError will happen regardless.

Let's take the following code:

```py
from __future__ import annotations

if TYPE_CHECKING:
   from fancy_select import FancySelect

class View(ui.View):
    def __init__(self) -> None:
        ...

    @discord.ui.select(min_values=1, max_values=1, options=[])
    async def select(self, interaction: discord.Interaction, item: FancySelect[View]) -> None:
        ...
```

> The first and simpler solution is simply not try to eagerly evaluate the annotation if it's already not a string.

In here, the annotation would be `"FancySelect[View]"` as a string. Evaluating this would cause an error.

> The second is to delay evaluating the annotation to View's `__init_subclass__`. 

Even if it's delayed, the evaluation would still cause an error.

> The third is to delay evaluating the annotation even further, to View's __init__, and cache the result then.

Unfortunately, still an error.

Best course from what I can see is just to revert the commit since it'll work fine with how it was supposed to be in the first place.

**Comment by Zephyrkul** [comment]
> Let's take the following code:
> 
> ```python
> from __future__ import annotations
> 
> if TYPE_CHECKING:
>    from fancy_select import FancySelect
> 
> class View(ui.View):
>     def __init__(self) -> None:
>         ...
> 
>     @discord.ui.select(min_values=1, max_values=1, options=[])
>     async def select(self, interaction: discord.Interaction, item: FancySelect[View]) -> None:
>         ...
> ```

This would error on the old version too (since you couldn't pass `cls=` at runtime) so I don't see how this is relevant.

In any case, I do have a solution in my local clone which does evaluate to `discord.ui.Select[typing.ForwardRef['MangaView']]`, but if the best course in your eyes is to just revert the commit then I won't PR it.

**Comment by Zephyrkul** [comment]
On second thought, may as well PR it just to make it easier to review it, but please feel free to turn it down and revert the change from 9126 instead if you want to.
