### ISSUE TITLE
Doesn’t support Python 3.6

### ISSUE THREAD

**Issue by eltontay11** [Rapptz/discord.py#925]
I cannot run discord.py on a Python 3.6 Launcher. Import discord gives a error.

**Comment by Vexs** [comment]
Then you haven't installed discord.py on python 3.6

**Comment by eltontay11** [comment]
Then how do you install it on python 3.6?

**Comment by eltontay11** [comment]
I use command prompt and “pip install discord.py”. When I use Python Core 3.5 I can import but 3.6 I cannot.

**Comment by ngbeslhang** [comment]
Try `python3.6 -m pip` instead.

**Comment by eltontay11** [comment]
I already uninstalled and now using 3.5.3. But the code is compatible between 3.5 and 3.6 right?

**Comment by Vexs** [comment]
Some things added in 3.6 were not in 3.5 because if they were they would not have been added. If you were using these features in 3.6, they will not work in 3.5, like f-strings. 

In other words, try it and see. The lib is compatible however.

**Comment by mikevb1** [comment]
The lib is compatible with 3.4.2+, so it works with 3.6. You do, however, have to install it again with 3.6's pip, because each Python install has its own package environment. The reason `pip install` installed for 3.5 instead of 3.6 is because you didn't set 3.6 as the default or 3.5 comes first in your PATH.

**Comment by eltontay11** [comment]
Ok, thank you, my hosting is on 3.6 so I was thinking if I coded it in 3.5 it might not work on 3.6. Thanks for the clarification.
