### ISSUE TITLE
Make `interaction.add_reply()`

### ISSUE THREAD

**Issue by 2br-2b** [Rapptz/discord.py#9337]
### Summary

Make `interaction.add_reply()` which automatically uses the correct response method based on whether the interaction has been replied to yet.

### What is the feature request for?

The core library

### The Problem

Given `interaction`, if you don't know if it has been responded to, you have to add a few lines of code to check if it has been responded to and use a different reply command based on the result. This requires developers to keep track of this manually, use the same few lines throughout their codebase to check and respond accordingly, or write their own generic `reply_to_message(interaction, args)` function.

This also makes it harder for new developers, as they might be confused at first why having two `interaction.response.send_message()`s in the same function gives them an error.

### The Ideal Solution

The ideal solution would be to have an `interaction.add_reply()` function which automatically checks this and replies in the appropriate way.

This could also make it easier for new users, as they could just learn `interaction.add_reply()` instead of needing to remember two separate functions (`interaction.followup.send()` and `interaction.response.send_message()`).

```python
await interaction.add_reply(args)
```

### The Current Solution

```python
def reply_to_interaction(interaction: discord.Interaction, args):
    if interaction.response.is_done():
        await interaction.followup.send(args)
    else:
        await interaction.response.send_message(args)
```

### Additional Context

In order to match earlier naming conventions, `interaction.reply()` might be a better name.

The only potential downside I see to this is the additional overhead of checking each time if an interaction has been responded to yet.

**Comment by mikeshardmind** [comment]
There's another subtle downside here. initial response and/or deferring failing on double-use is a good thing. it acts as a natural way for a single process to "claim" it's handling an interaction. By promoting a pattern that hides the internal design of this, you force people to know more to get benefits they were previously getting for free, because you've provided them a seemingly better option that has a complex drawback.

An example where this would be useful is spinning up an extra instance of a slash command bot prior to shutting down the previous one, which might be done at scale to increase shard count. At no point in this do you have to coordinate this with additional machinery nor have any downtime if your bot is powered by interactions. (anything event based would still need coordination)

**Comment by mikeshardmind** [comment]
as an addendum to that, you should know based on your own code if you've responded or not if you *don't* have that case. You shouldn't need to check...

**Comment by 2br-2b** [comment]
> There's another subtle downside here. initial response and/or deferring failing on double-use is a good thing. it acts as a natural way for a single process to "claim" it's handling an interaction. By promoting a pattern that hides the internal design of this, you force people to know more to get benefits they were previously getting for free, because you've provided them a seemingly better option that has a complex drawback.

Interesting - I hadn't thought of that use case before, but I'll definitely be looking into it in the future. I had assumed issues would come up if I were to do this (despite testing to the contrary), but I guess I was wrong 😅. I or someone else should write something up about this in the documentation. If no one else does, then I'll probably write something up after I play around with this a bit to try to figure out the its quirks

> An example where this would be useful is spinning up an extra instance of a slash command bot prior to shutting down the previous one, which might be done at scale to increase shard count. At no point in this do you have to coordinate this with additional machinery nor have any downtime if your bot is powered by interactions. (anything event based would still need coordination)

Couldn't this be accomplished slightly differently by adding the following code to the beginning of each slash command:
```python
try:
    await interaction.response.defer()
except discord.errors.NotFound:
    # another instance has already claimed this command
    return
```

It seems to me (who again, doesn't have that much experience with this) that this would be better. That way, in a hypothetical bot with a `/increment` command, the two separate instances of the bot don't end up incrementing the number by two; one bot will defer the interaction successfully while the other will catch the error and do nothing.

> as an addendum to that, you should know based on your own code if you've responded or not. If you don't have that case, then you don't need to check, your code flow dictates if you have responded or not already, and if you do have that case, you especially don't want to check, failure for duplicate means it's already being handled

I see what you mean by that. I think this would be more aimed at beginners and at specific use cases rather than being used to replace the other commands. I'm not thinking that we eliminate the other two commands; this is just an addition for ease of use.

For example, in my bot, I've got a `reply_to_message()` function which takes an interaction, some content/files/etc to have in the message and automatically formats the message it before sending it (adding the content to an embed with a specific configuration, etc.). As a result, I either have to pass `reply_to_message()` a parameter for whether this is a followup message or not (which just ended up being tedious) or to just check if the interaction has been responded to yet (which is what I do now).

**Comment by 2br-2b** [comment]
Note about the example code: per [Discord's docs](https://discord.com/developers/docs/topics/rate-limits#invalid-request-limit-aka-cloudflare-bans), getting too many error within a short amount of time will cause issues with rate limits, so this is probably not the best solution for larger bots.

**Comment by SebbyLaw** [comment]
This sort of "ease of use" function is a footgun for any application larger than a hobby project. Similar to a language (javascript) allowing you to use the addition operator on two completely unrelated types and have things just work:tm: may seem "helpful" at first glance but really just introduce bugs and headaches in the future. Similarly, obfuscating a *very important detail* about how interactions work is not good for a library to be doing.

**Comment by mikeshardmind** [comment]
Not responging to everything in order...

Starting with
> Note about the example code: per [Discord's docs](https://discord.com/developers/docs/topics/rate-limits#invalid-request-limit-aka-cloudflare-bans), getting too many error within a short amount of time will cause issues with rate limits, so this is probably not the best solution for larger bots.

Looking at the page here, you have:
> An invalid request is one that results in 401, 403, or 429 statuses.
This is the primary one that people run into with Cloudflare bans and doesn't apply here, note the lack of 404, 400

and slightly further down you have
> In addition, you are expected to reasonably account for other invalid statuses. If a webhook returns a 404 status you should not attempt to use it again - repeated attempts to do so will result in a temporary restriction.

This is where things get slightly more interesting, but it's worth pointing out the example given for 404 handling of webhooks here doesn't apply The initial response to an interaction is not a webhook: /interactions/<interaction_id>/<interaction_token>/callback (or a response to POST in non-gateway slash commands)

followups are: /webhooks/<application_id>/<interaction_token>/...

I'd call using the scale-aware design provided by Discord in a way that helps handle gracefully switching over instances within reasonable design and accounting for statuses, but if you hear otherwise in a nuanced discussion with a developer for Discord, please let me know so I can update my assumptions on this.


next, lets look at

> Couldn't this be accomplished slightly differently by adding the following code to the beginning of each slash command:
> ```py
> try:
>     await interaction.response.defer()
> except discord.errors.NotFound:
>     # another instance has already claimed this command
>     return
> ```

Yep, though going this route precludes the possibility that a command is responded to as part of the initial response and doesn't need a follow-up at all, in the case of a slash command that edited data, this would be preferred to prevent multiple workers from doing the update.

It would be a relatively easy pattern to use as-is though with few drawbacks other than likely wanting to specify ephemeral in some cases, aware of how that particular interaction will later respond. Unfortunately, The part about ephemeral behavior with defer is the main reason this can't be convenience wrapped in a slightly different manner that "just works" without drawbacks. If the defer had no bearing on what you could do in a followup, you could reasonably request that that code block, as-is, be handled by the library, and your callback only be given access to the followup should it not error out.

**Comment by 2br-2b** [comment]
Sounds good. Thanks for the help and the information! Even though this won't get implemented, thanks for taking the time to explain _why_ this won't be implemented instead of just brushing me off. Now, even though I didn't help improve the library ~~yet~~, I at least learned a bit more about how it works.

Have a great day!
