### ISSUE TITLE
Audit Log Entry

### ISSUE THREAD

**Issue by ZironDev** [Rapptz/discord.py#9385]
### Summary

Fix Audit log Entry of Integration Create Which Gives None in Return

### Reproduction Steps

If a non whitelist user updates any of the bot's integration present in a server where antinuke system of my bot is enabled then bot will ban that user

### Minimal Reproducible Code

```python
import discord

client = commands.AutoShardedBot(command_prefix="",intents=discord.Intents.all(),allowed_mentions=discord.AllowedMentions(everyone=False, replied_user=False,roles=False),case_insensitive=True,strip_after_prefix=True,replied_user=False,shard_count=1)


@client.event
async def on_ready():
    print(f'Logged in as {client.user} (ID: {client.user.id})')

@client.event
async def on_integration_update(before, after):
    # Check if the integration updated is related to your bot
    if after.id == YOUR_BOT_INTEGRATION_ID:
        # Retrieve the user ID of the user who updated the bot integration
        user_id = after.user.id
        # Retrieve the user object from the user ID
        user = await client.fetch_user(user_id)
        # Print the username of the user who updated the bot integration on the console
        print(f'{user.name} updated the bot integration')

client.run('YOUR_BOT_TOKEN')
```

### Expected Results

The result should be returning name of the user but in return we get none 

### Actual Results

If a Integration create , update or delete is entry is created than we are not able to fetch it by given audit log action == name as integration_create , integration_update , integration_delete

### Intents

Message , Members

### System Information

Discord py :- 2.2.2
Python :- 3.8
Windows :- 10.10.0 ( While Developing the Bot )
Ubuntu :- 22.04 ( Where i Host My Bot )

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Puncher1** [comment]
As the [docs for `integration.user`](https://discordpy.readthedocs.io/en/latest/api.html?highlight=on_integration_update#discord.Integration.user) says :
> The user that added this integration.

You don't get the user that updated the integration. With that you only get the creator of the integration

**Comment by mikeshardmind** [comment]
> If a non whitelist user updates any of the bot's integration present in a server where antinuke system of my bot is enabled then bot will ban that user

As an aside, If you don't want users doing things, it's more effective and less error-prone to just not give them permission to do that. "antinuke" is a relatively terrible idea as it involves knowingly giving more permissions than you want people to use, then banning them for using those permissions. You can granularly grant access by *granting* actions through a bot, rather than punishing after the fact for a perceived overreach. This comes with the added benefit of not needing to be reactive to something you didn't want to happen.

Antinuke is especially problematic if you aren't actually reading the docs for what information Discord is giving you before building features based on it and incorrectly believing you can detect certain things reliably.
