### ISSUE TITLE
Discord bot wont DM user

### ISSUE THREAD

**Issue by seant4** [Rapptz/discord.py#940]
I have been trying to get my bot to dm a user, essentially, it needs to take the input of a user and dm that. So it will ask "Who is player 1" The user that is then inputed needs to be direct messaged, i tried setting the users input to a object called Player1, and then doing 
await client.send_message(pl1, 'It worked!'), but i get an error saying it needs to be a user, not a string (i convert it to a string earlier), any ideas? should i remove that part where it is converted?

**Comment by BlackSynder** [comment]
You've been opening a lot of issues lately, you might want to join [the official server](https://discord.gg/r3sSKJJ) to make it easier for everyone involved.

**Comment by seant4** [comment]
ok thank you

**Comment by giorgiocav1** [comment]
To get a user, there are many ways to get it:
-If the user sent a message, use the `on_message(message)` event and use `message.author` to get the user that wrote the message
-If you have the id or the name of the user, use `server.get_member(id)` or `server.get_member_named(member_name)`

btw to get the server don't use `discord.Server()` but `list(client.servers)[0]` if it is only joined to one server, or if it is in several servers at once use `[y.id for y in list(client.servers)][the_server_id]`

**Comment by BMan12321** [comment]
I'm not really able to tell you what's wrong since i"m not seeing your code, However, if you are trying to have the bot DM someone. you would have to do something like this.
```python
@bot.command(pass_context = True)
async def dm(ctx, member : discord.Member, *, content: str):
    await bot.send_message(member, content)
```
Using that code will allow you to send a command to the bot and then the bot will DM the person whatever it was you wanted.
Usage: if your prefix was "."
`.dm @user This is a random test`
That would then make the bot DM whoever "@user" is with a message just saying "This is a random test".

Hope this was helpful!

**Comment by Firazed** [comment]
I just had the same issue, my input was discord IDs. I hope this helps you, it worked for me. I used get_user_info of discord.client. This will return a "generator" if you do not put the await in front. Make sure your discord ID is cast as an int. There is probably a similar function if your input is name rather than id.
```
user = await client.get_user_info(id)
await self.bot.send_message(user, msg)
```

**Comment by Cinorhc** [comment]
anyone know how to do this in rewrite?

**Comment by Phxntxm** [comment]
Please do not necrobump issues. To answer the question you can use this method [here](https://discordpy.readthedocs.io/en/latest/api.html#discord.Member.send) however your question would be more appropriate in the [discord.py guild](https://discord.gg/r3sSKJJ) as this issue tracker is more for issues with the library itself, not teaching how to use it.
