### ISSUE TITLE
issue with running two bots with one script

### ISSUE THREAD

**Issue by PotatoPixel** [Rapptz/discord.py#942]
I was looking at https://github.com/Rapptz/discord.py/issues/516, and I tried using the solution, and got this:
```
Exception in default exception handler
Traceback (most recent call last):
  File "C:\Users\dindon\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 1284, in call_exception_handler
    self.default_exception_handler(context)
  File "C:\Users\dindon\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 1256, in default_exception_handler
    value = repr(value)
  File "C:\Users\dindon\AppData\Local\Programs\Python\Python36\lib\asyncio\base_tasks.py", line 15, in _task_repr_info
    coro = coroutines._format_coroutine(task._coro)
  File "C:\Users\dindon\AppData\Local\Programs\Python\Python36\lib\asyncio\coroutines.py", line 274, in _format_coroutine
    assert iscoroutine(coro)
AssertionError
```

which was probably caused by this:

```python
loop = asyncio.get_event_loop()
loop.create_task(super().start(token))
loop.create_task(selfbot.run())
try:
    loop.run_forever()
finally:
    loop.stop()
```

where `super()` is `discord.Client`, and `selfbot.run()` is 

```python
def run(self):
    print("Selfbot ready")
    super().start(self.token,bot=False) # super() is also discord.Client
```

what went wrong here?

**Comment by SourSpoon** [comment]
run needs to be a coroutine.

a couple of things,
first take a look at this [link](https://support.discordapp.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-)
second, questions about discord.py should really be directed at the [discord.py discord](https://discord.gg/r3sSKJJ) or the [discord api](https://discord.gg/discord-api) discord servers.

**Comment by Gorialis** [comment]
`run` does **not** need to be coroutine (it isn't supposed to be one). Your issue is that `start` on the other hand *is* a coroutine. You can fix this by calling `super().run` instead.

As a side note, `run` being executed does *not* mean your bot is ready and you should be using the [on_ready](http://discordpy.readthedocs.io/en/latest/api.html#discord.on_ready) event or [wait_until_ready](http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.wait_until_ready) coroutine to detect this instead.
