### ISSUE TITLE
Discord Bot + BottlePy/Flask

### ISSUE THREAD

**Issue by kawaaii** [Rapptz/discord.py#943]
Hello, 

I'm now a couple hours busy to get information from my bot
to be extracted to a page in my website.
So I can show for example how many servers my bot is in.

I tried for this 3 different web-server's
- Flask
- Hug
- Bottle

Now, what ever I try, It seems to not make any connection to the discord server.
I have tried it with and without loops, with threaths but I seem to not get it working.

This is the last thing I have tried.

````py
import discord
from discord.ext import commands
import asyncio
from bottle import route, run, template

client = discord.Client()
loop = asyncio.get_event_loop()

@route('/servers')
def index():
    servers = len(client.guilds)
    return template('Servers: <b>{{servers}}</b>!', servers=servers)

try:
    loop.create_task(client.start('mytokengoeshere'))
    loop.create_task(run(host='localhost', port=1212))
    loop.run_forever()
finally:
    loop.stop()
````

I tried also different variations, like `client.start`, `bot.start`, `client.run` etc.
Maybe someone else can help me further.

- Ashley

**Comment by Gorialis** [comment]
discord.py is an asyncio-based library and therefore things running beside it must either also be asyncio-compatible, running on the same event loop, or in a different thread.

In your example code, the issue is that when you run `run(host='localhost', port=1212)` the thread blocks in order to serve your server content and therefore won't make it to the point where you start up your event loop (and therefore your bot) until the server dies.

Both Flask and Bottle don't appear to be asyncio-compatible by default (although Bottle [appears to have some experimental implementation](https://github.com/bottlepy/bottle/blob/master/bottle.py#L3499). You'd have to use them on another thread in order for them to operate properly (note that by default this creates single-threaded servers that can only handle 1 request at once).

The best solution for this would either be to find equivalent asyncio-compatible libraries or to separate your server and bot into different scripts that push/pull data from a database or websocket.

**Comment by kawaaii** [comment]
I think, then this is the easier and best way to do it:

**to separate your server and bot into different scripts that push/pull data from a database or websocket.**

**Comment by davidsluo** [comment]
If you want to try something new, [Sanic](https://github.com/channelcat/sanic) is asyncio compatible. Although, I agree, making it a separate thing altogether is probably the best way to go.

**Comment by kawaaii** [comment]
Thank you for your reaction, I will have a look into it since, I kinda didnt tried anythig anymore after my last post!
