### ISSUE TITLE
Update README for rewrite branch.

### ISSUE THREAD

**Issue by deltamimikyu** [Rapptz/discord.py#946]
Can we update the README in the rewrite branch to reflect the correct installation instructions? Some new users will likely find this confusing otherwise, as it shows code snippets for the new library, but the installation will still lead the user to install version zero.

**Comment by Vexs** [comment]
This is intentional, the rewrite docs are written as if that's the current branch.

**Comment by deltamimikyu** [comment]
Does that not leave room for confusion?

**Comment by Helehelehele** [comment]
In it's current state, rewrite branch is not meant for new users. It is still in development. The only reason it's published as a branch was so that core users could play around with it, and possibly "break it".

So yes, it does leave room for confusion. And it's meant to. "New users" is not the audience.
