### ISSUE TITLE
Add the ability to obtain user IDs from global names.

### ISSUE THREAD

**Issue by creeper-0910** [Rapptz/discord.py#9502]
### Summary

Add the ability to obtain user IDs from global names.

### What is the feature request for?

The core library

### The Problem

We believe that using global names to obtain IDs will be easier to handle because names will not change as often as before.

### The Ideal Solution

global_name can be used in discord.util.get.

**Comment by Rapptz** [comment]
`global_name` is a global nickname. `name` is the "unique" username if they're migrated. That being said you can do whatever you want with it, e.g. `discord.utils.get(bot.users, name='whatever')`. If you're looking for an endpoint for this it doesn't exist and I can't implement it since I'm not Discord, you'd have to ask the discord developers in the discord API docs repository.

**Comment by creeper-0910** [comment]
Understood, I will contact Discord.
Thank you for your kind response!
