### ISSUE TITLE
Add exception raised to Client.on_error

### ISSUE THREAD

**Issue by gustavi** [Rapptz/discord.py#9520]
### Summary

Add exception raised to Client.on_error

### What is the feature request for?

The core library

### The Problem

I'm trying to stop the bot if a specific exception is raised. The current `on_error` method is called each time an exception is raised but there is not way to known which exception is involved.

### The Ideal Solution

```diff
    async def _run_event(
        self,
        coro: Callable[..., Coroutine[Any, Any, Any]],
        event_name: str,
        *args: Any,
        **kwargs: Any,
    ) -> None:
        try:
            await coro(*args, **kwargs)
        except asyncio.CancelledError:
            pass
-        except Exception:
+        except Exception as exception :
            try:
-                await self.on_error(event_name, *args, **kwargs)
+                await self.on_error(event_name, exception, *args, **kwargs)
            except asyncio.CancelledError:
                pass

...

-    async def on_error(self, event_method: str, /, *args: Any, **kwargs: Any) -> None:
+    async def on_error(self, event_method: str, exception: ..., /, *args: Any, **kwargs: Any) -> None:
```

### The Current Solution

I use a dirty hack with `self._my_exception_that_stop_the_bot = True` each time I raise it.

I my specific case I think it could work but if I would like to catch an exception for another library (like a database connection failure) I have to patch client myself.

**Comment by Rapptz** [comment]
This is a breaking change. In order to get this information you use the standard library's [`sys.exc_info`](https://docs.python.org/3/library/sys.html#sys.exc_info) as [documented](https://discordpy.readthedocs.io/en/stable/api.html#discord.on_error).

![`sys.exc_info` highlighted in the documentation for `on_error`](https://user-images.githubusercontent.com/1695103/247482165-88c3d3a1-b286-41fd-a4f1-45dd85a28ecb.png)
