### ISSUE TITLE
on_member_ban trigger issue

### ISSUE THREAD

**Issue by lepeli** [Rapptz/discord.py#954]
The on_member_ban event doesn't triggers properly 

Test : 
I used 4 instance of my bot using a simple code , with rewrite version

```python
class test:
    def __init__(self , bot):
        self.bot = bot
    
    async def on_member_ban(self , guild , member):
        print(f"[MEMBER BANNED] {member} , {guild}")

def setup(bot):
    bot.add_cog(test(bot)) 
```
My bot has 473 servers 

Here is the results of the test:
![Results](https://i-love.lepeli.fr/3Td2ea.png)

**Comment by Rapptz** [comment]
What exactly is this showcasing?

**Comment by Rapptz** [comment]
In any case -- this event is pretty straightforward and is just a pass through from Discord to you.

The only discrimination that causes this event to not be triggered "properly" is when the guild is not found, ergo it's done before that guild's `GUILD_CREATE` has been reached. Since I don't think this is the case (or maybe it is) then I don't know what to tell you.

Nevertheless, the library doesn't do anything special with the event to warrant the creation of this issue or needing fixing on my end.
