### ISSUE TITLE
Examples - App Commands duplicates the commands

### ISSUE THREAD

**Issue by and7ey** [Rapptz/discord.py#9573]
### Summary

When example is used, the commands are added twice

### Reproduction Steps

1. copy-paste the example (https://github.com/Rapptz/discord.py/blob/master/examples/app_commands/basic.py)
2. run python script basic.py
3. stop the script
4. run the script second time

commands `add`, `hello` appears twice:
![photo_2023-09-20 15 55 16](https://github.com/Rapptz/discord.py/assets/900474/f51802fb-1f4c-4072-8e06-c8217a891fae)

### Expected Results

commands are NOT duplicated

### Actual Results

commands ARE duplicated

### Intents

.default()

### System Information

na

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by No767** [comment]
Duplicate commands are usually due to auto-syncing commands (usually in `setup_hook`). For this reason, it's always recommended to [manually sync your commands](https://about.abstractumbra.dev/discord.py/2023/01/29/sync-command-example.html). But for the purposes of learning and to make it easier, the examples are auto-synced so the commands show up and can be used for demonstration purposes.

**Comment by Rapptz** [comment]
The example syncs to the guild as that's what it's showcasing but you're syncing globally as well which led to the duplicate.

If you want to sync globally then you need to remove `copy_global_to` and the `guild=` keyword argument from `sync`. To remove the pre-existing commands you need to do:

```py
self.tree.clear_commands(guild=MY_GUILD)
await self.tree.sync(guild=MY_GUILD)
```
