### ISSUE TITLE
<Future pending> on get_bans()

### ISSUE THREAD

**Issue by SoraTheDev** [Rapptz/discord.py#961]
I'm trying to use get_bans() to return a list of all of the banned players on this server but it's not working correctly.

Here is my code: 

  if message.content == "!bans":

        bans = client.get_bans(discord.Server)

        await client.send_message(message.channel, "The following members have been banned:")

        time.sleep(2)

        for ban in bans:

            await client.send_message(message.channel, ban)

            time.sleep(1)

However, it returns this error:

`raiseHTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400)`

And the bot sends a message saying <Future pending> on the chat.

How can I solve this?

**Comment by Altarrel** [comment]
You want an instance of discord.Server, not discord.Server. You probably want message.server. Also there is a Discord server you can ask for help on https://discord.gg/r3sSKJJ

**Comment by Rapptz** [comment]
1. [You're blocking when using `time.sleep`](http://discordpy.readthedocs.io/en/latest/faq.html#what-does-blocking-mean)
2. You need an actual instance of type `discord.Server`, not passing the actual type (this is basic python knowledge), consider using `message.server` instead.
3. You need to `await` the coroutine because as noted, [the function is a coroutine](http://discordpy.rtfd.io/en/latest/api.html#discord.Client.get_bans).
