### ISSUE TITLE
How to return an image

### ISSUE THREAD

**Issue by Shintaro27071997** [Rapptz/discord.py#988]
I want to write a code to user enter a word and the bot returns an image from an URL. But I don't know how to write it. Need code

**Comment by scragly** [comment]
Nobody is likely to write your bot for you. If you don't know how to do something, the best thing to do is learn. 

If you got caught on a specific thing, such as the way you're using a lib function isn't resulting in what you expect after trying to figure it out yourself, then most of us in the support server will help out and try prod you in the right direction. 

Nobody is going to step through the process of figuring out the logical steps and the basic python to use to get there though, as it's not going to help you learn, since you won't actually understand how any of that code works.
