### ISSUE TITLE
Change own nickname

### ISSUE THREAD

**Issue by Blacksilver42** [Rapptz/discord.py#992]
A function, say, `change_own_nick(server, name)` that, well, changes the bot's nickname automagically.

**Comment by Rapptz** [comment]
Just use `change_nickname` with your own member passed in.

**Comment by Blacksilver42** [comment]
How should I get the bot's member?

**Comment by Rapptz** [comment]
http://discordpy.rtfd.io/en/latest/api.html#discord.Server.me

**Comment by Pg96** [comment]
I have a question about this topic. 
I'm following what you told Blacksilver42 and I did the following:

(this is part of a command I created in order to change the Bot's nickname)
`me = context.message.server.me`
`client.change_nickname(me, "Newnickname")`

I get no errors but the bot does not change its nickname and I don't know why (roles allow nickname change and I also tried it by granting Admin privileges to the bot).

Do you have any suggestions for me? Thanks in advance!

**Comment by Pg96** [comment]
Thank you @Vrori . Now it works as it should!

**Comment by Vrori** [comment]
Anytime!

Happy developing.
